### ISSUE TITLE
☂️ [GEP-31] Support for In-Place Node Updates

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#10219]
**What would you like to be added**:
We like/need to offer, for all spec changes, a way to update cluster nodes in-place (all except for the ones where we have no other technical alternative, e.g. switching out physical machines will always require node rolling).

For these in-place node updates, we need to understand what exactly should to be done:
- Roll the nodes if otherwise technically impossible (a physical machine is no longer operational or goes into maintenance)
- Update the node (with or without drain; has its pros and cons) and reboot (e.g. OS update)
- Drain the node before we update it and restart the `kubelet` (e.g. K8s minor update, see [ref](https://kubernetes.io/releases/version-skew-policy/#kubelet-1))
- Just update the node (w/o drain) and restart the `kubelet` (e.g. K8s patch update, see [ref](https://kubernetes.io/releases/version-skew-policy/#kubelet-1))

All of the above (and maybe more cases) need to be detected and should trigger different forms of in-place node updates.

Note: Maybe some stakeholders would want to avoid an actual drain that would move the pod to another machine. In this case, we might get away with "local cleaning" (files/containers) after we stop the kubelet. When it restarts, it won't know that it used to run these containers. Would that be of any help to some users?

Until now, Gardener only supported the very first and last use case. Now we need to support also all the other use cases, trying to hold on to the machines (whether physical or virtual) and their Kubernetes node resources indefinitely, while keeping the impact under update as minimal as possible.

**Why is this needed**:
Physical machines/bare metal nodes (whether manually joined or programmatically provisioned) cannot be easily rolled like we roll today virtual machines. Physical machines/bare metal nodes are rather "pets", not "cattle" (like virtual machines). Usually:
- They have long boot times, unless they already fully booted and can be (UEFI) fast-booted without running certain checks like POST (Power-On Self-Test, e.g. memory tests)
- They have long cleanup/sanitization times to erase all data before returning them to a pool
- They have locally attached disks that cannot be "moved" like network-attached volumes that can be "re-attached" easily
- They are rather large in size and limited in number and not as interchangeable and sliceable as virtual machines

This is why we need to find a way to preserve them/never roll this kind nodes. In some cases, this may be also beneficial to brownfield/singleton applications/services that are rather sensitive to node rolling/disruptions in general.

### Tasks
- Proof of Concept and Design Considerations
  - [x] Perform a small PoC to validate the design ideas and the overall approach
  - [x] https://github.com/gardener/gardener/pull/10828
- **Gardener**
  - [x] API changes
    - [x] `CloudProfie` https://github.com/gardener/gardener/pull/11191
      - [x] https://github.com/gardener/gardener/pull/12507 
      - [x] https://github.com/gardener/gardener/pull/12577
    - [x] `Shoot` https://github.com/gardener/gardener/pull/11191
      - [x] https://github.com/gardener/gardener/pull/12438
    - [x] `Worker` Extension https://github.com/gardener/gardener/pull/11191
    - [x] `OperatingSystemConfig` Extension https://github.com/gardener/gardener/pull/11191
  - [x]  https://github.com/gardener/gardener/pull/11393
    - [x] https://github.com/gardener/gardener/pull/12241
  - [x] https://github.com/gardener/gardener/pull/11631
  - [x] https://github.com/gardener/gardener/pull/11713
    - [x] https://github.com/gardener/gardener/pull/12055 (reverted)
    - ~~https://github.com/gardener/gardener/pull/12118~~
    - [x] https://github.com/gardener/gardener/pull/12178
  - [x] https://github.com/gardener/gardener/pull/11718
    - [x] https://github.com/gardener/gardener/pull/11964
    - [x] https://github.com/gardener/gardener/pull/11995
    - [x] https://github.com/gardener/gardener/pull/12542
  - [x] https://github.com/gardener/gardener/pull/11843
  - [x] https://github.com/gardener/gardener/pull/11844
    - [x] https://github.com/gardener/gardener/pull/12290
  - [x] Vendor MCM with in-place support - https://github.com/gardener/gardener/pull/11963
  - [x] https://github.com/gardener/gardener/pull/11953
  - [x] https://github.com/gardener/gardener/pull/12005
  - [x] Add TestMachinery test https://github.com/gardener/gardener/pull/11990
    - [x] https://github.com/gardener/gardener/pull/12588
  - [x] https://github.com/gardener/gardener/pull/12359
- **Test-infra**
  - [x] https://github.com/gardener/test-infra/pull/735 
  - [x] https://github.com/gardener/test-infra/pull/736
- **Provider-Extensions** Vendor Gardener and adapt provider extensions to support in-place update.
   - [x] [provider-alicloud](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/795: Released with [v1.62.0](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.62.0) 
   - [x] [provider-aws](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/1276: Released with [v1.62.0](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.62.0) 
     - [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1325
     - [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1345: Released with [v1.62.2](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.62.2) 
   - [x] [provider-gcp](https://github.com/gardener/gardener-extension-provider-gcp) https://github.com/gardener/gardener-extension-provider-gcp/pull/1069: Released with [v1.45.0](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.45.0)
   - [x] [provider-azure](https://github.com/gardener/gardener-extension-provider-azure) https://github.com/gardener/gardener-extension-provider-azure/pull/1181: Released with [v1.54.0](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.54.0)
   - [x] [provider-openstack](https://github.com/gardener/gardener-extension-provider-openstack) https://github.com/gardener/gardener-extension-provider-openstack/pull/1054: Released with [v1.48.0](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.48.0)
- **OS-Extension** - Vendor Gardener and adapt OS extensions of OS which support in-Place Update.
  - [x] [os-gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux/): https://github.com/gardener/gardener-extension-os-gardenlinux/pull/260 Released with [v0.31.0](https://github.com/gardener/gardener-extension-os-gardenlinux/releases/tag/v0.31.0) 
    - [x] https://github.com/gardener/gardener-extension-os-gardenlinux/pull/277

**Comment by vlerenc** [comment]
We collected the following requirements/comments from adopters using/planning to use Gardener on bare metal hardware:
- Implement all updates in-place, i.e. preserve the nodes and also the machines (currently not possible for k8s minor version or OS updates, but default for k8s patch version updates and some other changes -> requires A/B booting; then we can even update the OS)
- Respond to external events such as "Machine will be shut down soon/when, please gracefully drain immediately", which could be handled by an extension directly (or indirectly via the metadata service or similar sources and the node agent)
- Being able to pause a roll-out (possible only from within the seed and only for machine roll-outs/with MCM)
- Temporarily exclude individual machines from roll-out (before or while an update is ongoing)
- Make it possible to “hook in” remote maintenance controllers (it isn't really clear, whether a hook is really necessary; our philosophy until now was, that the deployments should/must steer that via PDBs, but there can be more complicated pre-conditions that are unrelated to PDBs, e.g. whether or not the image registry is currently up and running/available).

Ideally, people can steer (e.g. https://github.com/sapcc/maintenance-controller) their roll-outs. As said, there are some checks that do not really fit into PDBs (e.g. excluding a single node/machine for a longer period of time because of “some reasons” or pausing the roll-out because the image registry is down), so if we want to avoid the last 3 bullet points above, i.e. if we want to avoid pause/exclusion/hooks, we could also offer the following maybe:
- Offer a different machine deployment update strategy `OnDelete` analogous to the `StatefulSet`, where the NodeAgent/MCM does not roll immediately and only new nodes receive the new spec (this would also avoid the combinatorial explosion of worker pools that we see with some adopters/users)
- Nothing happens until the node is (in-place) updated+rebooted or drained+deleted (no matter what was changed, e.g. even a different OS/version; just as an example)
- The stakeholder has their own specific maintenance controller running inside or outside of the cluster
- It sets labels to (in-place) update+reboot the machine (not yet supported) or to drain+delete it (already supported by MCM), so they can steer/decide what to do as they see fit, when they see fit (today one machine, the next machine 3 days later, if they need)
- Until then, some of the requirements (but not k8s minor version/OS updates) can also be implemented via a DaemonSet instead (that watches the associated node labels and “does things locally”), but real support in GardenLinux/NodeAgent would make this feature more versatile/useful

**Comment by vlerenc** [comment]
Garden Linux PoV:
 
- We will target only Garden Linux for in-place updates. People shall switch to Garden Linux, if they want in-place updates (Garden Linux as differentiator; no time nor interest in supporting other operating systems; no deep stack innovation/integration possible).
- SecureBoot and immutability are desired from security PoV.
- For SecureBoot (https://wiki.debian.org/SecureBoot), the UKI needs to be signed. The Garden Linux team does the signing with an intermediate CA. While it is not possible to replace the root CA in many cases (e.g. stamped into the AWS AMI, cannot be updated programmatically in the BIOS of bare metal machines and must be updated manually by a human operator), rotating the intermediate CA is still possible (no problem for us, i.e. we can hold onto a machine for as long as the root CA certificate is valid).
- This can be combined with in-place updates as we can steer which folders are mutable and immutable. The kernel and more is delivered in a UKI file (https://uapi-group.org/specifications/specs/unified_kernel_image/) that can be downloaded and booted into (into memory; reboot very fast in ~30s or so depending on various factors).
- We need to check (the OS extension team probably) which folders must be mutable and then test the process, i.e. boot into a Garden Linux node, update it, see that everything (pods/containers) works again after reboot.
- The GardenLinux teams wants to provide a tool to boot into another OS, basically 2 params: OS version/URL, flag whether the mutable folders shall be purged (e.g. Kubernetes minor version update) or not/kept as-is (all other cases).
 
From here on upwards:
- Today, we calculate machine classes and operating system configs from the shoot worker pool configuration. If the machine class changes, we update the machine deployment which triggers the rolling update. If only the operating system config changes, the node controller in the Gardener resource manager controls, via labels it sets at the nodes, the gradual roll-out of the updated operating system configs that then the Gardener node agent executes. With in-place updates, we discussed to shift the latter responsibility to MCM and make it generally control the roll-out based on the given worker pool configuration (maxUnavailable and maxSurge).
- MCM will need to support different update strategies:
  - RollingUpdate:
    - Rolling: Changing the spec triggeres a rolling update of the nodes according to maxUnavailable and maxSurge (either >0)
    - OnDelete: Changing the spec doesn’t trigger anything, but new nodes get the new spec; old nodes can be directly deleted
    - OnLabel: Changing the spec doesn’t trigger anything, but new nodes get the new spec; old nodes can be rolled via a label
  - InPlaceUpdate:
    - Rolling: Changing the spec triggers an in-place update of the nodes according to maxUnavailable (>0) while maxSurge must be 0
    - OnLabel: Changing the spec doesn’t trigger anything, but nodes that are labelled will be in-place updated

  This way, we can leverage the node drain logic of MCM that we might have to rely upon when we update a Kubernetes minor version which requires, according to the spec (https://kubernetes.io/releases/version-skew-policy/#kubelet-1), to drain the pods from the node first. This may also be required for changes to kube-system or CA rotation, but let’s see. Maybe people would want to opt-out/take care themselves (e.g. in the case of CA rotation).
- The heavy lifting is then done in the Gardener node agent.
- We have not discussed yet, how bare metal nodes will be adopted into a cluster and where their description/configuration resides. The current worker pools are a “difficult fit” as bare metal nodes can be all different, have no machine or volume type (inherent property of the bare metal machine). Then again, with IronCore, it’s not exactly bare metal either as already for the first clusters the MetalAPI will be used, so maybe we don’y really have to treat the IronCore case as a high-touch (=manual) bare metal case after all and IronCore must only configure the right update strategy to switch off MCM’s rolling update implementation and activate the in-place update strategy.
 
Research/prototypes/first work packages:
- Garden Linux & OS Extension: Garden Linux OS update+reboot test (mutable folders)
- MCM: MCM update strategies
- Gardener Core: Changing GRM+GNA

**Comment by acumino** [comment]
## A General Overview of the Solution:

Both MCM (Machine Controller Manager) and GNA (Gardener Node Agent) will be used to perform in-place updates. MCM will provide an interface that prepares the machine/node for an update. This interface can be used by other components to determine if a node is ready for an update, allowing the tool to perform the update and then notify MCM that the node has been successfully updated. ***In the case of Gardener, this tool will be GNA.***

This design has been chosen to leverage all the functionalities provided by MCM (such as draining nodes, using `maxUnavailable` for selecting machines/nodes for updates, etc.). Additionally, MCM can remain a standalone component without any dependency on `Gardener`.

### Implementation Details:

#### **MCM (Machine Controller Manager)**:  
MCM will provide two strategies for performing updates: `InPlace` and `OnLabel`.

- **InPlace Strategy**: Machines will be selected based on `maxUnavailable` and will go through the following steps:
  - Mark the machine as unschedulable.
  - Drain the node.
  - Mark the machine as ready for an update using a set of labels/annotations.
  - Wait for an annotation/label indicating that the machine has been updated.
  - Once the update is detected, the node will be uncordoned.

- **OnLabel Strategy**: Machines/nodes will be selected for updates based on certain labels, which the user has control over. This strategy gives users the flexibility to specify which machines/nodes should be updated by applying predefined labels.

In the current implementation, when a `Kubernetes minor version` or `OS/Machine Image` is updated in the shoot (worker pool), the provider extension creates a new MCC (Machine Class), and the MCD (Machine Deployment) is updated to use this new MCC. MCM detects that the `Machine Deployment` now references a new `Machine Class`, creates a new MCS (Machine Set) for the MCD referencing the new MCC, and machines are rolled based on the rolling strategy (new machines are created and old ones are deleted).

With the `InPlace` strategy, instead of creating new machines and deleting the old ones, machines/VMs will be transferred from the old MCS to the new MCS, avoiding the need to recreate machines.

#### **GNA (Gardener Node Agent)**:  
GNA acts as the update tool. When the `OS` or `Kubernetes minor version` is updated for a shoot, GNA will first check for the MCM annotation/label indicating that the node is ready for the update. It will then proceed to update the respective dependencies on the node. If the update is successful, GNA will notify MCM that the update has been completed.

The shoot/worker pool will allow configuring a rolling strategy for the nodes. If the `InPlace` or `OnLabel` strategy is selected, then during `Kubernetes minor version` or `OS/Machine Image` updates, GNA will wait for MCM's "ready-to-update" annotation on the node. Once this annotation is present, GNA will perform the update and mark/label the node as updated.

### OS Upgrade:
Currently, only `gardenlinux` will be supported for in-place OS updates. Gardenlinux will provide an update tool called `gardenlinux-update`, which can be triggered(GNA in case of gardener) to perform the OS update on the node.

---

More details and other discussed approaches will be provided in a future GEP (Gardener Enhancement Proposal).

**Comment by majst01** [comment]
I still did not get the point of an InPlace Update if the node must be drained anyway. The impact for the pods running on this node is almost the same as if they where rescheduled on a new node which was newly created with a newer version of the kubelet and OS. The burden of implementing a InPlace Update strategie in GNA and the OS itself must not be undertaken.

**Comment by rfranzke** [comment]
Thanks for the preliminary overview. I guess it makes sense to also think about the extensibility aspect of GNA. As of today, OS handling is moved into dedicated extensions, i.e., `gardener/gardener` does not have any specific knowledge. Teaching GNA to run a `gardenlinux-update` command breaks/violates this. Do you have ideas how to keep the GNA code generic?

**Comment by acumino** [comment]
> I still did not get the point of an InPlace Update if the node must be drained anyway. The impact for the pods running on this node is almost the same as if they where rescheduled on a new node which was newly created with a newer version of the kubelet and OS.

This is needed for the use case where we can't lose the node, it can be unavailable for some time for maintenance but should not be deleted.
Draining is needed for multiple reasons, one reason is that OS will be rebooted for an upgrade and this will terminate all the processes running on that node abruptly, which is not the correct thing to do, therefore before upgrading OS, node needs to be drained.

**Comment by acumino** [comment]
> I guess it makes sense to also think about the extensibility aspect of GNA. As of today, OS handling is moved into dedicated extensions, i.e., `gardener/gardener` does not have any specific knowledge. Teaching GNA to run a `gardenlinux-update` command breaks/violates this. Do you have ideas how to keep the GNA code generic?

Yes, we have planned it that way. OSC will a provide generic way to call an upgrade tool, which will be utilized by the `GNA`. This will keep the GNA code independent of the OS.

**Comment by majst01** [comment]
> > I still did not get the point of an InPlace Update if the node must be drained anyway. The impact for the pods running on this node is almost the same as if they where rescheduled on a new node which was newly created with a newer version of the kubelet and OS.
> 
> This is needed for the use case where we can't lose the node, it can be unavailable for some time for maintenance but should not be deleted. Draining is needed for multiple reasons, one reason is that OS will be rebooted for an upgrade and this will terminate all the processes running on that node abruptly, which is not the correct thing to do, therefore before upgrading OS, node needs to be drained.

The only Situation i can imagine is excessive use of local storage, in all other cases it will be safer and faster to simply rotate the node.

**Comment by majst01** [comment]
> > I guess it makes sense to also think about the extensibility aspect of GNA. As of today, OS handling is moved into dedicated extensions, i.e., `gardener/gardener` does not have any specific knowledge. Teaching GNA to run a `gardenlinux-update` command breaks/violates this. Do you have ideas how to keep the GNA code generic?
> 
> Yes, we have planned it that way. OSC will a provide generic way to call an upgrade tool, which will be utilized by the `GNA`. This will keep the GNA code independent of the OS.

But what is the plan if on a specific OS no "generic update tools" is available / installed ?

**Comment by shafeeqes** [comment]
> The only Situation i can imagine is excessive use of local storage, in all other cases it will be safer and faster to simply rotate the node.

The reason for this is explained in the very first comment under "Why is this needed".

> But what is the plan if on a specific OS no "generic update tools" is available / installed ?

You cannot do In-place updates in that OS. As of now, only gardenlinux will support it.

**Comment by shafeeqes** [comment]
> But what is the plan if on a specific OS no "generic update tools" is available / installed ?

We cannot do in-place updates in that OS. For now, only gardenlinux will support it.

**Comment by majst01** [comment]
> > But what is the plan if on a specific OS no "generic update tools" is available / installed ?
> 
> We cannot do in-place updates in that OS. For now, only gardenlinux will support it. We can validate the Shoot not to configure `Inplace` strategy if the OS used doesn't support it.

TBH i dont like this approach.

**Comment by elankath** [comment]
We should also think and clarify the failure cases. What if the GNA fails ? How should we handle this ? The GNA should ideally add a `failed-update` annotation to the Nodes which failed. How should we handle timeouts - ie cases where the `ready-to-update` annotation/label never goes away ?

**Comment by acumino** [comment]
> 
> TBH i dont like this approach.

We have opened a GEP for the approach in https://github.com/gardener/gardener/pull/10828. Do take a look and provide feedback or alternatives.

**Comment by acumino** [comment]
OS booting time issue - https://github.com/gardenlinux/gardenlinux/issues/3261

**Comment by vlerenc** [comment]
@acumino Hi, is that feature now fully implemented? I see the Azure PR is also merged.

**Comment by acumino** [comment]
> [@acumino](https://github.com/acumino) Hi, is that feature now fully implemented? I see the Azure PR is also merged.

We are waiting for the Azure release to close the issue. The release was not possible due to an ongoing task in `provider-azure`(not related to in-place) that needs to be included in the next release of `provider-azure`.

**Comment by acumino** [comment]
All tasks are completed.
/close
