### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.31”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#10286]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.31 is getting released on August 13th: [CHANGELOG](Https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md), [Kubernetes v1.31: Elli](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/).
There is [this guide](https://github.com/gardener/gardener/blob/master/docs/development/new-kubernetes-version.md) for developers who want to work on adding support for a new Kubernetes version.

---

# Tasks
 
## Gardener

- [x] `gardener`: https://github.com/gardener/gardener/pull/10472
  - Release-independent tasks
    - Allow instantiating v1.31 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/features/featuregates.go
    - Update admission plugins in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/admissionplugins.go
    - Update API groups in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/apigroups/apigroups.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/controllers.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/component/shoot/system/system.go
    - Bump used Kubernetes version for local shoot and local e2e test
    - Bump `kubectl` version in https://github.com/gardener/gardener/blob/master/hack/tools.mk#L69
  - Release-dependent tasks
    - After https://github.com/gardener/gardener/pull/10290, it is no longer possible to set `systemReserved` in the `kubelet` settings in `Shoot`s for `1.31+` clusters. Consider this in the force-upgrade code in the maintenance controller, see https://github.com/gardener/gardener/pull/10290/commits/1a6670f03663f607cab40d353cce3b1bdaf8913b#diff-47afa92178db2297d386efad63f8004d2a42183070e05f3a5ec5514bc5bd3c50R227-R229
    - After https://github.com/gardener/gardener/pull/10253, it is no longer possible to set `.oidcConfig.clientAuthentication` in `Shoot`s for `1.31+` clusters. Consider this in the force-upgrade code in the maintenance controller.
    - https://github.com/kubernetes/kubernetes/pull/124767 removes the `k8s.io/legacy-cloud-provider` dependency. We will not be able to vendor `k8s.io/legacy-cloud-providers@v0.31.0` in our [gcp cloud-controller-manager fork](https://github.com/gardener/cloud-provider-gcp).
    - [Deprecation of `status.nodeInfo.kubeProxyVersion` field for Nodes](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#deprecation-of-status-nodeinfo-kubeproxyversion-field-for-nodes-kep-4004-https-github-com-kubernetes-enhancements-issues-4004): We have a single usage of the field in the e2e tests
    - Default kubelet and containerd cgroup driver to `systemd`. Ref https://github.com/gardener/gardener/issues/5325
  - Nice to know
    - Highlights of features graduating to Stable
      - [Kubernetes support for AppArmor is now GA.](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#apparmor-support-is-now-stable)
      - [Kube-proxy improved ingress connectivity reliability is stable in v1.31](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#improved-ingress-connectivity-reliability-for-kube-proxy)
      - [Persistent Volume last phase transition time feature moved to GA in v1.31.](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#improved-ingress-connectivity-reliability-for-kube-proxy)  
    - Highlights of features graduating to Beta
      - [The nftables backend moves to beta in v1.31](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#nftables-backend-for-kube-proxy)
      - [The Always Honor PersistentVolume Reclaim Policy feature has advanced to beta in Kubernetes v1.31](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#changes-to-reclaim-policy-for-persistentvolumes)
      - [Support for clusters with multiple Service CIDRs moves to beta in v1.31 (disabled by default).](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#multiple-service-cidrs)
      - [Traffic distribution for Services moves to beta in v1.31 and is enabled by default.](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#traffic-distribution-for-services)
      - [VolumeAttributesClass API is moving to beta in v1.31.](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#kubernetes-volumeattributesclass-modifyvolume)
    - New features in Alpha
      - [New DRA APIs for better accelerators and other hardware management](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#new-dra-apis-for-better-accelerators-and-other-hardware-management)
      - [Support for image volumes](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#support-for-image-volumes)
      - [Exposing device health information through Pod status](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#exposing-device-health-information-through-pod-status)
      - [Finer-grained authorization based on selectors](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#exposing-device-health-information-through-pod-status)
      - [Restrictions on anonymous API access](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#exposing-device-health-information-through-pod-status)
    - [Graduations, deprecations, and removals in 1.31](https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#graduations-deprecations-and-removals-in-1-31)
    - Others
      - Removed k8s.io/legacy-cloud-providers from staging. (https://github.com/kubernetes/kubernetes/pull/124767)
      - Added Coordinated Leader Election as Alpha under the CoordinatedLeaderElection feature gate. With the feature enabled, the control plane can use LeaseCandidate objects (coordination.k8s.io/v1alpha1 API group) to participate in a leader election and let the kube-apiserver select the best instance according to some strategy. (https://github.com/kubernetes/kubernetes/pull/124012)
      - CustomResourceDefinition objects created with non-empty caBundle fields which are invalid or do not contain any certificates will not appear in discovery or serve endpoints until a valid caBundle is provided. Updates to CustomResourceDefinition are no longer allowed to transition a valid caBundle field to an invalid caBundle field, because this breaks serving of the existing CustomResourceDefinition. (https://github.com/kubernetes/kubernetes/pull/124061)
      - Graduated MatchLabelKeys/MismatchLabelKeys feature in PodAffinity/PodAntiAffinity to Beta. (https://github.com/kubernetes/kubernetes/pull/123638)
      - Introduced a new boolean kubelet flag --fail-cgroupv1. (https://github.com/kubernetes/kubernetes/pull/126031)

## Cloud Controller Managers

- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.31` branch from it (update container images and revendor latest Kubernetes patch): The  k8s.io/legacy-cloud-providers module is removed starting K8s 1.31. See https://github.com/kubernetes/kubernetes/pull/124767
  - Maintain `release-v1.30` branch (update container images and revendor latest Kubernetes patch): [v1.30.5](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.30.5)
  - Maintain `release-v1.29` branch (update container images and revendor latest Kubernetes patch): [v1.29.9](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.29.9)
  - Maintain `release-v1.28` branch (update container images and revendor latest Kubernetes patch): [v1.28.14](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.28.14)

## Provider Extensions

- [x] `provider-local`:
  - Bump `kindest/node` version in `node/Dockerfile` ([example](https://github.com/gardener/machine-controller-manager-provider-local/pull/19)): https://github.com/gardener/gardener/pull/10688
- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/739
  - Revendor `gardener/gardener` with support for 1.31 client creation
  - Update `README.md` with support for 1.31
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/1055
  - Revendor `gardener/gardener` with support for 1.31 client creation
  - Update `README.md` with support for 1.31
  - Update `cloud-controller-manager` and `ecr-credential-provider` images
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/963
  - Revendor `gardener/gardener` with support for 1.31 client creation
  - Update `README.md` with support for 1.31
  - Update `cloud-controller-manager` and `cloud-node-manager` images
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/844
  - Revendor `gardener/gardener` with support for 1.31 client creation
  - Update `README.md` with support for 1.31
  - Update `cloud-controller-manager` images
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/856
  - Revendor `gardener/gardener` with support for 1.31 client creation.
  - Update `README.md` with support for 1.31
  - Update `cloud-controller-manager`, `csi-driver-cinder` and `csi-driver-manila` images
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/324
  - Revendor `gardener/gardener` with support for 1.31 client creation
  - Update `README.md` with support for 1.31

## Test Infra

- [x] [Ensure test-infra compatibility](https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/README.md#run-conformance-tests-against-new-k8s-versions) with conformance tests ([example](https://github.com/gardener/test-infra/commit/231f14fd430cbfc76be8ae4f893b7fa0ddd484c5)): https://github.com/gardener/test-infra/commit/0ce0b36d58fc996c6d5711bbbc3d698e3ff56e58

## Cluster Autoscaler

- [x] Update cluster-autoscaler for K8s 1.31: https://github.com/gardener/autoscaler/issues/320
  - Adaptation of `gardener/autoscaler`: https://github.com/gardener/autoscaler/pull/339
  - Integration into `gardener/gardener`: https://github.com/gardener/gardener/pull/11646

## Follow-up items

- [x] Add K8s 1.31 support for Gardener to [kubernetes/test-infra](https://github.com/kubernetes/test-infra/): https://github.com/kubernetes/test-infra/pull/33789
- [x] Add K8s conformance badges to Gardener and extensions: https://github.com/gardener/gardener/pull/10829
- [x] Update the [the conformance spreadsheet](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0&range=117:118) and reflect this update in our README.md: https://github.com/gardener/gardener/pull/10829
- [x] Update the Kubernetes versions in e2e tests: https://github.com/gardener/gardener/pull/10704
- [x] Update `kindest/node` to `v1.31`: https://github.com/gardener/gardener/pull/10723

**Comment by ialidzhikov** [comment]
/close
as all subtasks are completed now
