### ISSUE TITLE
Limit permissions of `gardener-node-agent` instances to required objects

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#10505]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
At the moment `gardener-node-agent` on every node share their service account (`gardener-node-agent`)  and so also the same [permissions](https://github.com/gardener/gardener/blob/master/pkg/component/extensions/operatingsystemconfig/original/components/nodeagent/rbac.go).
This means that `gardener-node-agents` have to many permissions, because they could update `Node`s and `Lease`s which belong to different GNAs and they can read `OperatingSystemConfig` secrets of all worker groups.
The permissions could be reduced way without the necessity to update the core functionality of GNA. 

🎯 _Goals_
- Each GNA has its own user
- Reduce permissions of GNA instances
  - GNA can update its own `Node` only
  - GNA has access to its own `Lease` only
  - GNA has access to the OSC secret of its own worker group only
- The feature should be switched on and off without the necessity to role the shoot nodes.   

**Implementation:**

**Usernames for GNA**
Each instance of gardener-node-agent is using the name of its `machine` as username. 
It cannot use the name of the `node`, because it is created by `kubelet` which is deployed by GNA.
It should not use the `hostname`, because we encountered cases where the hostname changed while GNA was running.
At the moment GNA does not know the name of its machine yet. That's why this feature needs an adapted `machine-controller-manager` and all provider specific implementations.

**`node-agent-authorizer` webhook**
For more granular permissions we cannot rely on the RBAC based authorization only, but could use a Webhook based approach similar to the the [SeedAuthorizer](https://github.com/gardener/gardener/blob/master/docs/deployment/gardenlet_api_access.md) we already implemented. The implementation of this `NodeAgentAuthorizer` could be simpler as there is no need for a dependency graph in this use case.
The webhook is implemented in `gardener-resource-manager` because it already serves [multiple webhooks](https://github.com/gardener/gardener/tree/master/pkg/resourcemanager/webhook) for shoots.

**Certificate based authentication** 
[Certificates and Certificate Signing Requests (CSR)](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) are used to authenticate each GNA individually at the shoot kube-apiserver. The same concept is already used [by gardenlet](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) to authenticate at garden-apiserver.

GNA creates CSRs which are automatically approved under these conditions.
- a machine with the name of the GNA user must exist
- when a bootstrap token is used: there must not be a node for this machine
- when a GNA certificate is used: the requesting user and the common name of the certificate must be equal, so GNA is only allowed to renew its on certificate.

There is already a [controller in GRM](https://github.com/gardener/gardener/tree/master/pkg/resourcemanager/controller/csrapprover) which approves CSRs for kubelet server certificates. This could be adapted for this use-case.

**Tasks:** 
-  [x] Add `machine-name` to user data and as a node label in [MCM](https://github.com/gardener/machine-controller-manager): https://github.com/gardener/machine-controller-manager/pull/919
- [x] Update provider specific MCMs:
  - [x] [`gardener/machine-controller-manager-alicloud`](https://github.com/gardener/machine-controller-manager-provider-alicloud): https://github.com/gardener/machine-controller-manager-provider-alicloud/pull/86
  - [x] [`gardener/machine-controller-manager-aws`](https://github.com/gardener/machine-controller-manager-provider-aws): https://github.com/gardener/machine-controller-manager-provider-aws/pull/175
  - [x] [`gardener/machine-controller-manager-azure`](https://github.com/gardener/machine-controller-manager-provider-azure): https://github.com/gardener/machine-controller-manager-provider-azure/pull/166
  - [x] [`gardener/machine-controller-manager-gcp`](https://github.com/gardener/machine-controller-manager-provider-gcp): https://github.com/gardener/machine-controller-manager-provider-gcp/pull/129
  - [x] [`gardener/machine-controller-manager-openstack`](https://github.com/gardener/machine-controller-manager-provider-openstack): https://github.com/gardener/machine-controller-manager-provider-openstack/pull/181
  - [x] [`ironcore-dev/machine-controller-manager-provider-ironcore`](https://github.com/ironcore-dev/machine-controller-manager-provider-ironcore): https://github.com/ironcore-dev/machine-controller-manager-provider-ironcore/pull/442
   - [x] [`ironcore-dev/machine-controller-manager-provider-metal`](https://github.com/ironcore-dev/machine-controller-manager-provider-metal): https://github.com/ironcore-dev/machine-controller-manager-provider-metal/pull/20
   - [x] [`metal-stack/machine-controller-manager-provider-metal`](https://github.com/metal-stack/machine-controller-manager-provider-metal): https://github.com/metal-stack/machine-controller-manager-provider-metal/pull/38
- [x] Introduce `node-agent-authorizer` webhook in `gardener-resource-mananger`: https://github.com/gardener/gardener/pull/10535 
  - [x] https://github.com/gardener/gardener/pull/10703 
- [x] Adapt `CSRApprover` of `gardener-resource-manager` to approve CSRs created by `gardener-node-agent`: https://github.com/gardener/gardener/pull/10549
- [x] Implement webhook based authorization in `gardener-node-agent`: https://github.com/gardener/gardener/pull/10781
- [x] Promote `NodeAgentAuthorizer` feature gate to beta: https://github.com/gardener/gardener/pull/11757
- [x] Graduate `NodeAgentAuthorizer` feature gate to GA: https://github.com/gardener/gardener/pull/12405
- [x] Remove access token based authorization and drop `NodeAgentAuthorizer` feature gate after `gardener/gardener@v1.123` was released: https://github.com/gardener/gardener/pull/12576
