### ISSUE TITLE
☂️ [GEP-39] Live Control Plane Migration(CPM) or CPM with zero downtime

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#10686]
Umbrella issue for implementing [GEP-39: Live Control Plane Migration](https://github.com/gardener/enhancements/blob/main/geps/0039-live-control-plane-migration/README.md).

**How to categorize this issue?**
<!--
Please select area, kind, and priority for this issue. This helps the community categorizing it.
Replace below TODOs or exchange the existing identifiers with those that fit best in your opinion.
If multiple identifiers make sense you can also state the commands multiple times, e.g.
  /area control-plane
  /area auto-scaling
  ...

"/area" identifiers:     audit-logging|auto-scaling|backup|certification|control-plane-migration|control-plane|cost|delivery|dev-productivity|disaster-recovery|documentation|high-availability|logging|metering|monitoring|networking|open-source|ops-productivity|os|performance|quality|robustness|scalability|security|storage|testing|usability|user-management
"/kind" identifiers:     api-change|bug|cleanup|discussion|enhancement|epic|impediment|poc|post-mortem|question|regression|task|technical-debt|test
-->
/area open-source
/kind enhancement

**What would you like to be added**:
Currently, shoot control plane migrations cause temporary downtime for the shoot cluster because ETCD needs to be backed up and deleted before being restored in the new seed cluster. During this time, the API server, along with all other control plane components, is also taken down. Although the workload within the shoot cluster continues running, it cannot be reconciled, scaled, or updated, leading to downtime since the control plane is unavailable to users.

We would like to support live Control Plane Migration (CPM), allowing migrations to happen without causing downtime for the API server, thereby preventing downtime for the users. This ensures that the shoot cluster remains fully operational, with continuous availability of control-plane for the users.

We(@acumino, @shafeeqes and @ary1992) conducted a POC on this, and it is feasible to implement. More details can be found [here](https://github.com/gardener/gardener/issues/10686#issuecomment-2425831313).


**Why is this needed**:
Prevent downtime during control plane migration, ✨ enabling support for more use cases and scenarios, such as 'seed draining/shoot evictions' or streamlined seed cluster deletions.

**Tasks:**
- [x] Get a go-ahead from the TSC - https://github.com/gardener/documentation/pull/796                                                                                                                                                                                                                                                                                                          
- [ ]  etcd-backup-restore & etcd-druid                                                                                                                                                                                                                                           
    - [ ] [`etcd-backup-restore#896`](https://github.com/gardener/etcd-backup-restore/issues/896): Decouple etcd member name from pod name                                                                                                                                     
    - [ ] [☂️  etcd-druid#1237: Support for LiveCPM](https://github.com/gardener/etcd-druid/issues/1237)                                   
                                                                                                                                                                                                                                                                               
- [ ] Gardener Core: Shoot API & Gardenlet Flow                                                                                                                                                                                                                                  
    - [ ] Shoot API: `status.liveMigration.conditions`, `LiveMigrate` operation, and `LiveCPM` feature gate: https://github.com/gardener/gardener/pull/14719                                                                                                                                                                    
    - [ ] Prerequisite validation                                                                                                                                                                                                                                              
      - [ ] Admission-side: scheduler ConfigMap distance check + hibernation rejection                                                                                                                                                                                         
      - [ ] Gardenlet-side: version parity watch/block + network connectivity pre-check                                                                                                                                                                                        
    - [ ] Expose etcd peer endpoints via Istio (source + destination seeds)                                                                                                                                                                                                    
    - [ ] Live Migration gardenlet flow and temporary VPN tunnel                                                                                                                                                                                                               
    - [ ] Live Migration e2e tests                                                                                                                                                                                                                                             
    - [ ] Live Migration TM (Test Machinery) tests                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
  - [ ] Failure & Recovery Paths                                                                                                                                                                                                                                                   
    - [ ] Abort flow: `abort-live-migration` annotation handling                                                                                                                                                                                                               
    - [ ] Force-shrink etcd: `force-shrink-etcd` annotation handling                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                               
  - [ ] Documentation                                                                                                                                                                                                                                                              
    - [ ] Troubleshooting and debugging guide for Live CPM                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                               
  - [ ] Extension Adaptations                                                                                                                                                                                                                                                      
    - [ ] Adapt extensions to support Live CPM where needed

**Comment by acumino** [comment]
# Live CPM POC/Status

## Main problems
- ETCD migration
- DNS switching
- VPN migration

### ETCD Migration -
Approaches evaluated - 
- **ETCD mirror maker** - https://hackmd.io/@acumino/rkVBtwDTT

- **etcd-gateway**
    - Start 3 etcd pods in dest cluster which works as proxy(route traffic to source etcd counterpart pod/member).
    - One by one make dest etcd pods as actual member and switch source etcd counterpart pod/member to proxy.
    - Once all pods/member has been migrated stop source etcd.
    - Momentarily one etcd member would not be available.

- **6 member etcd cluster** - https://excalidraw.com/#json=m3Rfb9ks95PR2rrlw7uJG,FzCYXju78K26L22c_Bo81A

### DNS switching -
- Since there is only one underlying etcd cluster, we don't have any issue with either of kube-apiservers serving the requests.

### VPN migration -
VPN should be available during whole migration for the availability of webhooks in Shoot.
- https://excalidraw.com/#json=QAA369tj-S9NJdQHa0jOT,46RN2EILnUYLhLRQ_QhoSw

## Actual Flow
As of now two gardenlets works parallely on one shoot based on set of annotation such as- 
- `shoot.gardener.cloud/source-second-stage-ready`
- `shoot.gardener.cloud/target-second-stage-ready`

Following diagram explains the flow in more detail - 
- https://excalidraw.com/#json=g1uxKRPhSQSqNjtLXbpJU,A7nsF0ZBLgq-W9zM0JOcPQ

## Things that will/can change during implementation
- Instead of loadbalancer service for each etcd pods, we can use Istio(ServiceEntries and other resources).

## Points for Discussion
- ETCD **main** name change
- Should we redirect source istio traffic to dest istio before DNS migration(and if there is way)
- Disabling reverse lookup by etcd by using `--experimental-peer-skip-client-san-verification` flag.
- How does the shoot status looks like during migration?!


## Manual Work (Not implemented)
- Removal of member in etcd
- Adapting `seed-authorizer` and `seed-restriction`

## Changes required in repos -
- **etcd-wrapper** [[Changes](https://github.com/shafeeqes/etcd-wrapper/tree/enh/cpm)]
    - disabling reverse lookup
- **etcd-back-restore** [[Changes](https://github.com/shafeeqes/etcd-backup-restore/tree/enh/cpm)]
    - allow adding multiple url for peer and clients
    - allow to work with given urls instead of parsing a string
- **etcd-druid** [[Changes](https://github.com/shafeeqes/etcd-druid/tree/enh/cpm)]
    - adapt etcd object to
        - allow peer, initial and client urls
        - allow service endpoint
        - allow disabling reverse lookup
- **ext-authz-server** [[Changes](https://github.com/acumino/ext-authz-server/tree/allow-temp)]
    - allow temp vpn-seed-server services
- **gardener-extension-provider-aws** [[Changes](https://github.com/shafeeqes/gardener-extension-provider-aws/tree/test/cpm)]
    - shallow deletion of DNS records
- **gardener** [[Changes](https://github.com/acumino/gardener/tree/cpm-2)]
    - adapting flow

## Limitations
- We are seeing close to **[5-15] second** unavalibility of KAPI during DNS migration.
- Latency (distant located regions)
    - ETCD
        - New ETCD member is able to learn over a very long period of time (Not consistent)
        - ETCD throws error - 
            - Not in sync with leader
                - `2024-05-07 09:23:59.320872 W | etcdserver: waiting for ReadIndex response took too long, retrying (sent-request-id: 5398284687236073758, retry-timeout: 500ms)`
                - `2024-05-07 09:23:59.748703 W | etcdserver: ignored out-of-date read index response; local node read indexes queueing up and waiting to be in sync with leader (request ID want 5398284687236073758, got 5398284687236073757)`
            - Timeouts for range requests
                - `2024-05-07 10:11:43.229551 W | etcdserver: read-only range request "key:\"foo\" " with result "range_response_count:0 size:5" took too long (137.889387ms) to execute`
    - KAPI (After ETCD becomes 6 member cluster)
        - Already runnning replicas are fine
        - If pod restarts KAPI fails to get ready
- Old logs and metrics will be lost


## Data
- ETCD
    - ![image](https://hackmd.io/_uploads/rJIt2WawA.png)

    - ![image](https://hackmd.io/_uploads/H178hWTvC.png)

    - ![Screenshot 2024-07-11 at 1.06.10 PM](https://hackmd.io/_uploads/BydAjZTv0.png)
- KAPI downtime - 
    - kube-apiserver is healthy again after **11 seconds** of downtime. (eu-west-1 and eu-west-1)
    - kube-apiserver is healthy again after **6 seconds** of downtime. (eu-west-1 and eu-west-1)
    - kube-apiserver is healthy again after **4 seconds** of downtime. (eu-west-1 and eu-west-1)
    - kube-apiserver is healthy again after **1 seconds** of downtime. (eu-west-1 and eu-north-1)
    - kube-apiserver is healthy again after **0 seconds** of downtime. (eu-west-1 and eu-west-1)
    - kube-apiserver is healthy again after **13 seconds** of downtime. (eu-west-1 and eu-north-1)

**Comment by acumino** [comment]
KAPI downtime was eliminated (achieving zero downtime) by introducing a delay in deleting the source KAPI before and after migrating the DNS record.

**Comment by adenitiu** [comment]
@acumino would you be able to provide an approximate timeline by when this would be available, productive ?

**Comment by acumino** [comment]
> @acumino would you be able to provide an approximate timeline by when this would be available, productive ?

@adenitiu The work on this is paused currently to [prioritize InPlace](https://github.com/gardener/gardener/issues/10219). The work will probably start from Q2-2025. Don't have an exact timeline.

**Comment by acumino** [comment]
The `-experimental-peer-skip-client-san-verification` flag has been promoted to a stable `-peer-skip-client-san-verification`, supported flag in etcd version `v3.6`: https://github.com/etcd-io/etcd/pull/19362.
