### ISSUE TITLE
☂️ Support for Immutable Backup Buckets via ProviderConfig in Gardener Provider Extensions

### ISSUE THREAD

**Issue by seshachalam-yv** [gardener/gardener#10866]
**How to categorize this issue?**

/area backup
/area security
/kind enhancement

---

**What would you like to be added**:

Implement support for immutable backup buckets in the Gardener provider extensions for **AWS**, **GCP**, and **Azure**. The provider extensions should be capable of creating or updating backup buckets with immutability settings based on configurations specified in the seed's backup configuration under the `providerConfig` section. Additionally, introduce an admission validation webhook to enforce immutability settings and prevent them from being disabled or reduced once set.

**Why is this needed**:

Immutability of backup data is critical for security and compliance purposes. Enforcing immutability ensures that backup data cannot be altered or deleted before a specified retention period, protecting against accidental deletions or malicious actions. By adding support for immutable backup buckets, we significantly enhance the robustness and reliability of the backup and restore mechanisms in Gardener-managed clusters.

**Implementation Details**:

#### Gardener Seed Backup Configuration

Introduce immutability settings in the seed's backup configuration under the `providerConfig` section:

```yaml
spec:
  backup:
    providerConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: BackupBucketConfig
      immutability:
        retentionType: "bucket"
        retentionPeriod: 96h
        locked: false|true
```

This configuration allows Gardener to specify immutability policies for backup buckets, such as the type of retention policy (`retentionType`) and the retention period (`retentionPeriod`).

The `BackupBucket` resource will be created during the creation of the `Seed`. These immutability settings will be propagated to `backupbucket.spec.providerConfig` as mentioned [here](https://github.com/gardener/gardener/blob/master/docs/concepts/etcd.md#backup), and the provider extension will utilize them to create or update the bucket accordingly.

#### Gardener Extension Providers

The Gardener extension providers for **AWS**, **GCP**, and **Azure** should update the backup bucket handling to consider the `immutableSettings` from `backupbucket.spec.providerConfig`:

- **If the bucket does not exist**: Create the bucket with the specified immutability settings.
- **If the bucket exists without immutability settings**: Update the bucket to include the specified immutability settings.
- **If the bucket has immutability settings with a shorter retention period**: Adjust the retention period to match the new settings.

#### Admission Validation Webhook

Implement a new admission webhook to validate changes to the immutability settings in the seed's backup configuration:

- Once immutability settings are enabled, **they cannot be disabled**.
- The retention period **cannot be reduced** once set.

This ensures that the immutability policy is consistently enforced and cannot be circumvented after being configured.

**Tasks**:
- [x] Modify Gardener extension providers to handle immutability settings and implement the admission validation webhook.
  - [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/906: released with [v1.42.0](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.42.0)
    - [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/1002: released with [v1.43.0](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.43.0)
  - [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1261: released with [v1.62.0](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.62.0)
  - [x] https://github.com/gardener/gardener-extension-provider-azure/pull/1098: released with [v1.52.0](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.52.0)
- [x] Update documentation to reflect the changes and new configuration options: https://github.com/gardener/gardener/pull/12175

**Comment by seshachalam-yv** [comment]
cc: @kon-angelo

**Comment by rfranzke** [comment]
Thanks for the summary!
 
Suggestion: Rename `immutableSettings` to `immutability`

> Implement a new admission webhook to validate changes to the immutability settings in the seed's backup configuration:

What does that mean? Provider extensions already have an admission component for serving such webhooks.

**Comment by seshachalam-yv** [comment]
> What does that mean? Provider extensions already have an admission component for serving such webhooks.

Regarding the new admission webhook, it is intended to specifically validate changes to the immutability settings in the Seed's backup configuration. While it's true that provider extensions already have admission components like the [shoot validator](https://github.com/gardener/gardener-extension-provider-gcp/blob/master/pkg/admission/validator/shoot.go#L45-L64), we want to add an additional seed validator to ensure the immutability settings are correctly enforced.

**Summary of the Validation Logic**:

The seed validator performs the following checks:

- **On Creation**:
  - If immutable settings are provided in the `providerConfig`, the validator:
    - Checks that the `retentionType` is set to `"bucket"`.
    - Ensures the `retentionPeriod` is a valid duration and greater than zero.
    - Validates that the immutable settings are correctly specified.

- **On Update**:
  - **Prevent Disabling Immutability**:
    - If the immutable settings were previously set and are now removed, the validator rejects the change.
  - **Prevent Reducing Retention Period**:
    - If the `retentionPeriod` in the new settings is less than the old one, the validator rejects the update.
  - **Prevent Changing Retention Type**:
    - If the `retentionType` is modified from its previous value, the validator rejects the change.
  - **Validate Newly Added Immutable Settings**:
    - If immutable settings are newly added, the validator performs the same checks as on creation to ensure they are valid.

This validation ensures that once immutability settings are enabled:

- They cannot be disabled.
- The retention period cannot be reduced.
- The retention type cannot be changed.
