### ISSUE TITLE
Umbrella issue for go modules

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1096]
[golang/dep](https://github.com/golang/dep) is no longer the official tool for dependency management in the community. Go 1.11 adds preliminary support for a new concept called "modules", an alternative to GOPATH with integrated support for versioning and package distribution. Using modules, developers are no longer confined to working inside GOPATH, version dependency information is explicit yet lightweight, and builds are more reliable and reproducible.
Starting in Go 1.13, module mode will be the default for all development.

Below is the TODO list of project in the gardener org. The projects transitioned to go modules are the marked ones:
- [x] [gardener/gardener](https://github.com/gardener/gardener) (ref gardener/gardener#1185)
- [x] [gardener/gardenctl](https://github.com/gardener/gardenctl) (ref gardener/gardenctl#78)
- [x] [gardener/machine-controller-manager](https://github.com/gardener/machine-controller-manager) (ref gardener/machine-controller-manager#280)
- [x] [gardener/etcd-backup-restore](https://github.com/gardener/etcd-backup-restore) (ref gardener/etcd-backup-restore#176)
- [x] [gardener/gardener-extensions](https://github.com/gardener/gardener-extensions) (ref gardener/gardener-extensions#249)
- [x] [gardener/external-dns-management](https://github.com/gardener/external-dns-management)
... and others

P.S I didn't want to duplicate the same issue across the project, so opening a "umbrella" one. Please feel free to comment if you have any concerns or objections.

---

[Go modules wiki in golang/go](https://github.com/golang/go/wiki/Modules)
[Introduction to Go modules by Jordan Liggitt](https://www.youtube.com/watch?v=OrMA16ASz2U)

**Comment by ialidzhikov** [comment]
From [Go modules wiki in golang/go](https://github.com/golang/go/wiki/Modules):
> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required.

**Comment by rfranzke** [comment]
Any update?
