### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.32”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#11020]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.32 is getting released on December 11th: [CHANGELOG](Https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.32.md).
There is [this guide](https://github.com/gardener/gardener/blob/master/docs/development/new-kubernetes-version.md) for developers who want to work on adding support for a new Kubernetes version.

---

# Tasks
 
## Gardener

- [x] `gardener`: https://github.com/gardener/gardener/pull/11197
  - Release-independent tasks
    - Allow instantiating v1.32 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/features/featuregates.go
    - Update admission plugins in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/admissionplugins.go
    - Update API groups in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/apigroups/apigroups.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/controllers.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/component/shoot/system/system.go
    - Bump used Kubernetes version for local shoot and local e2e test
    - Bump `kubectl` version in https://github.com/gardener/gardener/blob/master/hack/tools.mk#L69
  - Release-dependent tasks
    - With https://github.com/gardener/gardener/pull/10858, the `.spec.kubernetes.clusterAutoscaler.ignoreTaints` field is deprecated and no longer allowed for `1.32+` shoot clusters. The [force-upgrade logic](https://github.com/gardener/gardener/blob/6faaaf42de959d9e53bac81058f320ce59997944/pkg/controllermanager/controller/shoot/maintenance/reconciler.go#L148-L290) in the maintenance controller needs to be adapted accordingly.
    -  With https://github.com/gardener/gardener/pull/10666, `OpenIDConnectPreset`s don't work for `1.32+` shoot clusters. Consider to adjust [admission controller](https://github.com/gardener/gardener/tree/master/plugin/pkg/shoot/oidc/openidconnectpreset) to exclude such shoots.
  - Nice to know
    - _n.a._
## Cloud Controller Managers

- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.32` branch from it (update container images and revendor latest Kubernetes patch): Not done anymore since `v1.31`.
  - Maintain `release-v1.31` branch (update container images and revendor latest Kubernetes patch): Not done anymore since `v1.31`.
  - Maintain `release-v1.30` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/53
  - Maintain `release-v1.29` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/52

## Provider Extensions

- [x] `provider-local`:
  - Bump `kindest/node` version in `node/Dockerfile`: 
- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/762 (released with `v1.59.0`)
  - Revendor `gardener/gardener` with support for 1.32 client creation
  - Update `README.md` with support for 1.32
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/1206 (released with `v1.61.0`)
  - Revendor `gardener/gardener` with support for 1.32 client creation
  - Update `README.md` with support for 1.32
  - Update `cloud-controller-manager` and `ecr-credential-provider` images
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/1076 (released with `v1.51.0`)
  - Revendor `gardener/gardener` with support for 1.32 client creation
  - Update `README.md` with support for 1.32
  - Update `cloud-controller-manager` and `cloud-node-manager` images
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/957 (released with `v1.43.0`)
  - Revendor `gardener/gardener` with support for 1.32 client creation
  - Update `README.md` with support for 1.32
  - Update `cloud-controller-manager` images
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/969 (release expected with `v1.47.0`)
  - Revendor `gardener/gardener` with support for 1.32 client creation.
  - Update `README.md` with support for 1.32
  - Update `cloud-controller-manager`, `csi-driver-cinder` and `csi-driver-manila` images

## ~Test Infra~

- [x] ~[Ensure test-infra compatibility](https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/README.md#run-conformance-tests-against-new-k8s-versions) with conformance tests ([example](https://github.com/gardener/test-infra/commit/231f14fd430cbfc76be8ae4f893b7fa0ddd484c5)):~ 

> [!NOTE]  
> This step is no longer required. `test-infra` now has built-in support for new Kubernetes versions. (cc @hendrikKahl)

## Cluster Autoscaler

- [x] Update cluster-autoscaler for K8s 1.32: https://github.com/gardener/autoscaler/issues/346
  - Adaptation of `gardener/autoscaler`: https://github.com/gardener/autoscaler/pull/348
  - Integration into `gardener/gardener`: https://github.com/gardener/gardener/pull/11903

## Follow-up items

- [x] Add K8s 1.32 support for Gardener to [kubernetes/test-infra](https://github.com/kubernetes/test-infra/) ([example](https://github.com/kubernetes/test-infra/pull/33789/commits/d741b5ff2d6f3de147160de867453357df94e2af)): https://github.com/kubernetes/test-infra/pull/34629
- [x] Add K8s conformance badges to Gardener and extensions: 
  - [x] `g/g`: https://github.com/gardener/gardener/pull/11781 
  - [x] `gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/1024
  - [x] `aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/1267
  - [x] `azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/1131
  - [x] `openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/1014 
  - [x] `alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/774
- [x] Update the [the conformance spreadsheet](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0&range=109:110) and reflect this update in our README.md: https://github.com/gardener/gardener/pull/11912
- [x] Update the Kubernetes versions in e2e tests: https://github.com/gardener/gardener/pull/11510

**Comment by LucaBernstein** [comment]
All tasks have successfully been completed 🥳 .
/close
