### ISSUE TITLE
Increase Monitoring retention

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener#1356]
**What would you like to be added**:
Increase the retention of the Shoot cluster Prometheus from [180h](https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml#L84) (7.5d) to 30d.
Probably we need also to increase the disk size which is currently fixed [20gb](https://github.com/gardener/gardener/blob/master/charts/seed-monitoring/charts/core/values.yaml#L3).

I checked the Prometheus db disk size of a cluster with ~30 nodes. Currently it is using only 20% of the available storage capacity.
```sh
$ df -h
Filesystem                Size      Used Available Use% Mounted on
...
/dev/sdc                 19.6G      3.8G     14.8G  20% /var/prometheus/data
...
```

**Todos**
- [ ] Increase Prometheus metrics retention to 30d
- [ ] Calculate proper Prometheus disk size (keep in mind we need also free disk space for the WAL)
- [ ] Check how to resize existing db disks, if we need to change the disk size
- [ ] Adapt all Grafana dashboards to allow to select data over the last 30d

**Why is this needed**:
To analyse long running Gardener performance and scale tests we need to keep the metrics for a longer period. Also for Shoots which run prod workloads it would be good to keep the data for a longer period.

We can also discuss to make the disk size configurable, if we want to provide options to save money, because not all clusters will really need this increased retention.

cc @amshuman-kr @wyb1 @vlerenc

**Comment by wyb1** [comment]
I suggest we whitelist the metric `prometheus_tsdb_storage_blocks_bytes` and collect it in the `aggregate-prometheus` as well. Then we can see on average how much storage all prometheus instances need. Obviously this does not account for the wal so we should leave some buffer. In addition to that we can whitelist `prometheus_tsdb_lowest_timestamp` to figure out how "old" the data is.
In the mean time we can set `--storage.tsdb.retention.size=15GB` and `--storage.tsdb.retention.time=30d`.
