### ISSUE TITLE
Support new API resources in core.gardener.cloud/v1alpha1 group

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1376]
Part of #308.

As we have proposed in [GEP-1](https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md) and [GEP-4](https://github.com/gardener/gardener/blob/master/docs/proposals/04-new-core-gardener-cloud-apis.md) we want to new API resources in the `core.gardener.cloud/v1alpha1` group.

# Definition of Done

- **Backwards-compatible resource migrations (+ example manifest in `example/` directory)**
  - [x] New `core.gardener.cloud/v1alpha1.Seed` resource [#1308, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.SecretBinding` resource [#1377, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.Quota` resource [#1377, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.Project` resource [#1382, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.CloudProfile` resource [#1403, ✅]
  - [x] New `core.gardener.cloud/v1alpha1.Shoot` resource [#1430, ✅]

- **Code adaptations**
  - [x] The admission plugins inside `gardener-apiserver` have been adapted to work with potential changes in the internal versions of the resources. [*implicitly done by the above PRs*, ✅]
  - [x] The `gardener-controller-manager` has been adapted to work with `core.gardener.cloud/v1alpha1` [#1453, ✅]
  - [x] The `gardener-scheduler` has been adapted to work with `core.gardener.cloud/v1alpha1` [#1435, ✅].
  - [x] The extensions need to work with `core.gardener.cloud/v1alpha1` [gardener/gardener-extensions#319, ✅].
  - [ ] The integration tests and test definitions have been adapted to work with `core.gardener.cloud/v1alpha1`.

**Comment by rfranzke** [comment]
@danielfoehrKn @schrodit @dguendisch volunteered to take over the adaptation of the integration tests once #1430 is merged.
