### ISSUE TITLE
Shoot Cluster Control Plane Auto-Scaling

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#16]
# Story
* As provider I want my shoot cluster control planes to scale automatically (within certain limits), so that my shoot clusters remain operational and respond fast.

# Motivation
Response time behaviour. Avoiding issues like #79. Generally being able to run larger and very large clusters safely (also important for our own shoot'ed seed clusters).

# Acceptance Criteria
- [x] XS (2 nodes), S (10 nodes), M (50 nodes), L (100 nodes) and XL clusters (250 nodes) with actual workload run safely without downtime for a week (hopefully longer, but that's the KPI and then we will free the resources).
- [x] Control plane shows good metrics-based utilisation (no large over-provisioning)
- [x]  #Minimal control plane unavailability (that is actually the greatest problem/threat, that we, when scaling, cause downtimes, most critically on API server and ETCD)

# Implementation Proposal
- [x] Use metrics-based horizontal pod autoscaling (HPA) for all shoot cluster control plane components that can be scaled horizontally like the API server (also brings HA as a side factor).
- [x] Use metrics-based vertical pod autoscaling (VPA) for all shoot cluster control plane components that cannot be scaled horizontally like the scheduler, controller manager and most importantly ETCD.

# Definition of Done
- [x] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [x] Unit tests are provided: Have you written automated unit tests?
- [x] Integration tests are provided: Have you written automated integration tests?
- [x] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [x] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [x] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?

**Comment by vlerenc** [comment]
FYI: [Autoscale your Kubernetes Workload with Prometheus - Frederic Branczyk, CoreOS](https://www.youtube.com/watch?v=VQFoc0ukCvI)
FYI: [Building Large Kubernetes Clusters](https://kubernetes.io/docs/admin/cluster-large/)

**Comment by vlerenc** [comment]
While HPA seems safe to use for horizontal pod autoscaling, VPA gives a very poor impression (NPEs) and the v1.11 release notes even hinted at larger problems and that the VPA will be revamped completely (https://kubernetes.io/docs/imported/release/notes for v1.11, search for VPA).

Therefore, ticket is now icebox'ed. There shall be a new version with v1.12, but I wouldn't hold my breath, so let's consider #255 for the time being.

**Comment by vlerenc** [comment]
FYI: The following podcast https://kubernetespodcast.com/episode/009-sre had some interesting information in it like:
- GKE etcd is split into main+events like ours (general community consensus anyways)
- GKE regular clusters really only have one master with one etcd (like ours, we also ditched leader election since we run etcd as pod in another Kubernetes cluster)
- Only regional GKE clusters have 3 masters/etcds
- etcd leader election (only required for these regional clusters) is troublesome, etcd in general is troublesome (well, we know... everybody knows)
- Key indicator of etcd is healthz endpoint also for Google
- One main reason for failure is disk i/o pressure that causes the API server to fail first and then the entire cluster

**Comment by vlerenc** [comment]
FYI: The following podcast https://kubernetespodcast.com/episode/009-sre had some interesting information in it like:
- GKE etcd is split into main+events like ours (general community consensus anyways)
- GKE regular clusters really only have one master with one etcd (like ours, we also ditched leader election since we run etcd as pod in another Kubernetes cluster)
- Only regional GKE clusters have 3 masters/etcds
- etcd leader election (only required for these regional clusters) is troublesome, etcd in general is troublesome (well, we know... everybody knows)
- Key indicator of etcd is healthz endpoint also for Google
- One main reason for failure is disk i/o pressure that causes the API server to fail first and then the entire cluster

**Comment by rfranzke** [comment]
Done with #1421
