### ISSUE TITLE
Shoot Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#1631]
This issue describes the necessary tasks for an initial implementation of the proposal for [Control Plane Migration](https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md).

The goal is to enable control plane migration between two working seeds.

The following things have to be done:
  - [x] ShootState resource added to gardener API Server #1634
  - [x] ShootState synchronization controller added to gardenlet #1731
  - [x] Extension Controllers extended to read and write state to their Custom Resource's 
`status.state` field gardener/gardener-extensions#476, gardener/gardener-extensions#528
  - [x] Extension Controllers support `gardener.cloud/operation=restore` to restore state from `status.state` and `gardener.cloud/operaton=migrate` to clean up resources
    - [x] Add Restore function to actuator interface in gardener-extensions 
    - [x] Implement Restore/Migrate function in extension controllers
      - [x] Infrastructure
      - [x] Worker
      - [x] Backupentry
      - [x] Network
      - [x] Controlplane
      - [x] OperatingSystemConfig
      - [x] Certificate extension controller
      - [x] DNS Controller 
      - [x] ContainerRuntime [#10](https://github.com/gardener/gardener-extension-runtime-gvisor/issues/10)
  - [x] Persist ETCD encryption data in ShootState 
  - [x] Extend ShootState and ShootState Sync Controller to be able to store secret data required by extension resources #2327 #2321 
  - [x] Add DNSOwners for DNSEntries during reconciliation and migrate/restore them during control plane migration
  - [x] Persist data for secrets generated by gardener in the ShootState
  - [x] Shoot reconciliation and deletion flows extended to support migration
  - [x] Enable modification of `Shoot.spec.seedName` field to trigger migration
  - [x] Integration tests
  - [x] Document what extensions controller writers need to do in order to support control plane migration
  - [x] Add a check if the __Destination Seed__'s provider is the same as the __Source Seed__
  - [x] Remove GardenerID and GardenerName checks (via Seed.Status.Gardener) when checking if the __Destination Seed__ is healthy as those values are defined for each gardenlet and will most likely be different. The version check should be kept though.
  - [x] Adapt worker configuration for the `Shooted Seed` which is created for CP Migration integration tests. The current configuration has too little workers and not all pods on the seed can be started.
  - [x] Improve updates of states of extension resources to the ShootState.
  - [x] Change `Shoot.Spec.Status.SeedName` to be equal to `Shoot.Spec.SeedName` as soon as reconciliation starts, instead of having to wait for reconciliation/restoration to finish successfully first.

### Additional issues identified during e2e tests
- [x] Investigate if manual reconciliation after shoot is stuck in "prepare for migration" phase triggers a reconciliation in the __Destination Seed__ therefore duplicating resources. - Cannot be reproduced.
~~- [ ] The extension healthcheck will report that an extension is "not yet picked up by a controller" if it is annotated with `Restore` or `Migrate` operation as the healthcheck expects there to be no operation annotation if an extension CR is currently reconciled by a controller.~~
- [x] backupentries of shoots which are not currently being migrated are annotated with `gardener.cloud/operation: migrate`
- [x] Deleting the `controlplane` CR deletes `cloud-provider-config` cm which prevents scaling of the control-plane deployments (kube-apiserver, kube-controller-manager, ...). This issue can occur if migration is stopped after the deployments are scaled to 0 and the flow has to be restarted.
- [x] If the `Worker` state in the `ShootState` is nil and consequently the `Worker` resource does not have its state field set in the destination `Seed` a nil pointer exception can happen during restoration
- [x] If there is only one `Shoot` in the seed, the extension controllers will get deleted at some time. Generally this shouldn't be a problem as extension controllers should only get deleted dynamically only if they are no longer necessary, however there are still leftover `dnsprovider`s and the corresponding `secrets` which still have a finalizer `dns.gardener.cloud/aws-route53`. This prevents the deletion of the `Shoot`'s namespace
- [x] After migration operation completes and the `Shoot`'s lastOperation is set to Restore, the restore operation is not automatically triggered. This happens because the generation is not increased on `shoot.Status` updates.
- [x] During restoration the `Worker` state does not get copied from the `ShootState` to the `Worker` resource.
- [x] The `extension-worker-mcm-shoot` `managedresource` was not deleted properly during migration. It should get removed during migration of the worker, but most likely it was deleted in the step which removes all managed resources, then redeployed by the worker controller. Perhaps we should first call the steps which migrate the extensions, then delete managed resources and after that delete the kube-apiserver.
- [x] Remove finalizers on Terraform Resources during migrate phase
- [x] Remove finalizers on MCM related secrets during migrate phase

**Comment by swilen-iwanow** [comment]
@vpnachev Can you add additional task for cleanup controller

**Comment by vpnachev** [comment]
Done

**Comment by vpnachev** [comment]
I am reopening this issue, there are more tasks to be done.

**Comment by swilen-iwanow** [comment]
During worker restoration provider extension crashes if worker has no state
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1271 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d6a4c0, 0x3398bb0)
	/go/src/github.com/gardener/gardener-extension-provider-gcp/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/gardener/gardener-extension-provider-gcp/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1d6a4c0, 0x3398bb0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator.removeWantedDeploymentWithoutState(0xc00193e2c0, 0x1, 0x1, 0xc000f998c0, 0xc00193e2c0, 0x1)
	/go/src/github.com/gardener/gardener-extension-provider-gcp/vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go:162 +0x207
github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator.(*genericActuator).Restore(0xc00004c9c0, 0x23774e0, 0xc0008a5880, 0xc000f998c0, 0xc0010c3b00, 0x6, 0x2086ba9)
	/go/src/github.com/gardener/gardener-extension-provider-gcp/vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go:63 +0x409
github.com/gardener/gardener/extensions/pkg/controller/worker.(*reconciler).restore(0xc000446e80, 0xc000f998c0, 0xc0010c3b00, 0x2072790, 0x6, 0x16, 0xc0010c3b00, 0x0, 0x0)
```

**Comment by danielfoehrKn** [comment]
I would like to add the ContainerRuntime to the section `Implement Restore/Migrate function in extension controllers`. I opened an issue on the extension repository.

**Comment by plkokanov** [comment]
> I would like to add the ContainerRuntime to the section `Implement Restore/Migrate function in extension controllers`. I opened an issue on the extension repository.

Thanks @danielfoehrKn I added it and sorry for seeing so late. Do you plan to work on it or should we handle it?

**Comment by danielfoehrKn** [comment]
@plkokanov if it is not super urgent I can do it. But sure, feel free to go ahead (just assign yourself on the issue).

**Comment by plkokanov** [comment]
As the tasks for this issue have been completed, I will close it in favour of #4902
