### ISSUE TITLE
Add Prometheus Monitoring

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#2]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:43 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/8_

----

# Stories
* As operator I want internal monitoring, so that I can check on my cluster(s).
* As operator I want alerts on issues available in internal monitoring, so that I dont have to check on my cluster(s) manually all the time.

# Motivation
We need means to monitor our own cluster(s).

# Acceptance Criteria
- [x] All key metrics are exposed to admins in a remotely accessible UI
  - [x] Number of nodes, pods, containers, services (running, failing)
  - [x] Corresponding infrastructure components
  - [x] Cluster load, free memory, free disk space
  - [x] Key data is put onto a dashboard
- [x] Historic data is kept for the past two weeks
- [x] When we reach certain thresholds, alerts are sent to pre-configured e-mail address(es)

:information_source: Migrated from Jira issue [KUBE-21](https://jtrack.removed/browse/KUBE-21)

**Comment by vlerenc** [comment]
Implemented.
