### ISSUE TITLE
ShootValidator admission plugin is mutating

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2158]
**Why is this needed**:
Currently the `ShootValidator` admission plugin is doing quite a lot of things which are not simple validation- it is defaulting Shoot spec.networking; it is updating the `shoot.garden.sapcloud.io/tasks` annotation; it is defaulting the machine image version; it is translating spec.kubernetes.version with `<major>.<minor>` to `<major.minor.patch>` and probably other mutating operations.
If the name of the admission plugin is `ShootValidator`, I wouldn't expect a mutation to happen inside.
I guess we could split the mutation/defaulting logic in other admission plugins and allow fine-grained configuration by the Gardener admins.

**Tasks**:
- [x] Introduce the `ShootMutator` admission plugin: https://github.com/gardener/gardener/pull/13156
- [x] Move mutation of the Shoot metadata annotation from the `ShootValidator` to the `ShootMutator` admission plugin : https://github.com/gardener/gardener/pull/13171
- [x] Ensure `ShootMutator` is executed before the `ShootValidator` admission plugin: https://github.com/gardener/gardener/pull/13276
- [x] Move defaulting of the Shoot networks from the `ShootValidator` to the `ShootMutator` admission plugin: https://github.com/gardener/gardener/pull/13207
- [x] Fetch the referenced CloudProfile / NamespacedCloudProfile: https://github.com/gardener/gardener/pull/13222
- [x] Move defaulting of the Shoot Kubernetes versions from the `ShootValidator` to the `ShootMutator` admission plugin:  https://github.com/gardener/gardener/pull/13252
- [x] Move defaulting of the Shoot machine image version from the `ShootValidator` to the `ShootMutator` admission plugin: https://github.com/gardener/gardener/pull/13351
- [x] Make the `ShootValidator` admission plugin validating one: https://github.com/gardener/gardener/pull/13352
- [x] Make the `.spec.provider.workers[].machine.image` field required for the Shoot resource (part 8): https://github.com/gardener/gardener/pull/13399

**Comment by rfranzke** [comment]
This issue is open since a long time without anyone picking it up or any attention at all. Do we think that this is important enough that we spend time with it within the next month (or even year)? It seems there is not too much benefit/value of splitting it up (what would be use cases for enabling just one of the plugins while disabling the other?). Maybe we should just rename it to prevent confusing w.r.t. the `Validator` suffix in its name? Any opinions?

**Comment by timebertt** [comment]
Renaming would be an option FMPOV.
Splitting would additionally provide a better separation of concerns. The lack of it has not only caused confusion but also some bugs in the past, if I remember correctly.

**Comment by ialidzhikov** [comment]
/close
as all subtasks are resolved
