### ISSUE TITLE
Seed Cluster Disaster Recovery (a.k.a. Control Plane Migration)

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#232]
# Story
- As operator I want my seed cluster (function-wise) to recover from a disaster, so that I can ensure business continuity.

# Motivation
Availability SLO, Business continuity.

# Acceptance Criteria
- [ ] Seed cluster functionality recovers from single zone loss (=full disaster for a single zone seed cluster) with a Recovery Time Objective (RTO) of 5 minutes.

# Implementation Proposal
Move the shoot cluster control planes to another seed cluster that is either in hot stand-by (active-passive) or anyways in use (active-active) or even created on-the-fly if necessary (but then 5 minutes cannot be reached).

# Resources
- Extended Shoot Cluster Control Plane Backup & Restore Design Discussion: https://github.com/amshuman-kr/gardener/blob/master/docs/proposals/shoot-control-plane-migration/README.md

# Release Notes
``` operator release notes
- In case of a total seed cluster outage or loss (disaster), Gardener can now relocate all shoot cluster control planes autonomously and automatically to another seed cluster to ensure business continuity with an RTO of 5 minutes.
```

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/documentation about user-relevant changes?

**Comment by rfranzke** [comment]
GEP: #1546

**Comment by rfranzke** [comment]
Closing in favour of #1631
