### ISSUE TITLE
☂️Integrate vSMP MemoryOne 

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener#2354]
**How to categorize this issue?**

/area usability
/area os
/kind epic
/kind enhancement
/priority normal

**What would you like to be added**: 
This is an umbrella issue for the integration of vSMP MemoryONE operating-system based machines with Gardener. 

MemoryONE helps in the expansion of memory using non-volatile storage-class memory, which is cost-effective against expensive DRAMs.

MemoryONE is a virtual machine technology that transparently expands the system memory and then runs a standard Linux-based operating-system.
We have been requested to support jeos/chost-sles for the same. Please find more information on the product [here](https://www.scalemp.com/products/vsmp-memoryone/).

Please find the detailed process [here](https://files01.scalemp.com/downloads/others/EC2/docs/vSMP_MemoryONE_for_EC2-userguide.pdf), around how to boot up the machine based on MemoryONE VM. 

The following are the main changes required for the complete integration, which can also be used to track the progress. 
- [x] Adapt MCM to support multiple-disks for AWS. @hardikdr 
      - Tracking issue: https://github.com/gardener/machine-controller-manager/issues/462

- [x] Adapt chost/jeos extension controller to prepend the MemoryONE user data. @rfranzke  
       - Tracking issue: https://github.com/gardener/gardener-extension-os-suse-jeos/issues/18
       -  Implementation PR (Gardener): https://github.com/gardener/gardener/pull/2420
       -  Implementation PR (SuSE JeOS extension): https://github.com/gardener/gardener-extension-os-suse-jeos/pull/19

- [x] Allow setting the env-variable in kube-scheduler to overwrite the max-attachable volumes to machines. Investigate related configurations for CSI-drivers. @rfranzke 
       -  Tracking issue: https://github.com/gardener/gardener/issues/2343
       -  Implementation PR: https://github.com/gardener/gardener/pull/2413

- [x] Adapt AWS-worker extension controller to support multiple disks. @rfranzke 
       -  Implementation PR: https://github.com/gardener/gardener-extension-provider-aws/pull/105

- [x] Adapt AWS-worker extension controller to support disks with snapshots. @rfranzke 
       -  Implementation PR: https://github.com/gardener/gardener-extension-provider-aws/pull/112

- [x] Adapt/Verify Gardener APIs to allow setting multiple volumes and customization configs for AWS via shoot-resource. @rfranzke @hardikdr 
       -  Implementation PR: https://github.com/gardener/gardener/pull/2438

**Comment by ghost** [comment]
@hardikdr Label "area/usabiliity" does not exist for this repository.

**Comment by rfranzke** [comment]
>  Adapt AWS-worker extension controller to support multiple disks.

The first PR https://github.com/gardener/gardener-extension-provider-aws/pull/105 was opened to support multiple disks for the worker machines. In another follow-up PR I'll add support for providing a snapshot ID for the data volumes.

**Comment by rfranzke** [comment]
>  Adapt AWS-worker extension controller to support disks with snapshots.

The second PR https://github.com/gardener/gardener-extension-provider-aws/pull/112 was opened to support providing a snapshot ID for data volumes.

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/pull/2413 allows configuring the `KUBE_MAX_PD_VOLS` environment variable. Helpful information next to the Kubernetes documentation and https://github.com/gardener/gardener/issues/2343#issuecomment-633982785 is here: https://kubernetes.slack.com/archives/C09QZFCE5/p1585038040227700

**Comment by rfranzke** [comment]
All the related pull requests have been opened (see above references). Once reviewed and merged we can release the various components.

There is an open topic with respect to the override of the volume limits per nodes. #2413 will allow configuring the kube-scheduler, though, it seems to only work up to Kubernetes v1.16. In v1.17 there is an issue (see above linked Slack thread), and beginning with v1.18+ the AWS is using the EBS CSI driver which is not supporting the override yet (see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/347).

Together with @hardikdr we were successfully e2e testing the creating of an AWS shoot with vSMP MemoryOne operating system using the following images:
* gardener/gardener: `eu.gcr.io/gardener-project/gardener/gardenlet:v1.6.0-dev-b50098267f2577d06674903fa20032f1fe44894b`
* gardener/gardener-extension-os-suse-jeos: `eu.gcr.io/gardener-project/gardener/extensions/os-suse-jeos:v1.7.0-dev-scalemp` (incorporating https://github.com/gardener/gardener-extension-os-suse-jeos/pull/19)
* gardener/gardener-extension-provider-aws: `eu.gcr.io/gardener-project/gardener/extensions/provider-aws:v1.9.0-dev-scalemp` (incorporating https://github.com/gardener/gardener-extension-provider-aws/pull/112)

We used the following worker pool configuration:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: vsmp-memoryone
  namespace: garden-foo
spec:
  ...
  workers:
  - name: cpu-worker3
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
    machine:
      image:
        name: memoryone-chost
        version: 9.5.195
        providerConfig:
          apiVersion: memoryone-chost.os.extensions.gardener.cloud/v1alpha1
          kind: OperatingSystemConfiguration
          memTopology: "2"
          systemMemory: "6x"
      type: c5d.metal
    volume:
      size: 20Gi
      type: gp2
    dataVolumes:
    - name: jeos
      size: 50Gi
      type: gp2
    providerConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: WorkerConfig
      dataVolumes:
      - name: jeos
        snapshotID: snap-123456
    zones:
    - eu-central-1b
```
