### ISSUE TITLE
Use cached controller-runtime client

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#2414]
**How to categorize this issue?**

/area quality networking cost
/kind enhancement

**What would you like to be added**:

In g/g we have an increasing number of API calls that are made via controller-runtime clients instead of using more efficient mechanisms like `Informers` or `Listers`.
In our current implementation, these clients — no matter if for garden, seed, plant or shoot cluster — are not backed by a cache, which means, that every call will result in a direct call to the respective API server. Because most of these calls go to API servers that are not running on the same cluster / in the same "network" (e.g. to the garden cluster or to the (shooted) seed's API server) like the caller (mainly gardenlet), they contribute to "external" traffic, which is (highly) priced by cloud providers.

Also, there are many different places and mechanisms in our code, where and how we construct such ClientSets, ChartRenderes, ChartAppliers, RESTMappers and so on, and they are very short-lived (e.g often constructed only for a single operation and discarded after the operation has completed).

As we will probably introduce more and more API calls via controller-runtime clients (because it is less complicated to use and allows more generic constructs), we should refactor how we construct/retrieve those clients and equip them with a cache, so we can save unnecessary network traffic (costs).

Related to/part of #1953

## Steps

#2822 tracks all steps for graduating the `CachedRuntimeClients` feature gate, but they can also be considered a part of this issue.

These are steps/subtasks of this issue, that are not strictly required for or related to the graduation of the feature gate but rather general improvements regarding cached controller-runtime clients:

- [x] Harmonize/centralize `RESTMapper` creation and get rid of disk cached discovery clients (#2415)
- [x] Harmonize/centralize `Applier`, `ChartRenderer` and `ChartApplier` creation (#2417)
- [x] Add a cached controller-runtime client to our clientset in `pkg/client/kubernetes` (~~will be used by default, so this will result in a breaking change for all callers~~ will be put behind a feature gate, so we can disable it if we encouter some problems while running it in a productive system) (#2449)
- [x] Add some form of a registry (`ClientMap`) which can be used by all components/controllers to retrieve clients to arbitrary clusters in a harmonized way and which keeps track of all constructed clients (#2449)
- [x] Adapt the main components (gcm, gardenlet) and all their controllers to make use of the `ClientMap` (#2449)
- [x] Adapt usages in the integration test framework (#2474)
- [x] Eliminate usages of generated client sets in `kubernetes.Interface` wherever appropriate in favor of cached controller-runtime clients
  - [x] `kubernetes.Interface.Kubernetes()` (i.e. client-go): #5754
  - [x] `kubernetes.Interface.Garden{Core,SeedManagement,Operations}` (i.e. our own generated client sets): #4592
  - [x] `kubernetes.Interface.API{Registration,Extension}`: #4592
- [x] Eliminate wrongful usages of `Try{Update,Patch}`, `RetryOnConflict`, `exponentialBackoff` in extensions library: https://github.com/gardener/gardener/pull/4799
- [x] Eliminate wrongful usages of `Try{Update,Patch}`, `RetryOnConflict`, `exponentialBackoff` in resource-manager code: https://github.com/gardener/gardener/pull/4799
- [x] only [patch shoot status label](https://github.com/gardener/gardener/blob/b07e623e814b9a768383a54319046aa5bf77c12f/pkg/gardenlet/controller/shoot/shoot_care_control.go#L367-L374) if necessary: #4870
- [x] ~~enable (cached) controller-runtime clients in gardener-apiserver admission plugins~~
- [x] ~~Eliminate unstructured requests in chart applier~~ (rather compolete component refactorings will switch to typed requests, see #2754)
- [x] Promote CachedRuntimeClients feature gate to GA : #5752

**Comment by rfranzke** [comment]
@timebertt Should this issue be closed in favor of #2822? Or do you want to track this separately?

**Comment by timebertt** [comment]
We could keep this one open as it is also about refactoring the client usage in the extension library, which is not related to the feature gate.
But I don't have a strong opinion.

**Comment by rfranzke** [comment]
cc @acumino @shafeeqes @ary1992, it seems there is just a very small TODO left to get this issue closed. Maybe you can have a look when you are free :)

**Comment by acumino** [comment]
/close
All the tasks are completed.
