### ISSUE TITLE
Multi-Tenancy

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#28]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/46_

----

# Stories
* As user I dont want others to see or interact with (get logs, kill pod) containers deployed by me, so that nobody can spy on me.
* As user I dont want to accidentally break containers deployed by others, so that I dont harm anybody.
* As operator I want to utilise the hardware as best as possible, so that I can offer a competitive price.
* As operator I want to manage as few as possible clusters, so that I can do a better job on these clusters.

# Motivation
In order to not having to deploy too many individual clusters, we ought to be able to let multiple teams (later maybe even customers) work concurrently on one cluster.

# Acceptance Criteria
- [ ] No non-admin user can deploy privileged containers
- [ ] Users from one namespace cant see or interact with (get logs, kill pod) containers deployed into other namespaces
- [ ] Containers from one namespace cant access other containers in any direct way

# Implementation Proposal
RBAC, security and network policies (defined per namespace) are the concepts that need to be explored at the time of this writing.

:information_source: Migrated from Jira issue [KUBE-23](https://jtrack.removed/browse/KUBE-23)

**Comment by vlerenc** [comment]
No topic for the Gardener.
