### ISSUE TITLE
 ☂️ -Issue for graduating CachedRuntimeClients to beta

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2822]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What would you like to be added**:
Since the introduction of the cached controller-runtime clients #2449 we should strive for graduating this feature to beta so that we can make use of all the delivered features in development. We broke down the graduation process to the following tasks after we tested the feature on different internal landscapes:

Required for graduation:
- [x] Get rid of the `DirectClient` and replace its usages by Patch requests and other proper mechanisms (see https://github.com/gardener/gardener/issues/2822#issuecomment-702132185) ➡️ preparations: see linked PRs below, removal in https://github.com/gardener/gardener/pull/4225
- [x] Improve g-api stability during rolling updates ➡️ #2814
- [x] Distribute rollout of Gardenlets for shooted seeds ➡️ #2687
- [x] Refactor existing controllers to get and use informers from the controller-runtime cache instead of relying on SharedInformerFactories (i.e. get rid of duplicated watches)
  - gardener-scheduler ➡️  #3746
  - gardener-controller-manager ➡️ #3768, #3982 (and similar)
  - gardenlet ➡️ #4503, #4510
- [x] Replace `CreateOrUpdate` with `GetAndCreateOr*Patch` ➡️ #4227
- [x] ~Replace `CreateOrUpdate` in [gardener-resource-manager library](https://github.com/gardener/gardener/blob/e8b66dccd11adb73e284cbf4a3ac36246eeb0b88/vendor/github.com/gardener/gardener-resource-manager/pkg/manager/managedresources.go#L106)~
- [x] Eliminate wrongful usages of `retry.RetryOnConflict` ➡️ #4246
- [x] Eliminate wrongful usages of `Try{Update,Patch}` in gardener components ➡️ #4378
- [x] add some developer documentation on client usage (e.g. caveats of cached clients, conflict management / optimistic locking, different patch types, ...) ➡️ #4425
- [x] use strategic merge patch for patching finalizers of built-in or gardener objects (provided by gardener-apiserver) in order to run without optimistic locking (make use of `merge` and `$deleteFromPrimitiveList` directive on finalizers array (see [doc](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#merge-directive))) to reduce the amount of conflicts (especially on start of reconciliations) ➡️ #4696
- [x] https://github.com/gardener/gardener/issues/4648
- [x] https://github.com/gardener/gardener/issues/4762

Other nice-to-have steps, cleanups, etc. (not strictly required for or related to the graduation of feature gate) are tracked in #2414

**Comment by rfranzke** [comment]
After having enabled the `CachedRuntimeClients` feature gate in the gardenlet on a large landscape, we have seen significant resource increases in the kube-apiserver and gardener-apiserver.

This is showing the usage **with** the feature gate being enabled:

```
gardener-apiserver-7df4b44c8c-lgfgg               2040m        5863Mi
gardener-apiserver-7df4b44c8c-llrbk               1996m        7370Mi
gardener-apiserver-7df4b44c8c-p8lks               1809m        4245Mi
gardener-apiserver-7df4b44c8c-phvxc               6266m        30830Mi
gardener-apiserver-7df4b44c8c-r75sn               3966m        20303Mi
gardener-apiserver-7df4b44c8c-tf8hd               1975m        18992Mi
gardener-controller-manager-67bfbb8664-gptms      178m         614Mi
gardener-dashboard-5bddfb6798-dqqzp               95m          130Mi
gardener-scheduler-7d9cb6d79-72k9r                65m          39Mi
gardenlet-7765c66877-dggtk                        264m         2277Mi
virtual-garden-etcd-events-0                      993m         854Mi
virtual-garden-etcd-main-0                        1105m        2055Mi
virtual-garden-kube-apiserver-c7c579555-8zf2j     3049m        2479Mi
virtual-garden-kube-apiserver-c7c579555-bv6pz     620m         920Mi
virtual-garden-kube-apiserver-c7c579555-bxcfr     665m         1927Mi
virtual-garden-kube-apiserver-c7c579555-k2w6d     2407m        2887Mi
virtual-garden-kube-apiserver-c7c579555-qqr6p     1104m        2177Mi
virtual-garden-kube-apiserver-c7c579555-vvt7j     293m         977Mi
```

After having disabled the feature gate again (only in the gardenlet), resource consumption dropped significantly:

```
gardener-apiserver-7df4b44c8c-lgfgg               1110m        3623Mi
gardener-apiserver-7df4b44c8c-llrbk               5325m        6286Mi
gardener-apiserver-7df4b44c8c-p8lks               2057m        4313Mi
gardener-apiserver-7df4b44c8c-phvxc               935m         10806Mi
gardener-apiserver-7df4b44c8c-r75sn               3031m        5698Mi
gardener-apiserver-7df4b44c8c-tf8hd               1099m        3917Mi
gardener-controller-manager-67bfbb8664-gptms      62m          661Mi
gardener-dashboard-5bddfb6798-dqqzp               93m          148Mi
gardener-scheduler-7d9cb6d79-72k9r                43m          39Mi
gardenlet-7765c66877-sj9s9                        192m         452Mi
virtual-garden-etcd-events-0                      998m         1915Mi
virtual-garden-etcd-main-0                        1608m        2318Mi
virtual-garden-kube-apiserver-c7c579555-8zf2j     1023m        869Mi
virtual-garden-kube-apiserver-c7c579555-bv6pz     569m         977Mi
virtual-garden-kube-apiserver-c7c579555-bxcfr     1784m        1282Mi
virtual-garden-kube-apiserver-c7c579555-k2w6d     350m         1004Mi
virtual-garden-kube-apiserver-c7c579555-qqr6p     687m         3058Mi
virtual-garden-kube-apiserver-c7c579555-vvt7j     1388m        888Mi
```

**Comment by timebertt** [comment]
@timuthy and I had an interesting discussion about the client usage in gardener and about this topic again.

We see the following problems with the combination of `Client` and `DirectClient` in our ClientSets:
- it is very confusing, when to use what
- `DirectClient` and `Client` are interoperable and can therefore be easily replaced/switches (both implement the same interface – `client.Client`)
- using the `DirectClient` does not solve the problem that data read from the cache or even the API server might always be slightly out of date (e.g. in API HA setup, one instance might have intermittent connection issues while reaching etcd) but is rather a work-around for using proper mechanism
- the usage/implementation differs from the concepts in controller-runtime (there you can only get a direct reader but not a whole direct client) and might impose difficulties when fully adopting controller-runtime in the future

To improve on this situation and move forward with the graduation, we want to:
- get rid of the `DirectClient` in our ClientSets and its usages
- replace usages of it by proper mechanism that tolerate slightly out-of-date data, e.g.
  - Patch requests (instead of Put requests with a `DirectClient`)
  - ensuring to check updated versions by using mechanisms like proposed in #2928 with `health. ExtensionOperationHasBeenUpdatedSince` (which can be used with a cached client without risk)
- offer a `APIReader() client.Reader` in our ClientSets instead of the `DirectClient` which won't be interoperable with `Client()` (e.g. can't be used with standard helper funcs accepting a `client.Client`) so you are "forced" by the compiler to at least think about proper mechanism to solve race issues

**Comment by vpnachev** [comment]
While investigating #3433 , it turns out it is not reproducible when the `CachedRuntimeClients` feature is enabled.
I was also looking in the audit logs, there is no list or delete requests from gardenlet for the above clusterrole and clusterrolebindings. On the other side, when the feature is disabled, I do see the list requests followed by delete.

**Comment by timebertt** [comment]
We should also take a look at / investigate how to:
- [ ] Enhance health endpoints (gardenlet, grm, etc.) to include checks for informer/watch healthiness

**Comment by timebertt** [comment]
/assign
Will work on this next.

**Comment by timebertt** [comment]
Note about this subtask:

> Replace `CreateOrUpdate` in [gardener-resource-manager library](https://github.com/gardener/gardener/blob/e8b66dccd11adb73e284cbf4a3ac36246eeb0b88/vendor/github.com/gardener/gardener-resource-manager/pkg/manager/managedresources.go#L106)

I decided to not spend any effort on replacing `CreateOrUpdate` in the grm library, as it's probably not worth it. (at least for now).
For the secrets, there will probably be only a small number of conflicts, as no one else is updating them regularly (only grm adds its finalizer, which is a one-time op).
For the managed resources, chances for running into conflicts are also small, because spec, labels, etc. change only very rarely and `CreateOrUpdate` doesn't send anything a request, if there's no change.

If we see the need for replacing this as well, because we observe a higher amount of conflicts than expected, we can still optimize it.

**Comment by timebertt** [comment]
BTW: It wasn't mentioned here, but with https://github.com/gardener/gardener/pull/4320 the `CachedRuntimeClients` feature gate was actually dropped in gardener-scheduler (now all clients are cached by default there).
Hence, there's nothing to graduate in the scheduler anymore, only in gardener-controller-manager and gardenlet.

**Comment by timebertt** [comment]
Update:

I updated the task list and moved all the nice-to-have / cleanup tasks, that are not required for graduating the feature gate, to https://github.com/gardener/gardener/issues/2414.

#4696 completes the last open task required for the graduation.
So once the next version including the PR is released and it is running fine without any additional issues, I plan to promote the feature gate to `beta`
