### ISSUE TITLE
Gardener Extensibility

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#308]
# Story
- As contributor I want to extend the Gardener out-of-tree, so that I can more easily add functionality I need, maybe even functionality that would never be included into the master branch.
- As developer I want the Gardener to be extensible out-of-tree, so that it becomes more versatile and it's community can grow faster without its maintainers turning into a bottleneck.

# Motivation
We see pull for more infrastructures and technologies, but the in-tree extension concepts (a.k.a. botanists) make cooperation harder than necessary. Also, specific extensions, e.g. custom audit logging, can't be easily done in-tree as it wouldn't be possible to allow all specifics of all individual stakeholders in-tree.

# Acceptance Criteria
- [ ] Infrastructure support moves out-of-tree
- [ ] Custom extensions can be added out-of-tree

# Implementation Proposal [Discussion / WiP]
- Gardener provisioning and infrastructure code moves out into dedicated controllers. These controllers and everything else that needs to be deployed to the Garden or a Seed cluster are merely configurations that are anonymously deployed into the respective clusters by Gardener. When the Gardener sees a shoot resource, it takes its spec apart and creates custom resources in the seed cluster that the controllers act upon. It only needs to understand very few spec sections like DNS, but doesn’t need to understand the extensions and won’t care. An Alibaba infrastructure controller may see the Alibaba spec and act on it, e.g. creating networks and such. An audit log controller may see the audit log spec and likewise act on it, e.g. create an audit log service instance/binding and apply the desired audit log policy to the particular shoot cluster API server. All controllers are requested to write their essential state (that cannot be reconstructed) into the status field of the CRs that the Gardener will watch and reconcile, i.e. it will pull the information into the relative safety of the Garden cluster. Should the seed be lost or a shoot cluster be moved, normal reconciliation will move the information back into the seed and the control plane will rematerialize.
- MCM is another topic right now and why we could embrace it similarly, the community seems to have made up their mind already in the context of the machine API and doesn’t want to go with full blown controllers, but processes offering a GRPC interface, i.e. MCM shall call into the different infrastructure-aware machine controllers. Maybe this will change again, but right now that’s the favoured extension model in the community.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit tests are provided: Have you written automated unit tests?
- [ ] Integration tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added/changed public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the operations guide about ops-relevant changes?
- [ ] User documentation: Have you updated the READMEs/docs/how-tos about user-relevant changes?
