### ISSUE TITLE
Provide a way to quickly dispose Shoot cluster

### ISSUE THREAD

**Issue by pbochynski** [gardener/gardener#3110]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:
The option to delete the cluster by destroying worker VMs without waiting for clean delete of all kubernetes resources. 
I can imagine it as an annotation on the Shoot: 
```
confirmation.gardener.cloud/deletion-force: true
```

**Why is this needed**:
I use a temporary gardener cluster to run the integration test. All the resources used for tests are deployed in the cluster (database, file storage, etc). The provisioning of the cluster takes about 5 minutes and test setup another 3-5 minutes. The clean up for resources created in the test takes about 3-5 minutes (delete resources, helm uninstall, delete CRD, delete namespaces). Then Shoot delete takes 5-15 minutes in the best case, but often more than 30 minutes. The result of the test can be provided in 10 minutes, but the job has to wait another 10-60 minutes to be finished. We just waste a lot of time and resources.

**Comment by vpnachev** [comment]
Just a bit more context, you are asking for a feature that skips the deletion or at least does not fail on deletion of the k8s resources inside the shoot cluster, right?

**Comment by ialidzhikov** [comment]
> Then Shoot delete takes 5-15 minutes in the best case, but often more than 30 minutes

From my observation from our integration tests the Shoot deletion takes 10-15min. 
Do you have CRDs are other resources that block the cleanup and need to be finalized by gardener after a timeout? If you are sure that this is not the case, then can you share at which step(s) from the deletion flow it spends more time than expected (when the deletion takes more than 30 min)?

**Comment by pbochynski** [comment]
Yes - the problem is that some orphan objects remain and have finalizers from already uninstalled controllers. I am thinking about writing a tool similar to this one: https://github.com/ctron/kill-kube-ns
But I would need to go through all CRD and for each CRD list all the objects and remove the finalizers. It is doable but will take some time, and I just don't care about clean up. I am going to delete the entire cluster anyway. I could imagine that you just free cluster resources VM when special flag is added. It would also free some resources in the Seed. In case of orphan objects with finalizers can take more than hour. Example: https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-dog/shoots/c04210451/

**Comment by vlerenc** [comment]
@pbochynski Yes, we are contemplating the same (cc as well to the already participating Gardener colleagues also @dguendisch, @rfranzke @timebertt ). In general and many years ago we thought it makes more sense to go the safe way "through the API server", so that we never become responsible for orphaned resources (controllers might be responsible for real world resources, e.g. infrastructures resources like databases and such not managed by K8s core components). This however is becoming ops effort for us more and more, now running many thousand clusters as indeed people want to delete clusters that are already broken in one way or the another (and a missing controller is such an issue). So, we plan to add code for forceful deletion. We do not have an BLI yet, as we are in the process to find out what needs to change, so this morning (coincidence), we have a meeting with our machine controller colleagues that would block that if the API server is down and nodes cannot be retrieved. We also have a few more components we must think of, but in general, we need to offer forceful deletion or else questions like "I cannot delete my cluster" won't stop. Thank you for opening the issue.

**Comment by vlerenc** [comment]
Let me add some more details: We need a solution for the following cases:
- invalid credentials
- deliberate deletion of resources managed by us
- creating infrastructure dependencies that block us
- deleted controllers for custom resources/resources with finalisers that won’t go away, because the end users have deleted the responsible controllers
- too long grace periods, so users get impatient and start creating new problems (best case) by contacting us on Slack and (worst case) starting to delete resources manually (problem above)

/cc @dguendisch 

In case of invalid credentials:
We cannot do much in this case and it's actually a very special (second case) of "forceful" deletion. Let's call it rather "purge". If invoked, it would mean "I don’t care, just delete the cluster metadata from my Gardener project and don’t touch my infrastructure anymore - I will deal with it or have already dealt with the infrastructure.".

In case of infrastructure dependencies:
We can learn and improve over time. At first, I would interpret “forceful” as “Gardener doesn't need to bring up the control plane anymore” (and in some cases it may really be down and stay down). Then I would get rid of LBs by calling the Cloud SDKs, because we know that’s blocking us (disks are not). On top, step by step, I would learn what else could block us (e.g. other network resources, EFS, etc.). It’s not nice, but either that or we are always involved. I believe, with the number of clusters increasing and increasing, it’s cheaper to add that kind of “dependency cleanup code” than trying to discuss it case by case.

Note on the question whether this will create orphaned resources:
I believe, we have to accept that and not stand in the way of our end users. It's their decision, whether they want to go for forceful deletion. Also, what’s the option? We are involved again and again and in the end, we anyways can’t do anything if our credentials were revoked, etc. We end up doing the above anyways, just manually. Then it’s better to have a “self-service” and that’s what forceful deletion is. A “self-service” where the end users sign "with their blood", that’s it’s now their problem. We can only help so much and then it’s just not possible anymore. Burning dev time on both sides costs money, too. Burning that time and still not being able to purge all IaaS resources is double waste.
That's also what all hyperscalers do (I understand, it’s in their interest, but not in SAP’s interest, but we cannot help here either in most cases) and most users won’t have created additional resources. If we purge the LBs, all our Gardener-managed resources, the networks and such (and by that also the machines), the majority of all the resources is gone (on Azure even everything, because we have resource sets there). The only thing that some users might forget to purge are disks, but then again: these users won’t go for the forceful deletion as their first choice (and much less for the above described purge option, which is really the very last resort). They will do that only if they did something odd. Giving them this option, will make them choose it when we offer it, but only as step 2 (purge being step 3). Today, if the normal deletion hangs for them, they go right into the infrastructure and break everything for us and them. That’s the worst of all options and we should change that.

**Comment by dguendisch** [comment]
We discussed this topic in a meeting, here's the outcome:

- for cases like broken/lost/invalid cloudprovider accounts we agree that it makes sense to provide an option to "purge" a cluster. "Purge" means to ignore the customers cloudprovider resources and instead delete everything on our accounts (seed resources) plus our metadata in gardener.
  - we want to enable this feature in a first step only for operators, not to shoot consumers
  - we reasses afterwards how we can expose this feature also to shoot consumers with the needed care of ensuring that they are aware of the leaking consequences

- the advanced case of infrastructure dependencies sounds too complicated and unclear to tackle in a special way for now:
  - highly cloudprovider specific -> huge effort
  - many different cases -> e.g. a VPC might be a pre-existing one used in other scenarios as well
  - unclear what to delete, esp. since cases exist where resources inside a vpc/resourcegroup might be reused in other scenarious (outside of that shoot purpose)
  - in the end if deps are blocking the deletion, "purging" (with all consequences) as described in the first case is the way forward

- the particular case from @pbochynski https://github.com/gardener/gardener/issues/3110#issuecomment-722000961
  - only deleting VMs is too less
  - current behaviour does not block deletion but only prolongs it (as it waits up to one hour for CRD deletion)
  - there is already a mean in place that would speed up: setting the no-delete label on the resp. resources (then gardener wouldn't try to delete them and thus not wait for them), however that means @pbochynski would need to adapt his automation for testing
  - if adaptation on testing automation is necessary, it would be more clean to just improve the test teardown to remove the resources prolonging the shoot deletion by either deleting them correctly or deleting them forcefully (i.e. removing their finalizers in the test teardown)

Overall there are pros (ops effort) and cons (leakage) to forceful deletion (most aspects listed by @vlerenc above), however one new risk brought up by @ialidzhikov is that doing forceful deletion from customer side could overshadow problems in gardener (i.e. gardener fails to proceed with deletion, hence customer decides to forceful delete, although gardener should have properly progressed with deletion, one example: https://github.com/gardener/machine-controller-manager/issues/562)

Please ammend if I missed something.

**Comment by vlerenc** [comment]
Thanks for the discussion @dguendisch @rfranzke @timebertt @prashanth26 @mvladev @dkistner @vpnachev @ialidzhikov and sorry I couldn't join that meeting yesterday.

### History

Many years ago we thought it makes more sense to go the safe way "through the API server" and delete all resources, so that we never become responsible for orphaned resources (controllers might be responsible for real world resources, e.g. infrastructures resources like databases and such not managed by K8s core components). That and of course, that the LBs would be deleted this way without us writing IaaS code that deletes them (and we need them to be deleted to delete the networks). This however is becoming ops effort for us more and more.

### This Case

@pbochynski only needs a delete option that deletes the cluster without respecting any finalizers / workload in the cluster. We already have a grace period in place and we could offer to make it configurable and he could set it to zero. I am not sure if we have only one grace period or deal with LB services differently and I have forgotten what's the status of the finalizers for these in all Kubernetes versions, but we can find a solution there and deal with them differently.
We could also interpret this as a case where the cluster shall be deleted whose control plane doesn’t come up anymore, in which case we would need to have IaaS code to delete the LBs, which is the more general case. That plus the other changes like in MCM and similar controllers that today needlessly want to talk to the API server.

### Summary Above

On purge: Great that we will built it. Not so great that we are still reluctant to expose it. Why? I don't want to design a system that depends on manual ops. This was always our mantra. Intelligent human minds should only handle the unforeseen corner cases. Automation and self-service should dea with the rest. Also, I think we should not patronise our end users. That was another mantra of ours. Why would we block them and ask them to go through ops? We should invite the Dashboard colleagues to design a purge dialog that takes care of that, with double confirmation or a forceful wait before the confirmation to read the fine print.

On @pbochynski ‘s case: I don’t understand the answer at all. His case is what troubles us and our end users the most and yet, we don’t want to do anything about it? This is THE reason we are having these discussions again and again. It is THE reason cluster deletion takes long and THE reason people get irritated and ping us on Slack (best case) or start deleting IaaS resources (worst case) and yet, we don’t want to do anything about that and tell @pbochynski to improve his test case. It is just one of many similar cases. While we could ask him to do that (yes, he can, maybe even should, but I am not even sure about this), it wouldn't solve the general problem that we are seeing so often at all.

On infrastructure dependencies: I understand the effort, but as I wrote above: “It’s not nice, but either that or we are always involved. I believe, with the number of clusters increasing and increasing, it’s cheaper to add that kind of dependency cleanup code than trying to discuss it case by case.”.

> highly cloudprovider specific -> huge effort

As written above, I would get rid of LBs by calling the Cloud SDKs, because we know that’s blocking us (volumes are not). On top, step by step, we could learn what else is blocking us and improve the error messages, so that the end users know what blocks them in detail.

> many different cases -> e.g. a VPC might be a pre-existing one used in other scenarios as well

What is that and why is that written here? We distinguish these cases also today. We don’t delete provided VPCs, so why would they block our deletion if we ignore them anyway. Why is forceful deletion now about them? This makes no sense as counter-argument whatsoever.

> unclear what to delete, esp. since cases exist where resources inside a vpc/resourcegroup might be reused in other scenarious (outside of that shoot purpose)

See above. What is unclear? We delete the LBs, because they got created by controllers that we have deployed. We can decide, whether our error messages are sufficient and the end users understand what blocks cluster deletion (preferred) or delete even more resources (OK for stateless resources if the case reoccurs too often and we cannot improve the error messages sufficiently enough, which seems unlikely - not OK with everything with state like an RDS instance in one of our networks). If the error messages are sufficient, there would be no more resources we would need to delete. End users would then have the information they need and if they mess up the manual cleanup of “their” resources, they can purge the cluster on our end and delete everything on their end.

We have to delete what we bring and we bring not only the `terraform`ed resources, but also the resources our controllers bring, like LBs (which we can identify by association with VPC and their tags), DNS records, and that’s already it, right?

Again, I may be wrong and am open for correction, but above I didn't find that information in the word "unclear".

> in the end if deps are blocking the deletion, "purging" (with all consequences) as described in the first case is the way forward

Yes, absolutely.

### All Cases

We know of the following cases in combination with cluster deletion, please correct me if I am wrong:
- invalid credentials
- creating infrastructure dependencies that block us from deleting the cluster
- deliberate deletion of resources managed by us, that confuses our own deletion
- deleted controllers for custom resources/resources with finalisers that won’t go away, because the end users have deleted the responsible controllers
- too long grace periods, so users get impatient and start creating new problems (best case) by contacting us on Slack and (worst case) starting to delete resources manually
- control planes that fail to come up / become responsive for whatever reasons (DoS from the nodes/pods/workload in the cluster, broken web hooks, feature gates that do not match an upgraded Kubernetes API server that then fails to start up, etc.)
- hibernated clusters that nobody needs or wants to bring up prior to deletion (maybe because they are larger or dysfunctional anyway)

#### Invalid Credentials

We cannot do much in this case and it's actually a very special case of "forceful" deletion. Let's call it rather "purge" and we already agreed to offer it. We differ only whether we will offer it in the UI and I would definitely do that. Ops should never have to deal with reoccurring and foreseen tasks like this if it cannot be helped (our own safety or production is at risk, which is not the case here, so it's only up to the end users - the ops colleagues are not their "human confirmation dialog" or reminder or whatever - they are highly skilled personal that usually should play with their kids or sleep or whatever and only be involved when things do not work unexpectedly).

#### Infrastructure Dependencies

See above. We should take care of all resources we bring into the game, which includes also LBs in case we can't bring up the control plane again. Other than that, it depends. In general, our error messages shall be good enough for the end users to understand the problem and help themselves. We might, case by case, decide to delete stateless resources, but never stateful resources. But discussing that here is too early. We don't have to decide anything here and I wouldn't want to either.

#### Resource Partly Deleted by End Users

Purge is the answer - clearly as a self-service, in my eyes.

#### Hanging Resources / Cluster Deletion Takes Too Long

We should offer regular deletion of clusters with the option to influence the grace period, zero if the end user decides. Resources created by us or the controllers we deployed are exempt. Either we delete them without grace period (not a good idea) or we treat the cluster after the grace period has lapsed as a cluster whose control plane is failing (preferred). In that case we would delete the cluster forcefully (next case below).

#### Control Plane Down / Hibernated Clusters

We should learn how to delete clusters without control plane. Besides todays dependencies in MCM and the like to the API server, we have to deal with all stateless IaaS resources the controllers we deployed created, which are only the LBs, right? PVs are stateful and would remain/can remain. LB deletion code would then be the only IaaS-specific code we would hopefully need. Then we can delete unresponsive or hibernated clusters and have never again to deal with this question.

### Wrap-Up

I would therefore suggest the following cluster deletion "options:
1. Regular deletion with configurable grace period
2. Forceful deletion that doesn't require a running control plane (invoked after grace period has lapsed)
3. Purge that only deletes the IaaS and Kubernetes resources on our end

Since a lapsed grace period or a grace period of zero equals forceful deletion, we would need to make only the regular deletion configurable, learn how to delete a cluster without control plane when it lapsed, and write the purge deletion code.

I would offer these (then actually two) deletion options in the Gardener Dashboard:
1. Delete Cluster (with configurable grace period)
2. Purge Cluster (with respective confirmation)

WDYT? What's wrong with this?

**Comment by vpnachev** [comment]
> On top, step by step, we could learn what else is blocking us and improve the error messages, so that the end users know what blocks them in detail.

I am not sure about this. Shoot owners can deploy their own custom resources with custom controllers that creates IaaS resources potentially blocking the deletion. Then we will have to know how to delete these IaaS resource that can block us and this will be never ending learning because the cloud provider can enable some new resource at any time (unlikely to happen very often). 

>  >    many different cases -> e.g. a VPC might be a pre-existing one used in other scenarios as well

> What is that and why is that written here? We distinguish these cases also today. We don’t delete provided VPCs, so why would they block our deletion if we ignore them anyway. Why is forceful deletion now about them? This makes no sense as counter-argument whatsoever.

The case is when the shoot owner re-use the VPC created by Gardener to run something else, which is even can be not related/connected to the shoot cluster at all. If we then purge the VPC, we will bring down anything else that is deployed.


To be honest, I would just expose the option to abandon the `Infrastructure` in the seed and let the shoot owner handle its deletion. This will also support the scenario with invalid credentials and already deleted infrastructure.

**Comment by vlerenc** [comment]
> I am not sure about this. Shoot owners can deploy their own custom resources with custom controllers that creates IaaS resources potentially blocking the deletion. Then we will have to know how to delete these IaaS resource that can block us and this will be never ending learning because the cloud provider can enable some new resource at any time (unlikely to happen very often).

@vpnachev For one, it's first about improving the error messages. That is always the preferred way. I am not sure which hints you get with the different IaaS SDKs (e.g. when you try to delete a VPC and can't - do you only get a failure code and nothing else or a list of resources blocking the deletion or is there a simple way to enumerate the blocking resources easily). Then, only if that doesn't work and a certain problem wastes our time again and again and we speak of ephemeral resources (EFS and RDS are stateful, so we would not/never delete them anyway), we might actually delete these ephemeral resources, but we neither should nor have to make this call now.

> The case is when the shoot owner re-use the VPC created by Gardener to run something else, which is even can be not related/connected to the shoot cluster at all. If we then purge the VPC, we will bring down anything else that is deployed.

One comment in advance: "Purge" in the sense of my comment above is maybe a poor choice for that option/word. Maybe "Drop" or "Forget" would be better. Your "purge" on the other hand is actually not what I meant with "purge".

OK, with that out of the way, your scenario is the same as the general scenario in which the end user puts additional resources into resources like our VPC. So, we don't have to consider that separately.

And the strategy for that is outlined above: Let's improve the error messages. We don't have to perfect everything from day one. It's anyways the same also operators would do. So let's improve the error messages and don't misuse operators for that kind of job, if we can. Only if we have good reasons and we have constant trouble with certain resources and these resources are ephemeral, we may decide to delete them. Again, that's not the main topic in my comment.

My comment is about:
1.) Make the grace period configurable.
2.) Then go on to delete the cluster without the control plane and here we need to take care of the LBs. We do that already on AWS and GCP, because of the service resource finalizer mess in previous K8s versions. On Azure it's covered implicitly by the resource group. Only on Alicloud and OpenStack we have nothing and need to add code. Then of course we need to make MCM and GRM independent of/ignore the control plane.
3.) Implement code to just drop/forget a cluster on our end and leave everything else to the end user. Maybe the user has first to delete the cluster before this option becomes available to her. Maybe, now or later (proposal by @rfranzke), we show a list of "our" resources, but I wouldn't make it a prerequisite already.

**Comment by vlerenc** [comment]
We discussed and decided that we want to do the following:

1. Offer "Drop Cluster" functionality (formerly called "purge" but that seems misleading), first programmatically but then also in the Dashboard (cc @grolu; with proper warnings/disclaimers, that this will drop/forget about the cluster only on Gardener side and that the end user has to confirm, "sign with blood", and take care of resources in her end user account/subscription/project/tenant).
2. Expose the means to influence the grace period when deleting a cluster, first programmatically but then also in the Dashboard (cc @grolu), so that people start to learn, that they don't have to wait for ages, but that what seems like a "hanging cluster deletion" is actually something they can influence (and usually cause).
3. Forceful deletion that doesn't require a running control plane (or hibernated cluster to be woken up), that will forcefully delete all resources created by the deployed controllers (e.g. LBs with the right tags, but not other LBs, never/no volumes, as they would anyhow not block cluster deletion and we couldn't anyhow retrieve the `reclaim policy` without a running control plane) and our Gardener infrastructure extension, but not other (end-user-created) resources. Again, first programmatically but then also in the Dashboard (cc @grolu; maybe as part of the regular deletion dialog, besides the grace period, much like with pods, approving forceful deletion after the grace period has lapsed, with the necessary warnings and fine-print, e.g. in regards to the volumes that won't be deleted).
4. Improving the Gardener error messages in case of "infrastructure dependencies" blocking cluster deletion, most importantly if due to timeouts the TF job didn't complete, but also by invocation of IaaS SDKs/APIs identifying which resources block the deletion (not necessary all resources, if that is too much effort, but at least the most likely culprits like NICs that would block VPC deletion).

/cc @timebertt @mvladev @vpnachev @rfranzke @timuthy @dguendisch @prashanth26 @dkistner @ialidzhikov

**Comment by pbochynski** [comment]
Just wanted to say that the use case is simple. I don't want to clean the cluster by deleting each and every resource gracefully if I am going to throw it away completely. It is not rocket science to write such a clean-up script, but in my case, it is just a waste of time. I am not talking about time to write the script, but time to execute it with every test run. Thousands of executions per month multiplied by 5 minutes - I could have one cluster for free. Programmatic forceful deletion is what I need, but don't see any reason to not expose it in the dashboard (with triple confirmation ;-)

**Comment by stoyanr** [comment]
After a long pause we are discussing this topic again, see #5173, and there is also an implementation proposed with #5150, so far only for the "forceful restoration" case, that could later be adapted to the "forceful deletion" (called "purge" or "drop cluster" here, see the first point in https://github.com/gardener/gardener/issues/3110#issuecomment-738745082).

**Comment by rfranzke** [comment]
After a long break, we had another meeting about this issue with @acumino @ary1992 @shafeeqes @vlerenc since we finally want to pick it up and get it done. This is the summary:

- The initial request of @pbochynski (making Gardener skip graceful deletion of Kubernetes resources) has already been implemented in the meantime, see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_cleanup.md for details. It's just not integrated into the dashboard (yet? cc @grolu @petersutter @holgerkoser), but possible to be used programmatically.
- Regarding the most recent plan in https://github.com/gardener/gardener/issues/3110#issuecomment-738745082:
  - `2.` is already implemented as just mentioned.
  - `3.` is something we will not do for now since it's highly infrastructure specific (high effort to implement and maintain) - i.e., we will not get into the business of (force-)deleting IaaS resources in the customer/user accounts. This is their responsibility to cleanup as follow-up task after their clusters were purged.
  - `4.` is something that might improve over time now that @kon-angelo and @MartinWeindel are switching the provider extensions from Terraform to native Golang SDKs for infrastructure mangement.
- Hence, `1`. is the only item that remains and that we now want to actively pursue ("drop/purge cluster" functionality).
- We plan to add a new annotation `confirmation.gardener.cloud/force-deletion=true` that controls this functionality (ref "sign with 🩸" from previous comments 😉). It may only be set for `Shoot`s which have a `deletionTimestamp` and an [user error code](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_status.md#error-codes), i.e. only for `Shoot`s for which regular/graceful deletion already failed.
- This prevents that people already add this annotation before or even during cluster creation.
- We discussed also whether want to enforce that a certain amount of time passed before setting this annotation is allowed ("only allow after graceful deletion has failed for a day"), but we decided against it - above condition seems good enough for now.
- Concerns were raised that we should allow users to get to the infrastructure status such that they know which IaaS resources they have to cleanup manually. This is a feature request that @kon-angelo wants to work on anyways and independently of this issue. In the past, we were already starting but never finishing it (see https://github.com/gardener/gardener/issues/3873). @shafeeqes @ary1992 @acumino will approach @kon-angelo to sync about it (pls create a new issue) and potentially collaborate/support.

**Comment by acumino** [comment]
## Tasks

### Gardener:

- [ ] Adapt gardener to allow forceful deletion of shoot
     - Add annotation `confirmation.gardener.cloud/force-deletion` which allows force deletion of the shoot.
     - Allow deletion of the shoot only if the below condition satisfies - 
       - Shoot already has a deletion timestamp.
       - Shoot has an ErrorCode present in status.
     - Adapt shoot deletion flow for forceful deletion.

### Extensions:
There are resources(e.g. - `Machine`, `MachineSet` etc.) for which Gardenlet doesn't have deletion access and we also don't want to allow that permission just for supporting forceful deletion other than that there are resources that are deployed by provider-extensions about which gardener doesn't have any knowledge. 
In case of forceful deletion provider extension should take care of the above responsibility.
  - [ ] provider-alicloud ,  released with [`?`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/?)
  - [ ] provider-aws ,  released with [`?`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/?)
  - [ ] provider-azure , released with [`?`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/?)
  - [ ] provider-gcp , released with [`?`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/?)
  - [ ] provider-openstack , released with [`?`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/?)
  - [ ] provider-vsphere , released with [`?`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/?)
  - [ ] provider-equinix-metal , released with [`?`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/?)

**Comment by rfranzke** [comment]
> There are resources(e.g. - Machine, MachineSet etc.) for which Gardenlet doesn't have deletion access and we also don't want to allow that permission just for supporting forceful deletion 

Now with #7594, I think we can certainly allow `gardenlet` access to the other resources in the `machine.sapcloud.io` API to make it a bit easier (at least for this part).

> other than that there are resources that are deployed by provider-extensions about which gardener doesn't have any knowledge.

OK, sure, for those the provider extensions need to take care.

**Comment by acumino** [comment]
All the mentioned tasks in https://github.com/gardener/gardener/issues/3110#issuecomment-1705500823 have been completed.
/close
