### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#32]
# Stories
* As user I want to utilise GPUs if available, so that I can implement GPU-relevant applications like ML.

# Motivation
See above.

# Acceptance Criteria
- [ ] Users can require nodes with GPUs
- [ ] The GPU is actually available to (non-privileged) containers
- [ ] CUDA usage for ML is possible

# Open Questions
- [ ] While CPUs are well compressible, how about GPUs (shader cores)?
- [ ] How do we provision the drivers into the kops-managed nodes (AMI image is fixed, no means yet to apply direct changes through kops, so would daemon sets help)?

# Resources
- [ ] https://vishh.github.io/docs/user-guide/gpus

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
Duplicate of https://github.com/gardener/gardener/issues/24.
