### ISSUE TITLE
☂️ Solution For Automated Shoot CA/Credentials Rotation

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#3292]
**How to categorize this issue?**

/area control-plane
/kind enhancement

**What would you like to be added**:
A documented and tested way to automatically manage and rotate Shoot CA credentials without downtime. One proposition would be to use the cert-manager.io project for it as it is well integrated within the K8s Community. 
An integration with secure stores like Hashicorp Vault is certainly desirable and also already supported by Cert-Manager (https://cert-manager.io/docs/configuration/vault/) 

**Why is this needed**:
Currently the Gardenlet and Kubelet Client certificates get automatically rotated after 10 months to prevent them from expiration (12 months). 
For the Shoot Certificate Authority there is no such mechanism implemented at the moment and it's up to the cluster operator to manage this.  

CC: @timebertt @cypherfox @schmidtdu

<hr>

Copied from https://github.com/gardener/gardener/issues/3292#issuecomment-1036058890 and now maintained here:

Now that [GEP18](https://github.com/gardener/gardener/blob/master/docs/proposals/18-shoot-CA-rotation.md) got merged with https://github.com/gardener/gardener/pull/5395, we can start with the implementation.
Please note that the below list is continuously subject to change and can be extended or shrank based on the made experience during the implementation phase.

# Tasks

## Prerequisites

- Add feature gate and trigger annotations, extend `ShootStatus` API
  - [x] https://github.com/gardener/gardener/pull/5449
  - [x] https://github.com/gardener/gardener/pull/5595
- Make sure that all control plane and system components restart in case the CA bundle changes
  - ~https://github.com/gardener/gardener/pull/5459~, closed due to https://github.com/gardener/gardener/issues/3292#issuecomment-1042984874
- [x] Introduce a new secrets manager supporting rotation scenarios https://github.com/gardener/gardener/pull/5503
  - Adapt `gardener/gardener` component (use new secrets manager)
    - [x] https://github.com/gardener/gardener/pull/5503
    - [x] https://github.com/gardener/gardener/pull/5510
    - [x] https://github.com/gardener/gardener/pull/5524
    - [x] https://github.com/gardener/gardener/pull/5583
    - [x] https://github.com/gardener/gardener/pull/5608
    - [x] https://github.com/gardener/gardener/pull/5616
    - [x] https://github.com/gardener/gardener/pull/5668
    - [x] https://github.com/gardener/gardener/pull/5688
    - [x] https://github.com/gardener/gardener/pull/5671
    - [x] https://github.com/gardener/gardener/pull/5656
    - [x] https://github.com/gardener/gardener/pull/5669
    - [x] https://github.com/gardener/gardener/pull/5673
    - [x] https://github.com/gardener/gardener/pull/5662
    - [x] https://github.com/gardener/gardener/pull/5629
    - [x] https://github.com/gardener/gardener/pull/5661
    - [x] https://github.com/gardener/gardener/pull/5682
    - [x] https://github.com/gardener/gardener/pull/5664
    - [x] ~Adapt `dependency-watchdog-{internal,external}-probe` client secrets (removed entirely with https://github.com/gardener/gardener/pull/5685)~
    - [x] https://github.com/gardener/gardener/pull/5691
    - [x] https://github.com/gardener/gardener/pull/5745
    - [x] https://github.com/gardener/gardener/pull/5790
    - [x] https://github.com/gardener/gardener/pull/5679
    - Adapt seed controller (creates a CA and other credentials for the seed)
      - [x] https://github.com/gardener/gardener/pull/5655
      - [x] https://github.com/gardener/gardener/pull/5669
      - [x] https://github.com/gardener/gardener/pull/5745
      - [x] https://github.com/gardener/gardener/pull/5686
      - [x] https://github.com/gardener/gardener/pull/5806
  - Revendor/Adapt Gardener extension components (use new secrets manager for generation, generate dedicated CAs, adapt usage of generic token kubeconfig)
    - [x] https://github.com/gardener/gardener/pull/5607
    - [x] https://github.com/gardener/gardener/pull/5666
    - [x] https://github.com/gardener/gardener/pull/5803
    - [x] `shoot-cert-service`: https://github.com/gardener/gardener-extension-shoot-cert-service/pull/113, released with [`v1.21.0`](https://github.com/gardener/gardener-extension-shoot-cert-service/releases/tag/v1.21.0)
    - [x] `shoot-dns-service`: https://github.com/gardener/gardener-extension-shoot-dns-service/pull/122, released with [`v1.19.0`](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.19.0)
    - [x] `shoot-oidc-service`: https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/41, released with [`v0.6.0`](https://github.com/gardener/gardener-extension-shoot-oidc-service/releases/tag/v0.6.0)
    - [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/475, released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.36.0)
    - [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/538, released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.36.0)
    - [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/493, released with [`v1.28.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.28.0)
    - [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/434, released with [`v1.23.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.23.0)
    - [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/443, released with [`v1.26.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.26.0)
    - [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/230, released with [`v0.13.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.13.0)
    - [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/209, released with [`v2.3.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.3.0)
    - [x] `auditlog-extension`, released with `v0.45.0`
  - Adapt other components
    - [x] `gardenlogin-controller-manager` (adapt to new CA data type in `ShootState` in garden): https://github.com/gardener/gardenlogin-controller-manager/pull/24
    - [x] `dashboard` (reading monitoring ingress credentials from `Secret` in seed): https://github.com/gardener/dashboard/pull/1178
    - [x] `etcd-custom-image`: https://github.com/gardener/etcd-custom-image/pull/10
    - `etcd-druid`
      - [x] https://github.com/gardener/etcd-druid/pull/309
      - [x] https://github.com/gardener/etcd-druid/pull/310
      - [x] https://github.com/gardener/gardener/pull/5693
  - [x] https://github.com/gardener/gardener/pull/5612
    - [Not strictly necessary/optional improvement] Adapt `gardenlogin-controller-manager` to use dedicated secret (instead of reading shoot CA data from `ShootState` in garden) or drop it entirely
    - [x] `landscape-setup` (adapt `roles-seed` to use dedicated secret instead of reading shoot CA data from `ShootState` in garden for OIDC kubeconfigs)

## Shoot CA Rotation Business Logic

- [x] https://github.com/gardener/gardener/pull/5774 (Support rolling update scenario for local shoots to re-enable e2e tests for CA rotation after #5666)
- [x] https://github.com/gardener/gardener/pull/5779
- [x] https://github.com/gardener/gardener/pull/5785
- [x] https://github.com/gardener/gardener/pull/5807
- [x] https://github.com/gardener/gardener/pull/5897
- [x] https://github.com/gardener/gardener/pull/5944
- [x] https://github.com/gardener/gardener/pull/5945
- [x] https://github.com/gardener/gardener/pull/6099
- [x] https://github.com/gardener/gardener/pull/6784
- [x] https://github.com/gardener/gardener/pull/7047

## Extension Webhook Server CA Rotation

- [x] https://github.com/gardener/gardener/pull/6003
- [x] https://github.com/gardener/gardener/pull/6060
- Revendor/Adapt extensions
  - [x] ~[`kupid`](https://github.com/gardener/kupid/blob/6312b00a767b1c24ec7700c8ea31b1b813855012/main.go#L182-L193)~ (not considered since `kupid` is considered deprecated and should be replaced with https://github.com/gardener/kupid/issues/33)
  - [x] `networking-cilium`: https://github.com/gardener/gardener-extension-networking-cilium/pull/92
  - [x] `shoot-oidc-service`: https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/44, released with [`v0.8.0`](https://github.com/gardener/gardener-extension-shoot-oidc-service/releases/tag/v0.8.0)
  - [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/492, released with [`v1.37.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.37.0)
  - [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/556, released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.36.0)
  - [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/513, released with [`v1.28.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.28.0)
  - [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/446, released with [`v1.23.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.23.0)
  - [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/455, released with [`v1.26.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.26.0)
  - [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/241, released with [`v0.14.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.14.0)
  - [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/212, released with [`v2.4.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.4.0)

## Related Tasks

- `ServiceAccount` Signing Key Rotation
  - [x] https://github.com/gardener/gardener/pull/5968
  - Revendor/Adapt extensions
    - [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/492, released with [`v1.37.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.37.0)
    - [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/556, released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.36.0)
    - [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/513, released with [`v1.28.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.28.0)
    - [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/446, released with [`v1.23.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.23.0)
    - [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/455, released with [`v1.26.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.26.0)
    - [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/241, released with [`v0.14.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.14.0)
    - [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/212, released with [`v2.4.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.4.0)
  - [x] https://github.com/gardener/gardener/pull/6063
  - [x] https://github.com/gardener/gardener/pull/6078
- ETCD Encryption Key Rotation
  - [x] https://github.com/gardener/gardener/pull/6021
  - [x] https://github.com/gardener/gardener/pull/6064
  - [x] https://github.com/gardener/gardener/pull/6065
- [x] https://github.com/gardener/gardener/pull/5926
- [x] https://github.com/gardener/gardener/pull/6038
- [x] https://github.com/gardener/gardener/pull/6039
- [x] https://github.com/gardener/gardener/pull/6148

## Rollout

- [x] https://github.com/gardener/gardener/pull/5939
- Testing
  - [x] https://github.com/gardener/gardener/pull/6072
  - Advanced checks for credentials e2e test
    - [x] https://github.com/gardener/gardener/pull/6098
    - [x] https://github.com/gardener/gardener/pull/6112
  - [x] https://github.com/gardener/gardener/issues/5895
  - [x] https://github.com/gardener/gardener/issues/6081
  - [x] https://github.com/gardener/gardener/issues/6092
  - [x] Perform a few e2e smoke tests on real landscapes
- [x] https://github.com/gardener/gardener/pull/6079
- [x] https://github.com/gardener/gardener/pull/6110
- [x] https://github.com/gardener/gardener/pull/6149

## Future Tasks

- Drop code related to migration and cleanup (annotated with `TODO(rfranzke):`)
  - https://github.com/gardener/gardener/pull/6891
  - https://github.com/gardener/gardener/pull/6929
  - Cleanup of legacy ETCD encryption and ServiceAccount token signing key secret
- Promote feature gates
  - https://github.com/gardener/gardener/pull/6252
  - https://github.com/gardener/gardener/pull/6734
  - https://github.com/gardener/gardener/pull/6930

**Comment by schmidtdu** [comment]
adding @dergeberl @mganter @einfachnuralex

**Comment by christianhuening** [comment]
adding @alesti

**Comment by christianhuening** [comment]
addin @iss0

**Comment by timebertt** [comment]
Ok, I see 3 (more or less) distinct topics touched here:

1. rotation of the Shoot root CA
- I have listed some steps that are necessary for doing this gracefully, can add them here
- This should probably be automated somehow via some annotation similar to the [kubeconfig rotation feature](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials)
2. rotation of the Garden cluster CA
- not sure, if we can do something about it here, because the garden CA is supplied by the landscape administrator
- I think, this might rather be a feature requests either for garden-setup or for the gardener control plane [landscaper](https://github.com/gardener/landscaper) component, though nobody has started working on it yet (cc @schrodit)
- Maybe some adaption in gardeners components will be needed to do that gracefully, though I guess, this is only the minor part
3. using cert-manager to generate certificates (and storing them in vault)
- not sure, how cert-manager comes into play here, as the gardenlet already has all the logic for generating the necessary certificates/secrets/... for a given Shoot cluster
- so if a given secret (e.g. root CA) is deleted from the Seed and ShootState, gardener will automatically regenerate it, so no need for an extra component/dependency

**Comment by timebertt** [comment]
Can you guys also outline, what you have already been investigating in / working on / what you would like to implement from the this list?

**Comment by cypherfox** [comment]
> Ok, I see 3 (more or less) distinct topics touched here:
> 
> 1. rotation of the Shoot root CA
> 
> 
>     * I have listed some steps that are necessary for doing this gracefully, can add them here

Please do. I also think we need a diagram that shows *ALL* certs that we are talking about here. Otherwise, misunderstanding is guaranteed.

> 
> 1. rotation of the Garden cluster CA
> 
>     * I think, this might rather be a feature requests either for garden-setup or for the gardener control plane [landscaper](https://github.com/gardener/landscaper) component, though nobody has started working on it yet (cc @schrodit)
> 
>     * Maybe some adaption in gardeners components will be needed to do that gracefully, though I guess, this is only the minor part

I doubt that this is minor, as all other trust derives from that. Unless the root of the chains for the Shoots can be injected independently from the Gardener (see below).
> 
> 
> 1. using cert-manager to generate certificates (and storing them in vault)

We would like to generate and maintain those root CAs with Vault, that are not generated by a subsystem (e.g. Gardener, Kubernetes, Linkerd) internally. If the certs are *completely* maintained internally, this cert-manager is not relevant.

> 
> 
>    * not sure, how cert-manager comes into play here, as the gardenlet already has all the logic for generating the necessary certificates/secrets/... for a given Shoot cluster

Does the gardenlet contain logic for cert *rotation* as well as initial generation? We have run with Linkerd in a similar problem, that in large, high churn cluster, simple cert replacement is almost guaranteed to cause a downtime due to a cascading communication failures.

Also I do not trust cert handling implementations to correctly handle cert bundles and chains longer than 2 steps . I have been bitten too often. We need a specific test for that.

> 
>    * so if a given secret (e.g. root CA) is deleted from the Seed and ShootState, gardener will automatically regenerate it, so no need for an extra component/dependency

Again, if the key within that secret is also regenerated, it basically needs a chain rotation, and the same as above applies. Otherwise a downtime will be the result.

**Comment by timebertt** [comment]
Ok, I already sense some misunderstanding here. So let me try to clarify :)


> I doubt that this is minor, as all other trust derives from that. Unless the root of the chains for the Shoots can be injected independently from the Gardener (see below).

Actually, the Shoots' root CA (CN `kubernetes`) is self-signed and is not related to the CA of the garden cluster in any way (which is good, you already outlined some disadvantages of such an approach).


> We would like to generate and maintain those root CAs with Vault, that are not generated by a subsystem (e.g. Gardener, Kubernetes, Linkerd) internally. If the certs are _completely_ maintained internally, this cert-manager is not relevant.

Not sure, if I get this point. The Shoots' CAs are generated and "maintained" by the gardenlet. Would that fit to your understanding of a "subsystem"? Or is your concern, that it is not maintained "internally" because it materializes in a Secret on the Seed cluster?

> Does the gardenlet contain logic for cert _rotation_ as well as initial generation? We have run with Linkerd in a similar problem, that in large, high churn cluster, simple cert replacement is almost guaranteed to cause a downtime due to a cascading communication failures.

No, the gardenlet has no dedicated logic for the cert rotation, yet. And yes, the replacement is no option for productive clusters, that's why we would need such a feature. That's exactly what I meant with my first point 👍 


> Again, if the key within that secret is also regenerated, it basically needs a chain rotation, and the same as above applies. Otherwise a downtime will be the result.

Exactly, that would need to be respected when implementing the Shoot CA rotation feature.

**Comment by timebertt** [comment]
Here are some of my personal notes of what needs to be done, when manually rotating a Shoot CA (@rfranzke @mvladev please add, if I missed something):

```
procedure
  - much like https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/
  - save all secrets of the Shoot
  - generate new CA (or take one from a local shoot cluster)
  - create a CA secret containing both old and new CA
  - update kube-controller-manager, kube-scheduler and kube-proxy kubeconfigs to trust both CAs
  - Scale down all other controllers in shoot namespace (ccm, mcm, dns and cert controller, vpa components)
  - skip step to update ServiceAccount tokens (kcm already updates them)
  - restart all pods, which use either a service account or a client certificate (e.g. kube-proxy, calico-node; if shooted seed: gardenlet, extension controllers, controllers in control plane, ...)
  - go to all nodes and
    - update the cloud-config-downloader script to trust both CAs
    - delete the `/var/lib/kubelet/kubeconfig-real` file and `/var/lib/kublet/pki` dir
    - restart the `cloud-config-downloader` systemd unit
    - -> will re-bootstrap kubelet (create CSR, obtain new valid certificate and create new kubeconfig trusting both CAs)
  - patch all secrets signed by shoot cluster root CA out of ShootState and update root CA in ShootState
  - delete ca secret and all secrets signed by it from the Seed
  - trigger a Shoot reconciliation
    - will regenerate all the secrets and sign them using the new CA
    - will also roll the kube-apiserver and reject all client-certificates that were signed by old CA
problems with the approach
  - vpa isn't available and some pods may get OOMKilled -> needs manual scaling until vpa is scaled up again
  - all nodes need to be touched or rolled
```

This can probably be used to derive some concrete steps when implementing automation for this.

**Comment by cypherfox** [comment]
> Actually, the Shoots' root CA (CN `kubernetes`) is self-signed and is not related to the CA of the garden cluster in any way 

:+1: 

>(which is good, you already outlined some disadvantages of such an approach).
> 
> > We would like to generate and maintain those root CAs with Vault, that are not generated by a subsystem (e.g. Gardener, Kubernetes, Linkerd) internally. If the certs are _completely_ maintained internally, this cert-manager is not relevant.
> 
> Not sure, if I get this point. The Shoots' CAs are generated and "maintained" by the gardenlet. Would that fit to your understanding of a "subsystem"? Or is your concern, that it is not maintained "internally" because it materializes in a Secret on the Seed cluster?
> 
No, Shoot secrets in the Seed are fine (exception see below).  For this I would define a "subsystem" as a set of containers/processes that are communicating via TLS, trusted by certs from the same cert tree -> trust the same CA certs.  A container may be part of multiple subsystems at the same time.

These "subsystems" usually eventually come to a point where the manual states: "...and the admin injects the secret here...", resulting in the the need for a) the admin would in theory know the contents of the secret and b) require manual steps.

But I am wondering about the CA rotation of the Seed! (and thus, when talking about a shooted Seed, we are back to square one, I guess) And that is where the external root-key management comes in: when storing the secret in the next higher (Shoot -> Seed, Seed -> Garden) is not an option, can we store it somewhere else?

**Comment by mganter** [comment]
> But I am wondering about the CA rotation of the Seed! (and thus, when talking about a shooted Seed, we are back to square one, I guess) And that is where the external root-key management comes in: when storing the secret in the next higher (Shoot -> Seed, Seed -> Garden) is not an option, can we store it somewhere else?

I can't really see the difference between a Shoot and a Seed rotation. If you have a shooted seed, you can abstract the workload inside the shooted seed as shoot workload, so there shouldn't be any difference. You need to roll all secrets related to the shoot and that should do it, right?


> Here are some of my personal notes of what needs to be done, when manually rotating a Shoot CA (@rfranzke @mvladev please add, if I missed something):
> 
> ```
> procedure
>   - much like https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/
>   - save all secrets of the Shoot
>   - generate new CA (or take one from a local shoot cluster)
>   - create a CA secret containing both old and new CA
>   - update kube-controller-manager, kube-scheduler and kube-proxy kubeconfigs to trust both CAs
>   - Scale down all other controllers in shoot namespace (ccm, mcm, dns and cert controller, vpa components)
>   - skip step to update ServiceAccount tokens (kcm already updates them)
>   - restart all pods, which use either a service account or a client certificate (e.g. kube-proxy, calico-node; if shooted seed: gardenlet, extension controllers, controllers in control plane, ...)
>   - go to all nodes and
>     - update the cloud-config-downloader script to trust both CAs
>     - delete the `/var/lib/kubelet/kubeconfig-real` file and `/var/lib/kublet/pki` dir
>     - restart the `cloud-config-downloader` systemd unit
>     - -> will re-bootstrap kubelet (create CSR, obtain new valid certificate and create new kubeconfig trusting both CAs)
>   - patch all secrets signed by shoot cluster root CA out of ShootState and update root CA in ShootState
>   - delete ca secret and all secrets signed by it from the Seed
>   - trigger a Shoot reconciliation
>     - will regenerate all the secrets and sign them using the new CA
>     - will also roll the kube-apiserver and reject all client-certificates that were signed by old CA
> problems with the approach
>   - vpa isn't available and some pods may get OOMKilled -> needs manual scaling until vpa is scaled up again
>   - all nodes need to be touched or rolled
> ```
> 
> This can probably be used to derive some concrete steps when implementing automation for this.

This solution seems very promising. 
Actually we have problems that the VPA is killing our pods with OOMKilled without scaling the resources up again :P

**Comment by christianhuening** [comment]
We had a call today to discuss the topics discussed here. It became apparent, that we basically deal with three topics:
1. Shoot CA rotation & automation
2. Garden Base Cluster CA management & rotation
3. (where applicable) Support for Hashicorp Vault for secure storage of secrets 

I changed the title of this ticket to focus on the Shoot CA rotation. Bascially we agreed it boils down to implement/automate the rotation procedure as described above by @timebertt 

For topic 2 I will create a separat ticket

**Comment by timebertt** [comment]
Great, seems like we're on the same page, then. Your list resembles my list very much :)
Yes, let's first discuss the Shoot CA rotation here and keep the other topics separated and discuss them in dedicated issues.

What would be the next steps on this issue, then?
I think, this would make a great first PR :)
Anyone interested in pulling this off?

**Comment by cypherfox** [comment]
@timebertt I am wondering about how to implement the rotation component (starting with the Shoot CA). Did you envision this as a tool to be run by some admin, or as an extension that checks the remaining validity of the CA cert and then swings into action?

**Comment by timebertt** [comment]
I would teach gardener to automate it, similar to the kubeconfig rotation, as metioned above:

> 1. rotation of the Shoot root CA
> 
> * This should probably be automated somehow via some annotation similar to the [kubeconfig rotation feature](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials)

So at first, operators and endusers can trigger the automation via the new annotation. And maybe later on, gardener-controller-manager could be instructed to do it automatically when approaching the end of a CA's validity

**Comment by christianhuening** [comment]
We had an initial meeting (THX @timebertt ) where a number of notes were taken:

Notes from SAP Meeting:
- Hint is towards the rotate kubeconfig credentials as it is relatively similar as to what we want to achieve: https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials
- Shoot Controller is here: https://github.com/gardener/gardener/tree/master/pkg/gardenlet/controller/shoot 
- There are some small places in the code where a Shoot and a Shooted Seed are handled differently. Those need to be treated with extra care to ensure rotation works in both cases.
- currently all state for a Shoot is saved in the shootstate CRD, which could be reused in the first step to save all secret of the Shoot.
- Suggestion is to duplicate the ShootState as a Backup
- Code to generate CA for a Shoot: https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/secrets.go#L44
- The node rollout should be done 2 times:
- - First time to update kubelet and everything with the new CA bundle
- - (Optional) A second time to remove the old CA
- | - update the cloud-config-downloader script to trust both CAs
- This part might already be covered by the following PR: https://github.com/gardener/gardener/pull/3449

**Comment by timebertt** [comment]
One additional note from my side:
- We might want to have some metrics / dashboards showing the expiration date of the Shoot CA (ref https://github.com/gardener/gardener/issues/3453)

**Comment by cypherfox** [comment]
> One additional note from my side:
> 
>     * We might want to have some metrics / dashboards showing the expiration date of the Shoot CA (will open a dedicated issue for that)

For simplicity sake, IMHO it should expose the validity of any and all certs that it knows about.

**Comment by rfranzke** [comment]
Now that [GEP18](https://github.com/gardener/gardener/blob/master/docs/proposals/18-shoot-CA-rotation.md) got merged with https://github.com/gardener/gardener/pull/5395, we can start with the implementation.
Please note that the below list is continuously subject to change and can be extended or shrank based on the made experience during the implementation phase.

# Tasks

_This got copied into the issue description itself, see https://github.com/gardener/gardener/issues/3292#issue-762236864._

**Comment by rfranzke** [comment]
After https://github.com/gardener/gardener/pull/5459, I was not too happy with the manual injection of the checksums since this can easily lead to issues when it is forgotten or done wrongly. The same needs to be done for the extensions and it is generally quite fragile.

In a discussion with @timebertt, we agreed on closing this PR and rather rework the entire secret generation in `gardener/gardener`.
Concretely, we want to work with immutable `Secret`s with unique names. This way, we don’t need any checksum annotations since the `Secret`s would have unique names, i.e., referencing a different `Secret` triggers a rolling update.
Additionally, we would like to introduce a new `SecretsManager` concept in preparation for the multiple CAs, CA bundles, etc. later on such that it’s easy for components to consume the right secret while encapsulating the related logic in this `SecretsManager` instead of replicating it to each component.
We are also thinking about combining this with a webhook in GRM for auto-replacing secret names in volumes with the unique names of the secrets, similar to the `projectedtokenmount` webhook. This way, extensions would not need to care about the CA rotation at all.

Along the way, we envision cleaning up a few things regarding today’s central secret management, so the full motivation for doing this now is:

- Get rid of duplicated `ca.crt` key in secrets data
- Scalability:
    - Immutable `Secret`s/`ConfigMap`s are not watched by kubelet
    - No need to persist such secrets in `ShootState` 
- Move secret generation to components (ref #2754)
- Prevent programmer-level errors when checksums annotations are forgotten to inject
- Refactoring of complicated and legacy central secret generation is anyways overdue (this coding is one of the oldest in this repository and building rotation on top of the existing implementation will just create new technical debt)

**Comment by rfranzke** [comment]
All related tasks have been completed.
/close

**Comment by vlerenc** [comment]
Awesome!

**Comment by christianhuening** [comment]
Truly Amazing! Thanks a ton!

**Comment by cypherfox** [comment]
Outstanding!
