### ISSUE TITLE
Multi-Cloud

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#4]
# Stories
* As provider I want to provision on AWS, Azure, GCP and OpenStack, so that Kubernetes runs in the Public Hyper-Scale Clouds where our customers already have their footprint.

# Motivation
We shall go where our customers are, i.e. multi-cloud and also our own DCs. We shall offer this in an operator-friendly way with simplified operations.

# Acceptance Criteria
Clusters can be created, operated and destroyed (following the seed & shoot cluster approach):
- [x] Kubernetes on AWS (covering the same functionality as our kops-based solution)
- [x] Kubernetes on Azure to (almost) the same extent as we have it on AWS
- [x] Kubernetes on GCP to (almost) the same extent as we have it on AWS
- [x] Kubernetes on OpenStack to (almost) the same extent as we have it on AWS

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vasu1124](https://github.com/vasu1124)**
_Wednesday Jul 19, 2017 at 19:30 GMT_

----

I found some interesting insights on kubeadm here: https://kubernetes.io/docs/admin/kubeadm/ .
e.g. kubeadm v1.7 has a feature to auto-approve new nodes, which can be turned off; see section "Securing your installation even more"

I was wondering if we could enable BYO bare metal system by integrating kubeadm and pointing users to use kubeadm join.
pro: 
- we delegate the setup to the cluster user/admin
- OS etc. is user responsibility. he can choose BM or VM.
- we point to official kubeadm join documentation and be done with it

cons: 
- all kinds of edge scenarios (especially wrt network) will land on our heads
- wont work in many cases with cloud provider setup. LBaaS, Storage etc. unless BM is setup with narrow bounds

Alternatively, we could do something similar like kubeadm join, for manual setups of BM in the data center for permitted use cases by our engineering teams only.

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vasu1124](https://github.com/vasu1124)**
_Wednesday Jul 26, 2017 at 10:02 GMT_

----

Test clear containers with kubernetes: https://github.com/01org/cc-oci-runtime/wiki/Clear-Containers-and-Kubernetes
