### ISSUE TITLE
Support Kubernetes 1.12

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#400]
[Kubernetes v1.12](https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0) has been released (see [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#v1120)).
We should take a look into what has changed and implement support for 1.12 in Gardener.

# TODOs

## Standard tasks
- [x] Update Go libraries to `kubernetes-1.12.1`
  - [x] `Added --authorization-always-allow-paths to components doing delegated authorization to exclude certain HTTP paths like /healthz from authorization.` -> Do we need it?
- [x] Update https://github.com/gardener/gardener/blob/master/docs/usage/supported_k8s_versions.md

## Version-specific tasks  (identified from the [1.12 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md))
- [x] Update `CloudProfile` and `Shoot` example manifests 
- [x] Server certificates
  - [x] Use `ca` secret to generate another server certificate for the kube-controller-manager (maybe also for K8s versions < 1.12?) and configure it `--tls-cert-file` or `--tls-private-key-file` -> Do the other components also need a server certificate?
  - [x] Secure serving on port 10258 to cloud-controller-manager (configurable via --secure-port) is now enabled. Delegated authentication and authorization are to be configured using the same flags as for aggregated API servers. Without configuration, the secure port will only allow access to /healthz
- :x: ~`When using --enable-admission-plugins the Priority admission plugin is now enabled by default (matching changes in 1.11.1+). If using --admission-control to fully specify the set of admission plugins, it is now necessary to add the Priority admission plugin for the PodPriority feature to work properly.` -> Remove the `Priority` admission plugin for Kubernetes 1.12.~
  - Won't do due to unneeded complexity in the code. We specify other default-enabled admission plugins anyways.
- [x] `'KubeSchedulerConfiguration' which used to be under GroupVersion 'componentconfig/v1alpha1', is now under 'kubescheduler.config.k8s.io/v1alpha1'.`
- [x] `The Azure load balancer idle connection timeout for services is now configurable.` -> We configure the idle timeout for AWS already, should we also configure it for Azure?
- [x] The audit.k8s.io api group has been upgraded from v1beta1 to v1.
- [x] Adapt HPA configuration options for 1.12 (see #399):
  - [x] `--horizontal-pod-autoscaler-downscale-delay` does not exist any longer in 1.12, hence, we should validate that it can only be used with versions <1.12
  - [x] `--horizontal-pod-autoscaler-upscale-delay` does not exist any longer in 1.12, hence, we should validate that it can only be used with versions <1.12
  - [x] `--horizontal-pod-autoscaler-downscale-stabilization` new flag in 1.12, defaults to `5m0s`: The period for which autoscaler will look backwards and not scale down below any recommendation it made during that period. -> we should validate that it can only be used with versions >=1.12
  - [x] `--horizontal-pod-autoscaler-initial-readiness-delay ` new flag in 1.12, defaults to `30s`:  The period after pod start during which readiness changes will be treated as initial readiness. -> we should validate that it can only be used with versions >=1.12
  - [x] `--horizontal-pod-autoscaler-cpu-initialization-period`, new flag in 1.12, defaults to `5m0s`: The period after pod start when CPU samples might be skipped. -> we should validate that it can only be used with versions >=1.12

# Test cases

- :white_check_mark: Reconcile old clusters in all versions (1.9, 1.10, 1.11) with this branch
- :white_check_mark: Create new clusters with versions < 1.12
- :white_check_mark: Create new clusters with version  = 1.12
- :white_check_mark: Upgrade old clusters from version 1.11 to version 1.12
- :white_check_mark: Delete clusters with versions < 1.12
- :white_check_mark: Delete clusters with version  = 1.12

**Comment by rfranzke** [comment]
FYI: I created the [`feature/kubernetes-1.12`](https://github.com/gardener/gardener/tree/feature/kubernetes-1.12) branch to which we can push our implementations.

**Comment by rfranzke** [comment]
@zanetworker the HPA PR (#399) is merged.
I have rebased the [`feature/kubernetes-1.12`](https://github.com/gardener/gardener/tree/feature/kubernetes-1.12) branch on the latest `master`.
Please start working on the two items assigned to you (see above).
