### ISSUE TITLE
Support profiling of gardener components

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4567]
**How to categorize this issue?**

/area dev-productivity ops-productivity
/kind enhancement

**What would you like to be added**:

Kubernetes components allow to enable profiling HTTP handlers (enabled by default).
As we reuse the API server library (`k8s.io/apiserver`) for gardener-apiserver, it already has profiling handlers (also enabled by default), see:
```
$ docker run eu.gcr.io/gardener-project/gardener/apiserver:v1.30.0 /gardener-apiserver --help | grep profiling
      --contention-profiling                                    Enable lock contention profiling, if profiling is enabled
      --profiling                                               Enable profiling via web interface host:port/debug/pprof/ (default true)
```

We should support enabling similar features for the rest of our components.

We can potentially reuse [`componentbaseconfigv1alpha1.DebuggingConfiguration`](https://github.com/kubernetes/component-base/blob/89c9a8654c518bf9d5c138213861fdc944f73617/config/v1alpha1/types.go#L59-L66) and include it in our component configs, similar to the [`KubeSchedulerConfig`](https://github.com/kubernetes/kube-scheduler/blob/2484e10e7f4dbff872d6244ab78303b410137586/config/v1beta2/types.go#L63-L65).
Probably we don't want to enable it by default right away.

Steps:

- [x] allow enabling profiling handlers to gardenlet: #4568
- [x] allow enabling profiling handlers to gardener-controller-manager: #4568
- [x] allow enabling profiling handlers to gardener-scheduler: #4568
- [x] allow enabling profiling handlers to gardener-admission-controller: #4568
- [x] allow enabling profiling handlers to gardener-seed-admission-controller: #5651
- [x] allow enabling profiling handlers to gardener-resource-manager: #5654 
- [x] document how enabling profiling handlers works: #4568
- ~enable profiling by default~
- ❓ enable TLS for profiling endpoints: https://github.com/gardener/gardener/issues/2829

**Why is this needed**:

Operators and developers might want to analyze runtime behavior of gardener components to further improve code and config.

**Comment by timebertt** [comment]
> allow enabling profiling handlers to gardener-seed-admission-controller

This is not done in https://github.com/gardener/gardener/pull/4568 as it's a rather minor component (as of now) and it doesn't have a component config like the other components.
Thus, we first might want to come up with a good way to make it configurable (maybe via the gardenlet config?).

**Comment by timebertt** [comment]
/unassign
for now. #4568 was merged, which concludes all planned steps as of now.

**Comment by ialidzhikov** [comment]
/assign
for gardener-seed-admission-controller

**Comment by rfranzke** [comment]
As discussed, we can probably
/close
this issue. The only remaining open task was to enable the profiling by default. However, there are several Kubernetes security best practices suggesting that profiling should not be enabled by default for the `kube-apiserver`, so it's probably a good idea to follow the same for our components.

From https://cloud.redhat.com/blog/12-kubernetes-configuration-best-practices:

> `--profiling` argument shows as `false`. Unless you’re experiencing bottlenecks or need to troubleshoot something that needs investigation, there’s no need for the profiler, and having it there unnecessarily opens you to exposure of system and program details.
