### ISSUE TITLE
Replace usage of static `ServiceAccount` tokens for components running in shoot talking to the shoot API server

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4660]
**How to categorize this issue?**

/area security
/kind enhancement
/priority 2

**What would you like to be added**:

Today, all of the components running in the shoot clusters and talking to the shoot's API server use a static `ServiceAccount` token ([example](https://github.com/gardener/gardener/blob/f5353762715d0aa5b3e5ded07f044cf431374193/pkg/operation/botanist/component/metricsserver/metrics_server.go#L146-L151)).

Instead, let's start using [projected `ServiceAccount` tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) supported since Kubernetes v1.12.

Concretely, we have to explicitly declare the volume in the `.spec.volumes[]` field of the `PodSpec`.
Additionally, we need to explicitly mount the data in the `.spec.containers[].volumeMounts[]` field where needed:

```yaml
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: some-serviceaccount
  volumes:
  - name: kube-api-access-gardener
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 600
          path: token
  containers:
  - name: foo
    volumeMounts:
    - name: kube-api-access-gardener
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
...
```

**Why is this needed**:

In order to eliminate static credentials requiring costly manual rotation which doesn't scale.
Projected `ServiceAccount` tokens can be configured with `expirationSeconds` and are regularly auto-rotated and re-mounted by the kubelet without further do.
Clients are expected to regularly reload the token, however, the `client-go` supports reloading them since `v9.0.0`, (see https://github.com/kubernetes/kubernetes/pull/67359), and most of the components are either already using this version or could be updated.

**Tasks**:

- Adapt `gardener/gardener` components
  - [x] https://github.com/gardener/gardener/pull/5099

- Adapt `gardener/gardener-extension-*` components
  - [x] `runtime-gvisor`: https://github.com/gardener/gardener-extension-runtime-gvisor/pull/32
  - [x] `networking-calico`: https://github.com/gardener/gardener-extension-networking-calico/pull/137
  - [x] `networking-cilium`: https://github.com/gardener/gardener-extension-networking-cilium/pull/76
  - [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/405
  - [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/467
  - [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/421
  - [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/368
  - [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/369
  - [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/192
  - [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/182
