### ISSUE TITLE
Replace usage of static client credentials for components running in seed talking to the shoot API server

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4661]
**How to categorize this issue?**

/area security
/kind enhancement
/priority 2

**What would you like to be added**:

Today, all of the components running in the seed clusters and talking to the shoot's API server use a kubeconfig with a static client certificate issued by the cluster's certificate authority ([example](https://github.com/gardener/gardener/blob/f5353762715d0aa5b3e5ded07f044cf431374193/pkg/operation/botanist/component/kubescheduler/kube_scheduler.go#L249-L256)).

Instead, let's start using similar concepts compared to [projected `ServiceAccount` tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) supported since Kubernetes v1.12.

Concretely, we have to use the [`TokenRequest`](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/#TokenRequestSpec) API of the shoot's API server to issue short-lived tokens for the respective components.
The tokens should be stored in dedicated `Secret`s in the shoot namespace in the seed cluster so that they can be mounted to the respective `Pod`s.
Similar to how the kubelet issues a new token when the lifetime reaches 80%, we should refresh such tokens regularly and update them in the respective `Secret`s in the seed.

This also allows us to use the same kubeconfig for all components which plays well together with what is proposed in #3598.
Also, it helps reducing the load of the Garden cluster since no client certificates/kubeconfigs would be generated anymore for such components, hence, reducing the size of the `ShootState` and also the size of the etcd backup.

For example, the following kubeconfig could be generated by gardenlet and stored in the `kubeconfig` `Secret` in the shoot namespace:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  namespace: shoot--foo--bar
type: Opaque
stringData:
  kubeconfig.yaml: |
    apiVersion: v1
    kind: Config
    current-context: shoot--foo--bar
    clusters:
    - cluster:
        server: https://kube-apiserver
      name: shoot--foo--bar
    contexts:
    - name: shoot--foo--bar
      context:
        user: shoot--foo--bar
        cluster: shoot--foo--bar
    users:
    - name: shoot--foo--bar
      user:
        tokenFile: /var/run/secrets/gardener.cloud/shoot/token
```

Also, let's say the short-lived token was stored in the `some-component-shoot-token` `Secret` in the shot namespace:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: some-component-shoot-token
  namespace: shoot--foo--bar
type: Opaque
stringData:
  token: some-token
```

Then the `PodSpec` would look as follows:

```yaml
apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: kubeconfig
    secret:
      secretName: kubeconfig
  - name: shoot-token
    secret:
      secretName: some-component-shoot-token
  containers:
  - name: foo
    volumeMounts:
    - name: kubeconfig
      mountPath: /var/run/secrets/gardener.cloud/kubeconfig
      readOnly: true
    - name: shoot-token
      mountPath: /var/run/secrets/gardener.cloud/shoot
      readOnly: true
    command:
    - /foo
    - --kubeconfig=/var/run/secrets/gardener.cloud/kubeconfig/kubeconfig.yaml
...
```

**Why is this needed**:

In order to eliminate static credentials requiring costly manual rotation which doesn't scale.
Projected `ServiceAccount` tokens can be configured with `expirationSeconds` and are regularly auto-rotated and re-mounted by the kubelet without further do.
Clients are expected to regularly reload the token, however, the `client-go` supports reloading the tokens specified in `tokenFile`s since `v10.0.0`, (see https://github.com/kubernetes/kubernetes/pull/70606), and most of the components are either already using this version or could be updated.

**Target Picture**:

_New in this picture is:_ Secret with short-lived token. Also the pod spec is adapted to mount the token and the component-kubeconfig points to the mounted `tokenFile`.
In the Shoot the ServiceAccount needs to be added and referenced by the existing rolebinding.

![target Picture](https://user-images.githubusercontent.com/7465180/135600979-8bfcd89b-c50a-4ed0-9162-44e793145a98.png)

**Open Questions**:
 - [x] Do all components support auto reloading tokens from disk -> Seems like yes supported in client-go since v1.13.0.
 - [x] Does the kubelet auto-remount secrets if the data of the secret changes -> yes
 - [x] Do we want to reuse a component for our controller (like the grm) or create a new component which includes this token functionality. -> we use the grm for now
 - [x] How is the controller itself authenticated against the KAPI?
 - [x]  Adapt all components running in the Seed targeting the Shoot to use a non-static token. 
 - [x] We create a significant amount of API requests on the Seed API server when updating tokens of all components in the Shoot namespaces upon token expiration. Will this have scaling performance implications on the Seed APIServer?
 - [x] How often do we want to rotate the tokens? What to choose for expiration time?
 - [x] A TokenRequest also includes an `audiences`. We are currently unsure what this [field](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/#TokenRequestSpec) does.

**Tasks**:
- Prepare `gardener-resource-manager`
  - [x] https://github.com/gardener/gardener/pull/4757
  - [x] https://github.com/gardener/gardener/pull/4817
  - [x] https://github.com/gardener/gardener/pull/4867
  - [x] https://github.com/gardener/gardener/pull/5084

- Adapt `gardener/gardener` components
  - [x] https://github.com/gardener/gardener/pull/4931
  - [x] https://github.com/gardener/gardener/pull/5007
  - [x] https://github.com/gardener/gardener/pull/5008
  - [x] https://github.com/gardener/gardener/pull/5009
  - [x] https://github.com/gardener/gardener/pull/5010
  - [x] https://github.com/gardener/gardener/pull/5012
  - [x] https://github.com/gardener/gardener/pull/5121
  - [x] https://github.com/gardener/gardener/pull/5138
  - [x] https://github.com/gardener/gardener/pull/5153
  - [x] https://github.com/gardener/gardener/pull/5685
  - [x] https://github.com/gardener/gardener/pull/5162
  - [x] https://github.com/gardener/gardener/pull/5163

- Adapt `gardener/gardener-extension-*` components
  - [x] `shoot-cert-service`: https://github.com/gardener/gardener-extension-shoot-cert-service/pull/103
  - [x] `shoot-dns-service`: https://github.com/gardener/gardener-extension-shoot-dns-service/pull/96
  - [x] `shoot-oidc-service`: https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/16
  - [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/405
  - [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/467
  - [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/421
  - [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/368
  - [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/369
  - [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/192
  - [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/182
  - [x] `external-dns-management`: https://github.com/gardener/external-dns-management/pull/237

**Comment by jia-jerry** [comment]
@rfranzke , I like this [pic](https://user-images.githubusercontent.com/7465180/135600979-8bfcd89b-c50a-4ed0-9162-44e793145a98.png) you drew because it help us understand how to rotate shoot kubeconfig token easily. Do you have plan to add this token rotation process in the gardener doc?

**Comment by rfranzke** [comment]
@jia-jerry There are already other, probably more detailed pics in the docs: https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#tokenrequestor
