### ISSUE TITLE
☂️ -Issue for switching to `Lease`s for leader election locks

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4742]
**How to categorize this issue?**

/area scalability
/kind enhancement
/priority 3

**What would you like to be added**:
Many components deployed in Gardener systems are still not using `Lease`s, however, since this is the new recommended default, let's switch to it to ensure our systems scale well.
Support for `endpoints` and `configmaps` is removed in K8s 1.24 with  https://github.com/kubernetes/kubernetes/pull/106852.
More details about the motivation to switch to leases - ref https://github.com/kubernetes/kubernetes/issues/80289.

Guidelines:
- To preserve the backwards-compatibility, resource lock for migration purposes (`endpointsleases`, `configmapsleases`) should be used when switching from the legacy resource locks (`endpoints`, `configmaps`).
- If the leader election resource lock is not configurable via flag, then let's also make it configurable (for example https://github.com/gardener/gardener-extension-provider-aws/pull/348).
- For the extensions case instead of adapting each and every provider extension to specify leader election flags for the MCM deployment, we can rather adapt the default resource lock used in the MCM.
- Consider RBAC adaptations if needed.

**List of components**:

Gardener:

- [x] [dependency-watchdog](https://github.com/gardener/dependency-watchdog) - v0.6.1 is using `endpoints` (@ary1992 )
  - https://github.com/gardener/dependency-watchdog/pull/37
  - Fixed with https://github.com/gardener/dependency-watchdog/pull/44
- [x] [etcd-druid](https://github.com/gardener/etcd-druid) - v0.7.1 is using `configmapsleases` (@acumino )
  - Fixed with https://github.com/gardener/etcd-druid/pull/281
- [x] [nginx-ingress-controller-seed](https://github.com/kubernetes/ingress-nginx/) - v0.49.0 is using `configmaps` (@shafeeqes )
  - https://github.com/kubernetes/ingress-nginx/issues/8091 
  - https://github.com/kubernetes/ingress-nginx/pull/8733
  - https://github.com/kubernetes/ingress-nginx/pull/8921
  - https://github.com/gardener/gardener/pull/6672
- [x] [external-dns-management](https://github.com/gardener/external-dns-management/) - v0.11.2 is using `configmapsleases` (@acumino )
  - Fixed with https://github.com/gardener/external-dns-management/pull/236

Extensions:

- [x] [machine-controller-manager](https://github.com/gardener/machine-controller-manager) - v0.42.0 is using `endpoints`  (all)
  - Ref https://github.com/gardener/gardener-extension-provider-aws/issues/413
  - https://github.com/gardener/machine-controller-manager/pull/662
  - Fixed with https://github.com/gardener/machine-controller-manager/pull/711
- [x] [machine-controller-manager-provider-alicloud](https://github.com/gardener/machine-controller-manager-provider-alicloud) - v0.3.0 is using `endpoints` (@ary1992 )
  - https://github.com/gardener/machine-controller-manager-provider-alicloud/pull/21
- [x] [machine-controller-manager-provider-aws](https://github.com/gardener/machine-controller-manager-provider-aws) - v0.8.0 is using `endpoints` (@shafeeqes )
  - https://github.com/gardener/machine-controller-manager-provider-aws/pull/63
- [x] [machine-controller-manager-provider-azure](https://github.com/gardener/machine-controller-manager-provider-azure) - v0.5.0 is using `endpoints` (@acumino )
  - https://github.com/gardener/machine-controller-manager-provider-azure/pull/51
- [x] [machine-controller-manager-provider-gcp](https://github.com/gardener/machine-controller-manager-provider-gcp) - v0.7.0 is using `endpoints` (@ary1992 )
  - https://github.com/gardener/machine-controller-manager-provider-gcp/pull/31
- [x] [machine-controller-manager-provider-openstack](https://github.com/gardener/machine-controller-manager-provider-openstack) - v0.6.0 is using `endpoints` (@shafeeqes )
  - https://github.com/gardener/machine-controller-manager-provider-openstack/pull/45
- [x] [machine-controller-manager-provider-vsphere](https://github.com/gardener/machine-controller-manager-provider-vsphere) - v0.10.0 is using `endpoints` (@acumino )
  - https://github.com/gardener/machine-controller-manager-provider-vsphere/pull/19
- [x] [gardener-extension-provider-vsphere](https://github.com/gardener/gardener-extension-provider-vsphere) - v0.11.0 is using `configmapsleases` (@acumino )
  - Fixed with https://github.com/gardener/gardener-extension-provider-vsphere/pull/194
- [x] [cert-management](https://github.com/gardener/cert-management)
  - Fixed with https://github.com/gardener/cert-management/pull/97

**Comment by shafeeqes** [comment]
Issue: Migrate `ingress-nginx` to use Lease API 
https://github.com/kubernetes/ingress-nginx/issues/8091

**Comment by acumino** [comment]
For [external-dns-management](https://github.com/gardener/external-dns-management/) we need to make changes in [controller-manager-library](https://github.com/gardener/controller-manager-library) and then revendor [external-dns-management](https://github.com/gardener/external-dns-management/) with the updated [controller-manager-library](https://github.com/gardener/controller-manager-library).

**Comment by MartinWeindel** [comment]
> For [external-dns-management](https://github.com/gardener/external-dns-management/) we need to make changes in [controller-manager-library](https://github.com/gardener/controller-manager-library) and then revendor [external-dns-management](https://github.com/gardener/external-dns-management/) with the updated [controller-manager-library](https://github.com/gardener/controller-manager-library).

Done with https://github.com/gardener/external-dns-management/pull/236

**Comment by shafeeqes** [comment]
kubernetes/ingress-nginx/pull/8107

**Comment by acumino** [comment]
kubernetes/cloud-provider-gcp#309

**Comment by acumino** [comment]
kubernetes/cloud-provider-openstack#1733

**Comment by rfranzke** [comment]
What's the status of this issue? 👀

**Comment by ialidzhikov** [comment]
MCM and its providers still use `endpointsleases`. To be switched to `leases` with https://github.com/gardener/machine-controller-manager/pull/711 and then has to be vendored in the MCM providers.

**Comment by shafeeqes** [comment]
https://github.com/kubernetes/ingress-nginx/pull/8107 is still open

**Comment by rfranzke** [comment]
@himanshu-kun The MCM PR is still open - what are the plans?

**Comment by himanshu-kun** [comment]
I am looking into it with @acumino as we want to test the relevance of `endpoint` in RBACs as pointed in [this comment](https://github.com/gardener/machine-controller-manager/pull/711#issuecomment-1132696519). It got delayed due to other ad-hoc tasks.
Will merge it in coming 2 days.

**Comment by rfranzke** [comment]
The only item left above is

> [nginx-ingress-controller-seed](https://github.com/kubernetes/ingress-nginx/) - v0.49.0 is using configmaps (@shafeeqes )

However, v0.49 is only used for seeds < 1.22, so are we fine here? Is there anything left to be done or can we close this issue?

**Comment by shafeeqes** [comment]
> The only item left above is
> 
> > [nginx-ingress-controller-seed](https://github.com/kubernetes/ingress-nginx/) - v0.49.0 is using configmaps (@shafeeqes )
> 
> However, v0.49 is only used for seeds < 1.22, so are we fine here? Is there anything left to be done or can we close this issue?

`nginx-ingress` is still using `configmapleases`, [ref](https://github.com/tao12345666333/ingress-nginx/blob/62a876a80875d53756b0831f03d518295f76f9f8/internal/ingress/controller/status.go#L104-L115), we have to wait till it uses `leases`.
I will open a corresponding PR soon.

**Comment by rfranzke** [comment]
Cool, thanks for the update

**Comment by shafeeqes** [comment]
The PR for using leases is also merged. Now we have to wait for the release of `ingress-nginx`.

**Comment by ialidzhikov** [comment]
/close
as all sub-tasks are completed
