### ISSUE TITLE
☂️ [GEP-17] Shoot Control Plane Migration "Bad Case" Scenario

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#4866]
**How to categorize this issue?**

/area control-plane-migration robustness
/kind enhancement epic
/roadmap internal
/priority 3

**What would you like to be added**:

This is an epic to track the implementation of [GEP-17 Shoot Control Plane Migration "Bad Case" Scenario](https://github.com/gardener/gardener/blob/master/docs/proposals/17-shoot-control-plane-migration-bad-case.md).

* Add handling of owner DNSRecord resources and ensure they are reconciled properly while avoiding rate limit issues.
  - [x] #4307 
  - [x] #4815 
  - [x] #4876
  - [x] gardener/gardener-extension-provider-aws/pull/425

* Add owner check watchdog to extension reconcilers and ensure canceling the reconciliation context works as expected.
  - [x] #4638
  - [x] #4720
  - [x] #4752

* Ensure all extensions have vendored g/g v1.33.1 with the owher check watchdog mechanism and the corresponding versions have been released:
  - [x] `provider-aws`: gardener/gardener-extension-provider-aws/pull/435, [v1.30.0](gardener/gardener-extension-provider-aws/releases/tag/v1.30.0)
  - [x] `provider-azure`: gardener/gardener-extension-provider-azure/pull/388, [v1.23.0](gardener/gardener-extension-provider-azure/releases/tag/v1.23.0)
  - [x] `provider-gcp`: gardener/gardener-extension-provider-gcp/pull/339
  - [x] `provider-openstack`: gardener/gardener-extension-provider-openstack/pull/347
  - [x] `provider-alicloud`: gardener/gardener-extension-provider-alicloud/pull/372, [v1.29.0](gardener/gardener-extension-provider-alicloud/releases/tag/v1.29.0)
  - [x] `provider-vsphere`: gardener/gardener-extension-provider-vsphere/pull/182
  - [x] `networking-calico`: gardener/gardener-extension-networking-calico/pull/121, [v1.21.0](gardener/gardener-extension-networking-calico/releases/tag/v1.21.0)
  - [x] `networking-cilium`: gardener/gardener-extension-networking-cilium/pull/71, [v1.7.1](https://github.com/gardener/gardener-extension-networking-cilium/releases/tag/v1.7.1)
  - [x] `os-gardenlinux`: gardener/gardener-extension-os-gardenlinux/pull/51
  - [x] `os-ubuntu`: gardener/gardener-extension-os-ubuntu/pull/55
  - [x] `os-suse-chost`: gardener/gardener-extension-os-suse-chost/pull/57, [v1.14.0](gardener/gardener-extension-os-suse-chost/releases/tag/v1.14.0)
  - [x] `runtime-gvisor`: gardener/gardener-extension-runtime-gvisor/pull/28
  - [x] `shoot-cert-service`: gardener/gardener-extension-shoot-cert-service/pull/97
  - [x] `shoot-dns-service`: gardener/gardener-extension-shoot-dns-service/pull/89

* Adapt `external-dns-mangement` and the `shoot-dns-service` extension to not reconcile shoot DNS resources if the ownership has changed.
  - [x] gardener/external-dns-management/pull/192, [v0.11.0](gardener/external-dns-management/releases/tag/v0.11.0)
  - [x] gardener/gardener-extension-shoot-dns-service/pull/90

* Add owner checks and taking of final snapshots to `etcd-backup-restore`, introduce the corresponding configuration in the `Etcd` resource and controller (`etcd-druid`), and ensure it is set properly by `gardenlet`.
  - [x] gardener/etcd-backup-restore/pull/383
  - [x] gardener/etcd-druid/pull/239
  - [x] #4813

* Add copying of etcd backups to the destination backup container to `etcd-backup-restore`, the corresponding resource and controller to `etcd-druid`, and the corresponding adaptations to `gardenlet`. This is not strictly part of the "bad case" scenario implementation, but it's a prerequisite for implementing the flow as described in [GEP-17]((https://github.com/gardener/gardener/blob/master/docs/proposals/17-shoot-control-plane-migration-bad-case.md)).
  - [x] gardener/etcd-backup-restore/pull/369
  - [x] gardener/etcd-druid/pull/234
  - [x] #4894

* Ensure all provider extensions have vendored g/g v1.37.0 with the copying of backups mechanism and the corresponding versions have been released:
  - [x] `provider-aws`: gardener/gardener-extension-provider-aws/pull/463
  - [x] `provider-azure`: gardener/gardener-extension-provider-azure/pull/418
  - [x] `provider-gcp`: gardener/gardener-extension-provider-gcp/pull/364
  - [x] `provider-openstack`: gardener/gardener-extension-provider-openstack/pull/364
  - [x] `provider-alicloud`: gardener/gardener-extension-provider-alicloud/pull/403
  - [x] `provider-vsphere`: gardener/gardener-extension-provider-vsphere/pull/187
  - [x] `provider-equinix-metal`: gardener/gardener-extension-provider-equinix-metal/pull/180

* Ensure CPM "bad case" scenario mechanisms in `etcd-backup-restore` and `etcd-druid` work correctly with multi-node etcd.
  - [ ] Adapt owner checks, taking of final snapshots, and disabling the cluster in `etcd-backup-restore` for multi-node etcd (part of gardener/etcd-backup-restore/pull/353, see also gardener/etcd-druid/issues/242)
  - [x] Add owner check watchdog to `etcd-druid` to prevent reconciling `Etcd` resources when the seed is no longer the owner of the shoot

* Adapt `gardenlet` shoot reconciliation and migration flows for the "bad case" and the "good case" scenarios.
  - [x] #5095
  - [x] #5101

* Add forcing the shoot's restoration to the destination seed during control plane migration if the preparation for migration in the source seed is not finished after a certain grace period and is considered unlikely to succeed (falling back to the "bad case" scenario).
  - [x] #5123

* Add automatic cleanup of shoot leftover resources in source seeds if the fallback to the "bad case" scenario had taken place, see also #5173.
  - [ ] #5150
  - [ ] Enhance the `ShootLeftover` resource and controller to support a grace period for the actual cleanup of shoot leftover resources (see https://github.com/gardener/gardener/issues/5173#issuecomment-997218476).
  - [ ] Add an admission plugin for `ShootLeftover` resources.
  - [ ] Actually trigger the cleanup of shoot leftover resources in the new reconcilers introduced with #5123.

* Testing
  - [ ] Add integration test for CPM "bad case" scenario

**Comment by MartinWeindel** [comment]
Regarding the shoot-dns-service extension: PR https://github.com/gardener/gardener-extension-shoot-dns-service/pull/63 was replaced by https://github.com/gardener/gardener-extension-shoot-dns-service/pull/90

**Comment by plkokanov** [comment]
Closing this in favour of #6302
