### ISSUE TITLE
☂️ Projected Service Account Tokens

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#4878]
**How to categorize this issue?**

/area security
/kind enhancement
/priority 3

This is an epic to track the development related to leveraging [projected `ServiceAccount` tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) for the components Gardener deploys into seed and shoot clusters

#### Merge `gardener/gardener-resource-manager` repository into `gardener/gardener` since we decided to add new controllers/webhooks to GRM as it's already deployed for all seeds and shoots:

- [x] #4757
- [x] #4848
- [x] #4871

#### Mimic [upstream `rootcacertpublisher` controller](https://github.com/kubernetes/kubernetes/tree/release-1.22/pkg/controller/certificates/rootcacertpublisher) in `kube-controller-manager` to make its functionality available for old Kubernetes versions

- [x] #4832
- [x] Enablement of this new controller for seed and shoot clusters (#4940)

#### Webhook for automatically adding projected `ServiceAccount` token `volumes` and `volumeMounts` for `Pod`s (so that we don't have to manually adapt all the components deployed in seeds and shoots)

- [x] #4873
- [x] #4941
- [x] Enablement of this new webhook for seed and shoot clusters (#5002)
- [x] #4659
- [x] #4660

#### Controller for creating `ServiceAccount`s in shoot clusters, requesting short-lived tokens, and pushing them back into the shoot namespaces in the seed for the control plane components to use (e.g. `kube-scheduler`) when communicating with the shoots' `kube-apiserver`s

- [x] #4867
- [x] Enablement of this new controller for shoot clusters (#4931)
- [x] #4661

#### Controller for invalidating static `ServiceAccount` tokens since we plan to not use them anymore and since Kubernetes does not provide such a feature yet

- [x] #4817
- [x] Enablement of this new controller and webhook for seed and shoot clusters (#5002)

#### Miscellaneous

- [x] https://github.com/gardener/gardener/pull/5341
- [x] https://github.com/gardener/gardener/pull/5506
- [x] https://github.com/gardener/gardener/pull/5422
  - The unused static `ServiceAccount` tokens for the controllers part of `kube-controller-manager` in the `kube-system` namespace of shoot clusters are now invalidated for all Kubernetes versions. However, note that the tokens for three of these controllers (`{node,route,service}` controllers) will only be invalidated for Kubernetes 1.21+ clusters since the `cloud-controller-manager`s of prior versions still rely on them.

#### Related, but out of scope for now and potential improvements for the future

- Consider whether we want to consciously protect the `ServiceAccount`s in the shoot created by the `TokenRequestor` (ref #55)
- #4924
- Add metrics and Grafana dashboards for `Token{Requestor,Invalidator}` controllers part of `gardener-resource-manager`

**Comment by rfranzke** [comment]
All related tasks have been completed.
/close
