### ISSUE TITLE
Improve Logging / GroupBy Cluster and Operation + Show As Task List

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#49]
# Story
- As operator (of the week) I want to access cluster operations logs (create, update/reconcile, delete) in a convenient way, so that I can easily see what the outcome of each operation was without trying to `grep` the information out of the overall/global Gardener logs.

# Motivation
We should improve the way how we interact/access the Gardener/cluster logs. As an operator (of the week) I frequently have to check what the Gardener says/logs on a certain cluster and operation. Now with the reconciler, the logs grew and with all the other planned features, they will even grow more. Of course, we will have a logging stack eventually, but that's not what this story is about. Usually I need to know something specific about a particular cluster, for a particular operation at a particular date/time. A logging stack and UI will allow me to set filters, but it won't be semantic in this sense. Also, we can't give away the entire operator logs via a logging stack to the entirety of the people that will later use the Gardener dashboard as operators (there must be strong isolation, so that we can have only one Gardener instance running).

# Acceptance Criteria
- [ ] Keep track of logs per operation

# Implementation Proposal
What springs to mind is something similar to the Bosh tasks and logs. There, the user nicely sees what the Bosh director does and did: A creation of a certain deployment, a deletion of one, any scan & fix tasks that happened on it, etc. Information (collection of logs) on that granularity (cluster + operation) would be a great improvement over a large shared operator log where I have the access rights issue and can only filter by properties instead of seeing (in a list) which operations where carried out when on one or all of my clusters in my project.

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
End of 2017 we implemented operation IDs that group all logs for an operation like create, reconcile or delete and report those as events of shoot resources, i.e. we have now the technical means to expose the logs in the dashboard (BLI).
