### ISSUE TITLE
Finalise "Good Case" Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#4902]
# Stories
- As user I want my clusters to recover from a disaster, should it strike (downtime is aceptable).
- As operator I want an easy, fail-safe, automated, and fast means to migrate clusters if disaster strikes.
- As provider I want disaster recovery to provide a compliant and safe service.

# Motivation
[GEP-17 Shoot Control Plane Migration "Good Case" Scenario](https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md) deals with cooperative `seeds` where a control plane can be migrated without any data loss. Migration of control planes from non-cooperative `seeds` is covered in [GEP-17 Shoot Control Plane Migration "Bad Case" Scenario](https://github.com/gardener/gardener/blob/master/docs/proposals/17-shoot-control-plane-migration-bad-case.md).

The main functionality of [GEP-7 Control Plane Migration](https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md) has been implemented. However, some enhancements are still necessary. This epic will be used to track these enhancements and fixes.

# Acceptance Criteria
- [x] End-to-end tests
  <details>
  <summary>Tasks</summary>

   - [x] #5500  (@kris94)
   - [x] #5987 (@kris94)
   - [x] Add support for creating a second seed in the completely local setup. (@plkokanov)

  </details>
- [x] Bugfixes
  <details>
  <summary>Tasks</summary>

  - [x] #4484
  - [x] #4820
  - [x] #5376
  - [x] #5423
  - [x] #4793 
  - [x] #5377
  - [x] Create a script that can be used to check the consistency of secrets in the shootstate and the control plane (plkokanov) 
  - [x]  ~https://github.com/gardener/dependency-watchdog/issues/35 this issue is causing the integration tests for control plane migration to fail so it should be fixed~ - no longer relevant to Control Plane Migration only. Check #6036 

  </details>
- [x] General Enhancements
  <details>
  <summary>Tasks</summary>

  - [x] #4883
  - [x] #5274 - necessary so that shoots do not get migrated to broken seeds (kris94)
  - [x] #4901 Alternatively we can forbid changes to the shoot spec, however there are still problems if a previous reconciliation did not completely finish (e.g a reconciliation to upgrade the kubernetes version) and cp migration was triggered

  </details>
- [x] Integration Tests
  <details>
  <summary>Tasks</summary>

  - [x] Add a test to perform control plane migration of a hibernated cluster
  - [x] #5350

  </details>
- [x] Documentation
  <details>
  <summary>Tasks</summary>

  - [x] Update documentation about control plane migration usage by adding more details about triggering the process and how to monitor it
  - [x] ~Add docs about how other extension controllers need to be modified so that they support control plane migration.~ This is already available and up-to-date here: https://github.com/gardener/gardener/blob/master/docs/extensions/migration.md 

  </details>

# Enhancement/Implementation Proposal
- https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md

**Comment by plkokanov** [comment]
Closing this as the tasks have been completed. I've opened #6281 to track the leftovers for the e2e tests.
