### ISSUE TITLE
Configurable log level/format everywhere

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5191]
**How to categorize this issue?**

/area logging ops-productivity dev-productivity
/kind enhancement

**What would you like to be added**:

Currently, only components with a component config (controller-manager, scheduler and gardenlet) feature a configurable log level and format. apiserver is special as it uses the apiserver-library and inherits its log-related flags (`-v` and friends).

There are a lot more components, that should be equipped with a configurable log level and format (currently hard-coded to `info` and `json`):
- [x] gardener-admission-controller #6652 
- [x] gardener-apiserver #6817
- [x] gardener-resource-manager #6830
- [x] gardener-seed-admission-controller #6831
- [x] gardener-extension-provider-local #6875

We should add configuration options via command line flags that can be used in all components. They should resemble the current options in component config APIs and could probably replace them, so that all components use the same mechanisms with the same semantics.

Extensions need to be adapted outside of this repository. However we should make helpers reusable across the board, so that the adoption is trivial.

In this context, we could also think about whether we should keep `debug`, `info` and `error` as log levels or if we want to have numbered (and more) levels like klog. However, at the time of writing there is no preference in either direction.

**Why is this needed**:

Developers want to add more verbose log messages that are useful during debugging and development, while operators are not interested in all log messages by default, but want to be able to see more verbose logs from time to time.
Currently, there is little/no incentive for developers to add helpful logs at "debug" level, because they will anyways not be shown at all in some components.

Also `text` format is sometimes nicer for development, while `json` allows better processing in production systems.

**Comment by rfranzke** [comment]
/close
All tasks have been completed.
