### ISSUE TITLE
Enable more e2e tests in presubmits and periodics

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5310]
**How to categorize this issue?**

/area testing dev-productivity quality
/kind enhancement

**What would you like to be added**:

In the context of https://github.com/gardener/gardener/issues/5024, we added an e2e job that runs for PR verification and periodically on `master`: https://github.com/gardener/ci-infra/pull/20
Currently, [gardener-e2e-kind jobs](https://prow.gardener.cloud/?job=*-gardener-e2e-kind) execute `make test-e2e-local` which only does a simple shoot creation followed by a deletion (see [definition](https://github.com/gardener/ci-infra/blob/5ad1ea15c5eddec95969c9b51f340446558ec292/config/jobs/gardener/gardener-e2e-kind.yaml#L35-L41) and [test-e2e-local.sh](https://github.com/gardener/gardener/blob/d7fa91d6f1a1ae0cf9d827ea8aa66c2ae6fc550c/hack/test-e2e-local.sh)).

We would like to run more e2e tests (PRs + master), e.g.
- create a hibernated shoot, delete it
- create a shoot, hibernate it, wake it up, delete it
- create a shoot, execute a control plane migration, delete it

**Why is this needed**:

This is needed to better prevent future regressions, e.g. https://github.com/gardener/gardener/pull/5300 and similar.

## Tasks

- [x] restructure the e2e test suite and make it easy to extend: https://github.com/gardener/gardener/pull/5320
- [x] add e2e tests for hibernation: https://github.com/gardener/gardener/pull/5320
- [x] add documentation for developers: [testing.md](https://github.com/gardener/gardener/blob/c4ee3949450b998abe22fe7f5143621dbc2fd085/docs/development/testing.md) https://github.com/gardener/gardener/pull/5469
- [x] restructure the `/test` directory to reflect the actual types of test: https://github.com/gardener/gardener/pull/5469
  - there should be one package hierarchy for each: integration tests (basically what is under `/test/integration/envtest` today), e2e tests (already placed correctly under `/test/e2e`), the test framework (already correctly placed under `/test/framework`) and testmachinery tests (basically everything else)
  - adapt the test definitions under `/.test-defs` to the changed structure

**Comment by timebertt** [comment]
/close
as the first few steps have been completed.
More e2e tests will be tracked separately. 
Next step is the CPM e2e test, which requires https://github.com/gardener/gardener/issues/5500
