### ISSUE TITLE
Use `systemd` as cgroup driver

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5325]
**How to categorize this issue?**

/area open-source
/kind enhancement

**What would you like to be added**:
With https://github.com/gardener/gardener/pull/5255 we have switched the cgroup driver from `cgroupfs` to `systemd` for shoots >= 1.23. However, this change was reverted with https://github.com/gardener/gardener/pull/5324.

Let's look into that the consequences of this change are, how the container runtime needs to be configured and how to properly roll this out.

**Why is this needed**:
Following [upstream recommendations](https://github.com/kubernetes/kubeadm/issues/1394#issuecomment-462878219).

**Work Items**
- [ ] Switch default kubelet configuration to `systemd` for all k8s versions >= 1.24 as was done in https://github.com/gardener/gardener/pull/5255/files#diff-fc4776dd3fd3277fcbaac11c0bcfe15e6bd797038eb1cc601444de5ca4c3bc68 but later reverted
  * We don't care about `docker` configuration as that's not a possible configuration in Gardener for k8s >= 1.23
- [ ] Introduce a property/helper function to figure out what the `cgroupfs driver` configuration is
- [ ] Switch g/g [`containerd` configuration](https://github.com/gardener/gardener/blob/77e09dd522d7bfb682cc35d0be437201b606061b/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh#L3-L7) to respect the selected `cgroupfs driver`
* Adapt containerd bootstrapping in OS extensions to use `systemd` as cgroupfs driver 
  * Pass in an additional parameter similar to [`isContainerDEnabled`](https://github.com/gardener/gardener/blob/970ae9649ed7953e8a1add7e9bed5b03f5e54636/extensions/pkg/controller/operatingsystemconfig/oscommon/template/template_generator.go#L169) that indicates which `cgroupfs driver` is used.
  - [ ] [Gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux/blob/ad3999428f5ee31d0a473bb4e100100b290f2228/pkg/generator/templates/cloud-init.gardenlinux.template#L15-L20)
  - [ ] [Flatcar](https://github.com/gardener/gardener-extension-os-coreos/blob/a9ca4f4c579fff269670b44f0b9cf53a74f52281/pkg/coreos/templates/containerd/run-command.sh.tpl#L4)
  - [ ] [Ubuntu](https://github.com/gardener/gardener-extension-os-ubuntu/blob/81c574ed4a07f69ad56883766acbbd12d9aaa3db/pkg/generator/templates/cloud-init-ubuntu.template#L60-L64)
  - [ ] [SUSE Chost](https://github.com/gardener/gardener-extension-os-suse-chost/blob/33c4296825da055c05fbaca9abea9e45004aca4d/pkg/generator/templates/script.suse-chost.template#L37-L42)

**Open Questions** 
* How do we prevent running with `systemd` as `cgroupfs driver` when the OS extensions have not been updated to respect this in their bootstrapping logic?
* Should we have a killswitch e.g. in cloud-config/kubelet reconfiguration that throws and error when there's a mismatch between kubelet config and containerruntime?

**Comment by vpnachev** [comment]
Thinking again on this topic, Gardener can configure both [kubelet](https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go#L54) and containerd [(similarly to how it control the pause image)](https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh#L9-L12) to use the wanted cgroup driver, so from this point of view the OS extensions should not do anything.  What do you think?

**Comment by voelzmo** [comment]
> Thinking again on this topic, Gardener can configure both [kubelet](https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go#L54) and containerd [(similarly to how it control the pause image)](https://github.com/gardener/gardener/blob/744e0ff5db4f7f58d70a2f43546d379303f8a2cf/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/containerd/templates/scripts/init.tpl.sh#L9-L12) to use the wanted cgroup driver, so from this point of view the OS extensions should not do anything. What do you think?

I can see how gardener modifies the `containerd` configuration file to inject the pause image and was thinking about something similar for the `cgroup driver` setting as well. This would, however, mean that we bootstrap a node first with the containerd configuration file from the OS extensions ([flatcar example here](https://github.com/gardener/gardener-extension-os-coreos/blob/a9ca4f4c579fff269670b44f0b9cf53a74f52281/pkg/coreos/templates/containerd/run-command.sh.tpl#L4), and later on change the cgroup driver, when the cloud-config is applied. My understanding was that changing the cgroup driver for a running node was something we would want to avoid? Or do you think in this scenario this would be okay?

**Comment by voelzmo** [comment]
@vpnachev do you have some thoughts on the above discussion? It may be that we have some time to pick this up in the near future.

**Comment by rfranzke** [comment]
/remove-lifecycle stale
cc @MrBatschner

**Comment by voelzmo** [comment]
I understand that this is only a prerequisite for enabling `cgroupsv2`, but please be aware that additional things need to be done before switching the cgroup:

- ensure that we're using at least `containerd` [1.5.12](https://github.com/containerd/containerd/releases/tag/v1.5.12) or [1.6.3](https://github.com/containerd/containerd/releases/tag/v1.6.3) to get the [fix for incorrectly detected OOMKill events](https://github.com/containerd/containerd/pull/6735), or otherwise VPA cannot act on OOMKill events.
  - [x] Done in gardenlinux since [576.12](https://github.com/gardenlinux/gardenlinux/releases/tag/576.12)
  - [ ] other supported OSes?

And a few interesting things from https://blog.kintone.io/entry/2022/03/08/170206

For example (taken from the above link) regarding [uber-go/automaxprocs](https://github.com/uber-go/automaxprocs):
> If you're using a version until v1.4.0, you need to patch it with a cgroup v2 PR or set GOMAXPROCS manually for a while.

And regarding the JDK version
> We need to use JDK 15 or later to run Java applications properly in the cgroup v2 environment. Let me describe it briefly.
>
> JDK has built-in support for the container environment from version 8u131. JDK 10 introduced the +UseContainerSupport option and enabled it by default. With this option, JDK inspects the cgroup filesystem and reads the CPU and memory quotas for its use. The CPU quota information is available on Runtime.availableProcessors() (see Docker blog for details). The memory quota affects its heap memory usage. This mechanism should be adjusted for cgroup v2, and the f[ix became available with JDK 15](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8230305).

**Comment by rfranzke** [comment]
@danielfoehrKn @MrBatschner Could you check the PR description and tell whether this is still up-to-date/the plan you are pursuing?

**Comment by rfranzke** [comment]
ping @danielfoehrKn @MrBatschner

**Comment by MrBatschner** [comment]
> @danielfoehrKn @MrBatschner Could you check the PR description and tell whether this is still up-to-date/the plan you are pursuing?

Sorry for the delay in answering. The PR linked above is meant to configure containerd and kubelet on Garden Linux to use systemd as cgroup driver if cgroup v2/unified hierarchy is detected (as Garden Linux 934 came with cgroup v2 support). However, this is just for Garden Linux. The CoreOS/FlatCar extension contains similar code and eventually, the Ubuntu and cHost extensions would require such code too - especially since the systemd announced to drop cgroup v1 support in a future release. Instead of having quite similar code to deal with the cgroup versions in each operating system extension separately, we should explore if this can be moved into the OS config part of Gardener itself - and that is the direction @danielfoehrKn and myself were looking into so far. Thus, this issue in my opinion is still relevant.

**Comment by ialidzhikov** [comment]
With https://github.com/gardener/gardener/pull/10472, starting K8s 1.31 the cgroup driver of kubelet and containerd is being defaulted to `systemd`.
