### ISSUE TITLE
Configure fine-granular `PriorityClasses` for all components

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#5634]
**How to categorize this issue?**

/area high-availability ops-productivity quality
/kind enhancement

**What would you like to be added**:

Configure priorityclass for the Gardener components
- [x] admission-controller -> #5652
- [x] apiserver -> #5652
- [x] controller-manager -> #5652
- [x] gardenlet -> #1899
- [x] scheduler -> #5652
- seed-admission-controller -> #5657
- resource-manager -> #5657

With the new plan from https://github.com/gardener/gardener/issues/5634#issuecomment-1156512839:
- [x] https://github.com/gardener/gardener/pull/6186
- adapt all components managed by gardenlet to use the well-known `PriorityClasses` and drop custom ones
  - [x] gardenlet itself (helm chart, reused by `ManagedSeed`) -> #6235 
     -  Revert changes https://github.com/gardener/gardener/pull/6432
     -  Remove `gardenlet` priority class and use `gardener-system-critical-migration` priority class for migration purpose of `gardenlet` priority class. -> https://github.com/gardener/gardener/pull/6510
    - Use `gardener-system-critical` for `gardenlet`. -> https://github.com/gardener/gardener/pull/6586
    - [x] Remove clean up code of `gardener-system-critical-migration` priority class. -> https://github.com/gardener/gardener/pull/6738
  - [x] Seed system components: seed-admission-controller, resource-manager, istiod, etc. -> #6257 
  - Shoot control plane components
    - [x] kube-apiserver, kube-controller-manager -> #6242 
  - [x] etcd: this will cause a rollout of all etcd pods, should be done separately and preferably together with another change that rolls out etcd: https://github.com/gardener/gardener/pull/6467
- adapt all extensions components deployed to seeds (included in `ControllerDeployment`) and control plane / shoot system components managed by extensions to use the well-known `PriorityClasses` and drop custom ones
  - [x] provider-local -> #6236
  - [x] external-dns-management -> https://github.com/gardener/external-dns-management/pull/265
  - [x] kupid -> https://github.com/gardener/kupid/pull/44
  - [x] networking-calico -> https://github.com/gardener/gardener-extension-networking-calico/pull/192
  - [x] networking-cilium - > https://github.com/gardener/gardener-extension-networking-cilium/pull/103
  - [x] os-coreos -> https://github.com/gardener/gardener-extension-os-coreos/pull/46
  - [x] os-gardenlinux -> https://github.com/gardener/gardener-extension-os-gardenlinux/pull/64
  - [x] os-suse-chost -> https://github.com/gardener/gardener-extension-os-suse-chost/pull/69
  - [x] os-ubuntu -> https://github.com/gardener/gardener-extension-os-ubuntu/pull/66
  - [x] provider-alicloud -> https://github.com/gardener/gardener-extension-provider-alicloud/pull/507
  - [x] provider-aws -> https://github.com/gardener/gardener-extension-provider-aws/pull/571
  - [x] provider-azure -> https://github.com/gardener/gardener-extension-provider-azure/pull/533
  - [x] provider-equinix-metal -> https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/217
  - [x] provider-gcp -> https://github.com/gardener/gardener-extension-provider-gcp/pull/462
  - [x] provider-openstack -> https://github.com/gardener/gardener-extension-provider-openstack/pull/468
  - [x] provider-vsphere -> https://github.com/gardener/gardener-extension-provider-vsphere/pull/262
  - [x] runtime-gvisor -> https://github.com/gardener/gardener-extension-runtime-gvisor/pull/48
  - [x] shoot-cert-service -> https://github.com/gardener/gardener-extension-shoot-cert-service/pull/126
  - [x] shoot-dns-service -> https://github.com/gardener/gardener-extension-shoot-dns-service/pull/143
  - [x] shoot-networking-filter -> https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/22
  - [x] shoot-networking-problemdetector -> https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/12
  - [x] gardener-extension-shoot-oidc-service -> https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/69
- [x] terraformer -> https://github.com/gardener/gardener/pull/6515
- [x] drop deprecated `gardener-shoot-controlplane` once all components have been migrated to the other fine-granular PriorityClasses -> https://github.com/gardener/gardener/pull/6738, https://github.com/gardener/gardener/pull/6899

**Why is this needed**:
These are components with high importance for a gardener landscape and shouldn't be evicted by pods with lower importance that have higher pod priority.

**Comment by ialidzhikov** [comment]
@vpnachev, really nice finding! Thank you for this issue!

**Comment by acumino** [comment]
Maybe we can use this new feature. [Add non-preempting option to PriorityClasses] (https://github.com/kubernetes/enhancements/issues/902.)

**Comment by rfranzke** [comment]
/unassign @ialidzhikov
/assign @rfranzke 

I still plan to take a look and at least come up with a proposal which `PriorityClass`es should be introduced and how the components should be assigned (either tomorrow or beginning of next week).

**Comment by rfranzke** [comment]
We discussed out of band that our usage of `PriorityClass`es is quite confusing today and that we should think whether we can introduce some better concepts to improve the overall robustness of the system.

I looked into this topic and I propose that we introduce the following `PriorityClass`es and with their respective associations:

## Seed Clusters

The seed controller in gardenlet would create the following to-be "well-known" `PriorityClass`es as part of the seed bootstrapping. Extensions can rely on them/their names.

| Name                                      | Priority   | Associated Components                                                                                                                                                                     |
| ----------------------------------------- | ---------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `gardener-system-critical` | 999998950 | `gardenlet`, `gardener-resource-manager`, `istio-ingressgateway`, `istiod`                                                                                                                |
| `gardener-system-900`    | 999998900  | Extensions, `gardener-seed-admission-controller`, `reversed-vpn-auth-server`                                                                                                              |
| `gardener-system-800`  | 999998800  | `dependency-watchdog-endpoint`, `dependency-watchdog-probe`, `etcd-druid`, `(auditlog-)mutator`, `vpa-admission-controller`                                                               |
| `gardener-system-700`     | 999998700  | `auditlog-seed-controller`, `hvpa-controller`, `vpa-recommender`, `vpa-updater`                                                                                                         |
| `gardener-system-600`  | 999998600  | `aggregate-alertmanager`, `alertmanager`, `fluent-bit`, `grafana`, `kube-state-metrics`, `nginx-ingress-controller`, `nginx-k8s-backend`, `prometheus`, `seed-prometheus`, `vpa-exporter` |
| `gardener-reserve-excess-capacity`        | -5         | `reserve-excess-capacity` ([ref](https://github.com/gardener/gardener/pull/6135)) |
| <hr>                                      | <hr>       | <hr>                                                                                                                                                                                      |
| `gardener-system-500` | 999998500  | `etcd-events`, `etcd-main`, `kube-apiserver`                                                                                                                                              |
| `gardener-system-400`    | 999998400  | `gardener-resource-manager`                                                                                                                                                               |
| `gardener-system-300`  | 999998300  | `cloud-controller-manager`, `cluster-autoscaler`, `csi-driver-controller`, `kube-controller-manager`, `kube-scheduler`, `machine-controller-manager`, `terraformer`, `vpn-seed-server`                  |
| `gardener-system-200`     | 999998200  | `csi-snapshot-controller`, `csi-snapshot-validation`, `cert-controller-manager`, `shoot-dns-service`, `vpa-admission-controller`, `vpa-recommender`, `vpa-updater`                        |
| `gardener-system-100`  | 999998100  | `alertmanager`, `grafana-operators`, `grafana-users`, `kube-state-metrics`, `prometheus`, `loki`                                                                                          |

## Shoot Clusters

The shoot controller in gardenlet would create the following to-be "well-known" `PriorityClass`es as part of the shoo reconciliation. Extensions can rely on them/their names.

| Name                                              | Priority   | Associated Components                                                                                                       |
| ------------------------------------------------- | ---------- | --------------------------------------------------------------------------------------------------------------------------- |
| `system-node-critical` (created by Kubernetes)    | 2000001000 | `calico-node`, `kube-proxy`, `apiserver-proxy`, `csi-driver`, `egress-filter-applier`                                                                |
| `system-cluster-critical` (created by Kubernetes) | 2000000000 | `calico-typha`, `calico-kube-controllers`, `coredns`, `vpn-shoot`                                                                                   |
| `gardener-shoot-system-900`           | 999999900  | `node-problem-detector`                                                                                                     |
| `gardener-shoot-system-800`         | 999999800  | `calico-typha-horizontal-autoscaler`, `calico-typha-vertical-autoscaler`                                                    |
| `gardener-shoot-system-700`            | 999999700  | `blackbox-exporter`, `node-exporter`                                                                                        |
| `gardener-shoot-system-600`         | 999999600  | `addons-nginx-ingress-controller`, `addons-nginx-ingress-k8s-backend`, `kubernetes-dashboard`, `kubernetes-metrics-scraper` |

Any opinions on this proposal? Let me know if I forgot/missed a component in the tables above.

**Comment by timebertt** [comment]
I've updated @rfranzke's proposal after another round of discussion and will start working on it this week.
/unassign @rfranzke 
/assign @timebertt

**Comment by timebertt** [comment]
One more nit, I noticed in the above proposal:
`gardener-system-critical` (like all other classes in Seeds) should have less priority than all `gardener-shoot-system-*` classes, to ensure shoot cluster critical components have higher priority than seed cluster components if we are on a `ManagedSeed`.
Therefore, I propose to use `gardener-system-critical=999998950`.

Additionally, I propose to drop `gardener-shoot-system-critical` in favor of reusing `system-cluster-critical` for `coredns` and `vpn-shoot` and `system-node-critical` for `egress-filter-applier`.

WDYT?

**Comment by rfranzke** [comment]
> Therefore, I propose to use gardener-system-critical=999998950.

Yes, sounds good, I think we talked about this in our meeting but didn't adapt the values accordingly.

> Additionally, I propose to drop gardener-shoot-system-critical in favor of reusing system-cluster-critical for coredns and vpn-shoot and system-node-critical for egress-filter-applier.

Fine for me, although this will create a slight asymmetry 😉

**Comment by timebertt** [comment]
/unassign
I have completed the first steps in https://github.com/gardener/gardener/pull/6186 and listed the remaining steps in the original issue description.

**Comment by ialidzhikov** [comment]
In https://github.com/gardener/gardener/issues/5634#issuecomment-1156512839 I don't see the terraformer component. Did we miss it?

**Comment by timebertt** [comment]
Yes, it's not included in the list.
I'm wondering whether we should assign a priority class to terraformer, as we probably don't want to preempt any of the control plane components in favor of a short-lived terraformer pod.
If there is no free capacity on the seed nodes we would wait for a new node to be added by cluster-autoscaler, which should be fine.
WDYT?

**Comment by ialidzhikov** [comment]
My concern was that the terraformer Pod can be evicted in favor of other control plane components. We know that in the past we had issue with terraform state lost - my feeling is that the terraform and its providers are not rock solid and just wanted to prevent any potential state lost issue that can arise around terraformer Pod being evicted and terraform (or its providers) not being able to properly handle the early termination.

**Comment by timebertt** [comment]
Got your concern. Which priority class do you suggest?

**Comment by timebertt** [comment]
/unassign @kris94 
as he is unavailable for the remaining items
/assign @acumino

**Comment by timebertt** [comment]
We decided to go with `gardener-system-300` for `terraformer`.
/assign
for this item.

**Comment by timebertt** [comment]
> We decided to go with `gardener-system-300` for `terraformer`.

Done with https://github.com/gardener/gardener/pull/6515
/unassign

**Comment by shafeeqes** [comment]
/close
All tasks are completed.

**Comment by timebertt** [comment]
/reopen

I just observed that a `kube-scheduler` pod was preempted by a `loki` pod, so I noticed that some components were not adapted yet:
```
$ k get po -o=custom-columns="name:.metadata.name,priorityclass:.spec.priorityClassName"
name                                                   priorityclass
cert-controller-manager-5c647d9bc9-56cwv               gardener-system-200
cloud-controller-manager-86bf56fdcf-bqs6h              gardener-system-300
cluster-autoscaler-5bbbbc9b-vx27w                      <none>
csi-driver-controller-7ffbfdffc-tptkg                  gardener-system-300
csi-snapshot-controller-7595464c96-z8ldr               gardener-system-200
csi-snapshot-validation-859b787d9c-4qf4k               <none>
etcd-events-0                                          gardener-system-500
etcd-main-0                                            gardener-system-500
event-logger-66fd786cdc-jfh6n                          gardener-system-100
gardener-resource-manager-64785d9c95-596t9             gardener-system-400
gardener-resource-manager-64785d9c95-ccms6             gardener-system-400
gardener-resource-manager-64785d9c95-dvbrp             gardener-system-400
grafana-operators-76bb69d65c-r7xnk                     gardener-system-100
grafana-users-8584f55bc5-jsmlh                         gardener-system-100
kube-apiserver-78f7d66fcf-j449b                        gardener-system-500
kube-apiserver-78f7d66fcf-jxgt2                        gardener-system-500
kube-apiserver-78f7d66fcf-wc6rl                        gardener-system-500
kube-controller-manager-6d8697459b-t2czj               gardener-system-300
kube-scheduler-7946565f8f-7r82r                        <none>
kube-state-metrics-74c5544c64-sz8qt                    gardener-system-100
loki-0                                                 gardener-system-100
machine-controller-manager-7bdd655b8f-lqx82            gardener-system-300
network-problem-detector-controller-6f895cfd9b-9vq87   gardener-system-200
prometheus-0                                           gardener-system-100
shoot-dns-service-5cb9bf6c89-mrshz                     <none>
vpa-admission-controller-5bfd4b6d86-nrtt6              gardener-system-200
vpa-recommender-54bffb8dc4-8th7j                       gardener-system-200
vpa-updater-cff9dd4cc-27xvp                            gardener-system-200
vpn-seed-server-699ccc8846-n8ws4                       gardener-system-300
```

Most importantly, the following components that are configured in this repository were not adapted:
- cluster-autoscaler
- kube-scheduler

**Comment by ialidzhikov** [comment]
- [x] `cluster-autoscaler` and `kube-scheduler` -> https://github.com/gardener/gardener/pull/6838
- [x] `csi-snapshot-validation` -> https://github.com/gardener/gardener-extension-provider-gcp/pull/507 (I found it missing only for provider-gcp, for the other provider extensions it was set)
- [x] `shoot-dns-service` -> https://github.com/gardener/gardener-extension-shoot-dns-service/pull/163

**Comment by ialidzhikov** [comment]
/close
as the items from https://github.com/gardener/gardener/issues/5634#issuecomment-1280573295 are completed

**Comment by rfranzke** [comment]
/reopen
for cleanup
due to https://github.com/gardener/gardener/pull/6799

**Comment by ialidzhikov** [comment]
/close
as https://github.com/gardener/gardener/pull/6899 is merged
