### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.24”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5912]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.24 has been released, find the changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md

Work can be started and pushed to the [`kubernetes-v1.24`](https://github.com/gardener/gardener/tree/kubernetes-v1.24) branch. There should be similar branches in the provider extension repositories in case the work has been started already.

---

# Tasks

### Hyperkube

- [x] `hyperkube`: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/hyperkube-master/jobs/master-build-hyperkube-images-job/builds/13
  - Build new images for v1.24

### Gardener

- [x] `gardener`: https://github.com/gardener/gardener/pull/6023
  - Good to know/no action required
    - `dockershim` is now fully removed from `kubelet`, but we already only allow `containerd` for shoots >= `1.23`, so we should be prepared
    - The `LegacyServiceAccountTokenNoAutoGeneration` feature gate is beta, and enabled by default. (ref https://github.com/kubernetes/kubernetes/pull/108309)
  - Release-independent tasks
    - Allow instantiating v1.24 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/featuregates.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/shootsystem/shootsystem.go
    - Bump used Kubernetes version for local shoot and local e2e test
  - Release-specific tasks
    - The `.spec.loadBalancerIP` field is deprecated and will be removed in the future. Users should use provider-specific annotations when available (ref https://github.com/kubernetes/kubernetes/pull/107235). We have several usages in our code, do we need adaptation?
    - The `--pod-infra-container-image` kubelet flag is deprecated and will be removed in future releases (ref https://github.com/kubernetes/kubernetes/pull/108045)
    - The `metadata.selfLink` field is deprecated since 1.20 (now KAPI does not populate it anymore, ref https://github.com/kubernetes/kubernetes/pull/107527). We have some usages in `pkg/registry` in our code, probably we should remove them as well

### Cloud Controller Managers

- [x] `cloud-provider-aws`
  - Maintain `legacy-cloud-providers` and create `release-v1.24` branch from it (update container images and revendor latest Kubernetes patch): [`v1.24.0`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.24.0)
  - Maintain `release-v1.23` branch (update container images and revendor latest Kubernetes patch): [`v1.23.6`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.23.6)
  - Maintain `release-v1.22` branch (update container images and revendor latest Kubernetes patch): [`v1.22.9`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.22.9)
  - Maintain `release-v1.21` branch (update container images and revendor latest Kubernetes patch): [`v1.21.12`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.21.12)
- [x] `cloud-provider-azure`
  - Maintain `release-v1.22` branch (update container images and revendor latest Kubernetes patch): [`v1.22.9`](https://github.com/gardener/cloud-provider-azure/releases/tag/v1.22.9)
  - Maintain `release-v1.21` branch (update container images and revendor latest Kubernetes patch): [`v1.21.12`](https://github.com/gardener/cloud-provider-azure/releases/tag/v1.21.12)
- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.24` branch from it (update container images and revendor latest Kubernetes patch): [`v1.24.0`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.24.0)
  - Maintain `release-v1.23` branch (update container images and revendor latest Kubernetes patch): [`v1.23.6`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.23.6)
  - Maintain `release-v1.22` branch (update container images and revendor latest Kubernetes patch): [`v1.22.9`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.22.9)
  - Maintain `release-v1.21` branch (update container images and revendor latest Kubernetes patch): [`v1.21.12`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.21.12)

### Provider Extensions

- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/490
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/553
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24
  - Update `cloud-controller-manager` images for >= 1.24
  - Update `cloud-controller-manager` images for < 1.24: https://github.com/gardener/gardener-extension-provider-aws/pull/547
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/509
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24
  - Update `cloud-controller-manager` images for >= 1.24
  - Update `cloud-controller-manager` images for < 1.24: https://github.com/gardener/gardener-extension-provider-azure/pull/498
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/444
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24
  - Update `cloud-controller-manager` images for >= 1.24
  - Update `cloud-controller-manager` images for < 1.24: https://github.com/gardener/gardener-extension-provider-gcp/pull/437
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/453
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24
  - Update `cloud-controller-manager` images
- [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/239
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/211
  - Revendor `gardener/gardener` with support for 1.24 client creation
  - Update `README.md` with support for 1.24

**Comment by rfranzke** [comment]
All related PRs have been merged / tasks have been completed, hence
/close

**Comment by vlerenc** [comment]
Awesome!
