### ISSUE TITLE
Add check/metric to test API Server reachability from Shoot via kubernetes service

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener#628]
We want to have a check if a pod can reach the Shoot Kube API Server via the `kubernetes` service in the default namespace. The result of the check should lead to a metric, which again should raise a Prometheus alert, when the API Server is not reachable via this route.

The alert dependents on the alert `KubeApiserverDown` (which is evaluated by the Prometheus on the Seed based on the existence of Kube Api Server deployment replicas on the Seed) and have to be silenced in the Alertmanager when `KubeApiserverDown` alert is firing. Furthermore it is depending on the health of vpn (without vpn Prometheus can't scrape metrics which are collected on the Shoot nodes). This should be also considered.

This check is pretty similar to the solution, which should be provided for https://github.com/gardener/gardener/issues/604 and can also use the `blackbox-exporter` which should be deployed onto a Shoot node.

**Tasks**
- [ ] Add Prometheus scrape config to configure the blackbox exporter
- [ ] Define a Prometheus rule for the alert
- [ ] Adapt the Alertmanager routing tree to silence the alert when the parent alerts are firing.
