### ISSUE TITLE
Finalise "Bad Case" Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#6302]
# Stories
- As user I want my clusters to recover from a disaster, should it strike (downtime is aceptable).
- As operator I want an easy, fail-safe, automated, and fast means to migrate clusters if disaster strikes.
- As provider I want disaster recovery to provide a compliant and safe service.

# Motivation
In contrast to [GEP-7 Shoot Control Plane Migration "Good Case" Scenario](https://github.com/gardener/gardener/blob/master/docs/proposals/07-shoot-control-plane-migration.md) that deals with cooperative `seeds`, [GEP-17 Shoot Control Plane Migration "Bad Case" Scenario](https://github.com/gardener/gardener/blob/master/docs/proposals/17-shoot-control-plane-migration-bad-case.md) deals with non-cooperative `seeds`, i.e. a current (source) `seed` that is either down or cannot reach the `garden` cluster. Migration is still possible also in this case, but data loss is possible.

[GEP-17 Shoot Control Plane Migration "Bad Case" Scenario](https://github.com/gardener/gardener/blob/master/docs/proposals/17-shoot-control-plane-migration-bad-case.md) introduced an owner check mechanism to the `backup-restore` sidecar container of the `etcd-main` pod which is used to detect whether the `etcd-main` pod is running inside the `seed` which currently "owns" the `shoot` or not.  If the `etcd-main` pod is not running inside the  `seed` which "owns" the `shoot` (runs the control plane of the `shoot`), the owner check mechanism fails the readiness probe of the `etcd-main` pod by setting it to return `503`, then it restarts the `etcd` process so that communication to the `shoot`s `kube-apiserver` is stopped and eventually takes a "final snapshot".

However, the complexity introduced by the owner checks is very difficult to manage in a multi-node ETCD setup and brings few benefits, because for HA control planes "bad case" control plane migration would be triggered very rarely - only if a data center where a `seed` is hosted burns down or all the zones of a `seed` are completely isolated from the internet for a long period of time.

# Acceptance Criteria
- [x] CPM MVP that doesn't hinder https://github.com/gardener/backlog/issues/21 and brings adequate robustness
  <details open>
  <summary>Tasks</summary>

  - [x] Turn off owner checks in the `backup-restore` container when deploying the [etcd component](https://github.com/gardener/gardener/blob/01377c4f34de8f993f52c9274148c5ef74092c32/pkg/operation/botanist/etcd.go#L124-L129), if the `HAControlPlane` feature gate is enabled and the `shoot` is configured for multi-node ETCD deployment (https://github.com/gardener/etcd-druid/issues/107). The owner checks were initially introduced with https://github.com/gardener/etcd-backup-restore/pull/383.
  - [x] ~Use owner checks to trigger clean up of `shoot` control planes in case the corresponding `shoot` has been migrated to a new `seed` via the "bad case" control plane migration and the `gardenlet` in the source `seed` cannot reach the garden apiserver.~
  - [x] ~Add clean-up of control planes that have been migrated away from a `seed` cluster via the "bad case" control plane migration. This was previously intended to be done via a new resource (`shootleftover` as described in option [#3](https://github.com/gardener/gardener/issues/5173#issuecomment-995562573) of [this proposal](https://github.com/gardener/gardener/issues/5173#issuecomment-995562573)), but we have decided against adding additional complexity and will instead rely on the `cluster` resource as proposed in option [#1](https://github.com/gardener/gardener/issues/5173#issuecomment-995562573) of the same proposal.~

  **Results**
  A PoC was created for the above two tasks after which it turned out that the introduced complexity does not bring too much benefit, considering the overall Gardener HA topic. The next steps are to completely remove the owner checks from gardener and etcd `backup-restore` to reduce complexity even further.

  **Next Steps**
  - [x] Remove owner checks from extension controllers. #6973 
  - [x] Do not set owner checks on `Etcd` resources in all cases, not only when more than 1 replica is specified for the `etcd-main` `StatefulSet`. #6988
  - [x] Remove owner checks from `etcd-druid` https://github.com/gardener/etcd-druid/pull/461
  - [x] Remove owner checks from etcd `backup-restore` https://github.com/gardener/etcd-backup-restore/pull/555
  - [x] Wait until extensions are ready for the owner DNSRecord removal
    - gardener-extension-provider-aws vendors `gardener/gardener@v1.60` starting [v1.42.0](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.42.0)
    - gardener-extension-provider-gcp vendors `gardener/gardener@v1.60` starting [v1.28.0](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.28.0)
    - gardener-extension-provider-azure vendors `gardener/gardener@v1.60` starting [v1.34.0](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.34.0)
    - gardener-extension-provider-openstack vendors `gardener/gardener@v1.60` starting [v1.32.0](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.32.0)
    - gardener-extension-provider-alicloud vendors `gardener/gardener@v1.60` starting [v1.44.0](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.44.0)
    - gardener-extension-provider-vsphere vendors `gardener/gardener@v1.60` starting [v0.23.0](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.23.0)
    - gardener-extension-networking-cilium vendors `gardener/gardener@v1.60` starting [v1.22.0](https://github.com/gardener/gardener-extension-networking-cilium/releases/tag/v1.22.0)
    - gardener-extension-networking-calico vendors `gardener/gardener@v1.60` starting [v1.31.0](https://github.com/gardener/gardener-extension-networking-calico/releases/tag/v1.31.0)
    - gardener-extension-shoot-networking-filter vendors `gardener/gardener@v1.60` starting [v0.12.0](https://github.com/gardener/gardener-extension-shoot-networking-filter/releases/tag/v0.12.0)
    - gardener-extension-shoot-networking-problemdetector vendors `gardener/gardener@v1.60` starting [v0.11.0](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/releases/tag/v0.11.0)
    - gardener-extension-os-ubuntu vendors `gardener/gardener@v1.60` starting [v1.20.0](https://github.com/gardener/gardener-extension-os-ubuntu/releases/tag/v1.20.0)
    - gardener-extension-os-gardenlinux vendors `gardener/gardener@v1.60` starting [v0.16.0](https://github.com/gardener/gardener-extension-os-gardenlinux/releases/tag/v0.16.0)
    - gardener-extension-os-suse-chost vendors `gardener/gardener@v1.60` starting [v1.20.0](https://github.com/gardener/gardener-extension-os-suse-chost/releases/tag/v1.20.0)
    - gardener-extension-os-coreos vendors `gardener/gardener@v1.60` starting [v1.16.0](https://github.com/gardener/gardener-extension-os-coreos/releases/tag/v1.16.0)
    - gardener-extension-shoot-dns-service vendors `gardener/gardener@v1.60` starting [v1.29.0](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.29.0)
    - gardener-extension-shoot-cert-service vendors `gardener/gardener@v1.60` starting [v1.28.0](https://github.com/gardener/gardener-extension-shoot-cert-service/releases/tag/v1.28.0)
    - gardener-extension-shoot-oidc-service vendors `gardener/gardener@v1.60` starting [v0.15.0](https://github.com/gardener/gardener-extension-shoot-oidc-service/releases/tag/v0.15.0)
    - gardener-extension-runtime-gvisor vendors `gardener/gardener@v1.60` starting [v0.9.0](https://github.com/gardener/gardener-extension-runtime-gvisor/releases/tag/v0.9.0)
    - gardener-extension-registry-cache vendors `gardener/gardener@v1.60` starting [v?]()
    - gardener-extension-shoot-lakom-service vendors `gardener/gardener@v1.60` starting v0.1.0
    - gardener-extension-shoot-auditlog-service vendors `gardener/gardener@v1.60` starting v0.3.0
  - [x] Remove Seed `spec.settings.ownerChecks` field and clean up the owner DNSRecord handling in gardener/gardener 
     - [x] Make the Seed `.spec.settings.ownerChecks` field as deprecated: https://github.com/gardener/gardener/pull/7748
     - [x] Lock the Seed `.spec.settings.ownerChecks` field to false and adapt the defaulting: https://github.com/gardener/gardener/pull/7909
     - [x] Remove deployment of the special owner `DNSRecord` during shoot reconciliation (https://github.com/gardener/gardener/pull/7005) and set the `ownerChecks` field to nil: https://github.com/gardener/gardener/pull/7951
     - [x] Drop the `ownerChecks` field from the API: https://github.com/gardener/gardener/pull/8109
  - [x] When revendoring `gardener/gardener` v1.60 in extension controllers the RBAC for `DNSRecords` will not be required by them with the exception of the `DNSRecord` controller (which resides in the `*-provider` extensions).
    - [x] Remove DNSRecord RBAC from [extension-networking-cilium](https://github.com/gardener/gardener-extension-networking-cilium): https://github.com/gardener/gardener-extension-networking-cilium/pull/157
    - [x] Remove DNSRecord RBAC from [extension-networking-calico](https://github.com/gardener/gardener-extension-networking-calico): https://github.com/gardener/gardener-extension-networking-calico/pull/237
    - [x] Remove DNSRecord RBAC from [extension-shoot-networking-filter](https://github.com/gardener/gardener-extension-shoot-networking-filter): https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/55
    - [x] Remove DNSRecord RBAC from [extension-shoot-networking-problem-detector](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector): https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/53
    - [x] Remove DNSRecord RBAC from [extension-os-ubuntu](https://github.com/gardener/gardener-extension-os-ubuntu): https://github.com/gardener/gardener-extension-os-ubuntu/pull/74
    - [x] Remove DNSRecord RBAC from [extension-os-gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux): https://github.com/gardener/gardener-extension-os-gardenlinux/pull/72
    - [x] Remove DNSRecord RBAC from [extension-os-suse-chost](https://github.com/gardener/gardener-extension-os-suse-chost): https://github.com/gardener/gardener-extension-os-suse-chost/pull/79
    - [x] Remove DNSRecord RBAC from [extension-os-coreos](https://github.com/gardener/gardener-extension-os-coreos): https://github.com/gardener/gardener-extension-os-coreos/pull/55
    - [x] Remove DNSRecord RBAC from [extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service): the shoot-dns-service still requires the RBAC for `dnsrecords`. The dependncy on the owner DNSRecords was removed: https://github.com/gardener/gardener-extension-shoot-dns-service/pull/171
    - [x] Remove DNSRecord RBAC from [extension-shoot-cert-service](https://github.com/gardener/gardener-extension-shoot-cert-service): https://github.com/gardener/gardener-extension-shoot-cert-service/pull/145
    - [x] Remove DNSRecord RBAC from [extension-shoot-oidc-service](https://github.com/gardener/gardener-extension-shoot-oidc-service): https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/90
    - [x] Remove DNSRecord RBAC from [extension-runtime-gvisor](https://github.com/gardener/gardener-extension-runtime-gvisor): https://github.com/gardener/gardener-extension-runtime-gvisor/pull/76
    - [x] Remove DNSRecord RBAC from [extension-registry-cache](https://github.com/gardener/gardener-extension-registry-cache): https://github.com/gardener/gardener-extension-registry-cache/pull/13

</details>
  
- [x] Future improvements
  <details open>
  <summary>Tasks</summary>

  - [x] ~In the future, if there is actual need of "bad case" control plane migration also for HA `shoot` control planes and multi-node/clustered ETCD the owner check in `gardenlet` could be extended to also instruct `backup-restore` to take a final snapshot. This has the draw-back that it would require `gardenlet` to be running (in HA), but that's useful also in general for the overal Gardener HA topic.~
  - [x] Additionally, when end users can enable HA control planes and use that feature to handle nearly all cases of disaster recovery, supporting owner checks for single node ETCD becomes less necessary. This means that once the option is available to switch to HA control planes, users should be instructed to use that if they require the highest possible degree of availability (instead of implicitely relying on the "bad case" control plane migration). Then, the owner checks can be entirely removed from `etcd-backup-restore`. Please note that we could still use "bad case" control plane migration in very rare corner cases, but we would not be able to guarantee final snapshots of ETCD data (we cannot guarantee that anyway in general).

  </details>

# Enhancement/Implementation Proposal
- https://github.com/gardener/gardener/blob/master/docs/proposals/17-shoot-control-plane-migration-bad-case.md

**Comment by timebertt** [comment]
I think, the `Seed.spec.settings.ownerChecks` section and corresponding handling can also be removed once the other tasks are done.
@plkokanov do you want to add this to the task list?

**Comment by plkokanov** [comment]
@timebertt yep, I was planning to do it directly as part of `Remove deployment of the special owner DNSRecord during shoot reconciliation.` But I will list it separately in the issue.

**Comment by rfranzke** [comment]
All tasks have been completed.
/close
