### ISSUE TITLE
Automated g/g upgrade PRs in extension repositories after a new release of g/g

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#6328]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
Experiment and investigate if g/g upgrade PRs on extension repositories can be automatically created after new releases of g/g. 

Here are some points that would have to be considered (not an extensive list):
- Should such PRs be opened on all releases or just major releases.
- Automatic revendoring might not work well when external modules are updated as well.
- Changes to interfaces could require manual work to adapt the automatically created upgrade PR (but I guess this is acceptable).
- Most likely automatic PRs should only be done on extension repositories from the gardener org

**Why is this needed**:
Automatically opening g/g upgrade PRs on extension repositories after g/g releases can save some time and can serve as a reminder to keep gardener up to date in those repositories, so that required changes after revendoring (if any) are minimal.

**Tasks**:
- [ ] Research a better way for distributing hack scripts (git subtree). 
  Currently we need a github action that runs `make revendor` for dependabot PRs because we use `make revendor` to distribute hack scripts (ref https://github.com/gardener/gardener-extension-os-gardenlinux/blob/08055c269c2974b6d7083417b297710b5e70f7f3/Makefile#LL72C1-L75C105). See https://github.com/gardener/gardener-extension-os-gardenlinux/pull/86#issuecomment-1479279913 for more details.
- [ ] Enable dependabot on extension repositories:
  - [x] gardener/gardener-extension-os-gardenlinux: https://github.com/gardener/gardener-extension-os-gardenlinux/pull/81
  - [x] gardener/gardener-extension-os-suse-chost: https://github.com/gardener/gardener-extension-os-suse-chost/pull/88
  - [x] gardener/gardener-extension-os-ubuntu: https://github.com/gardener/gardener-extension-os-ubuntu/pull/84
  - [x] gardener/gardener-extension-os-coreos: https://github.com/gardener/gardener-extension-os-coreos/pull/66
  - [x] gardener/gardener-extension-registry-cache: https://github.com/gardener/gardener-extension-registry-cache/pull/28
  - [x] gardener/gardener-extension-networking-calico: https://github.com/gardener/gardener-extension-networking-calico/pull/281
  - [x] gardener/gardener-extension-networking-cilium: https://github.com/gardener/gardener-extension-networking-cilium/pull/200
  - [x] gardener/gardener-extension-shoot-networking-filter: https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/74
  - [x] gardener/gardener-extension-shoot-networking-problemdetector: https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/80
  - [x] gardener-extension-shoot-networking-traffic-gauger: https://github.com/gardener/gardener-extension-shoot-networking-traffic-gauger/commit/e8c737479127503b78300827127fdc441dba2e5b
  - [x] gardener/gardener-extension-runtime-gvisor: https://github.com/gardener/gardener-extension-runtime-gvisor/pull/86
  - [x] gardener/gardener-extension-shoot-cert-service: https://github.com/gardener/gardener-extension-shoot-cert-service/pull/177
  - [x] gardener/gardener-extension-shoot-dns-service: https://github.com/gardener/gardener-extension-shoot-dns-service/pull/224
  - [ ] gardener/gardener-extension-provider-gcp:
  - [ ] tbd

**Comment by timebertt** [comment]
Tools that might be helpful for this or at least worth looking into:
- https://github.com/renovatebot/renovate
- https://github.com/dependabot

**Comment by plkokanov** [comment]
/remove-lifecycle stale
@AleksandarSavchev and @Kostov6 are currently experimenting with dependabot and renovate bot to see if this automated upgrade PRs can be done.

**Comment by Kostov6** [comment]
After some experimentation dependabot seems to be the better solution than renovate. 
1. It can run custom scripts after dependabot’s own running of `go mod tidy && go mod vendor`. This is needed because for some components those two commands are not enough and `make revendor` is required to be used (for example to change files to have correct permissions)
2. It is more widely adopted

There is only one problem that remains to be solved due to the `client-go` replace directive in the `go-mod` files. It is a known [issue](https://github.com/gardener/gardener/issues/6807). Because dependabot does not change replaces in `go.mod` they need to be updated manually. For now the replace of `client-go` can not be removed due to some required changes that could take several months so we propose a workaround by using a custom script [`client_go_replace.sh`](https://github.com/Kostov6/gardener-extension-os-gardenlinux/blob/master/.github/client_go_replace.sh):
1. We take the updated gardener version
2. We `curl`  the `go.mod` file of that version using autogenerated [Github token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api)
3. In this file we take the `client-go`'s replaced version
4. We edit the extension's `go.mod` file to use this for it's `client-go` repace

Dependabot's configuration used for this Proof of concept:
- [`dependabot.yml`](https://github.com/Kostov6/gardener-extension-os-gardenlinux/blob/master/.github/dependabot.yml)
- [github actions config file](https://github.com/Kostov6/gardener-extension-os-gardenlinux/blob/master/.github/workflows/vendor_gardener.yaml)

Example generation of pr: [Bump github.com/gardener/gardener from 1.60.0 to 1.64.0 in gardener-extension-os-gardenlinux](https://github.com/Kostov6/gardener-extension-os-gardenlinux/pull/2)
(Note: Several reopens of the PR were needed because a incorrect order of command execution in `make revendor` crashed the script and after a fix it worked as expected)
The expected `client-go` replace can be seen [here](https://github.com/Kostov6/gardener-extension-os-gardenlinux/pull/2/commits/ddb50da2a2dcf0ee2a0a2ce5bde1a0c36220c5ce)

**Comment by rfranzke** [comment]
Not related to your findings @Kostov6, but just to document here as well. I have already expressed these concerns multiple times to your colleagues: I have doubts that opening such automatic upgrade PRs in all extensions would be very helpful for the extension developers. In the end, most of the new Gardener versions require adaptations in the code, and only the minority is about "just revendor and be done". These manual tasks cannot be automated and always a human to take over. In this light, the value added by the PRs opened by dependabot is negligible (for me).
Given that all of this does not seem to be very straight forward and requires quite some configuration in each and every extension repository as visible in your PoC, maybe you want to discuss again whether this should really be put into practice.
A compromise could be to only do it for non-provider extensions, since here the necessity for manual adaptations of the implementations seems to be rather rare. Anyways, your call.

**Comment by plkokanov** [comment]
I think this could be useful so that fixes in the extension libraries e.g.: https://github.com/gardener/gardener/pull/7179/files can be revendored quicker.
Additionally, I feel that even if there are any manual changes that will be required, just automatically opening a PR and revendoring could still save a bit of work. It also servers as a reminder to always keep the extensions revendored with the most recent version of gardener. 
In the end though, I guess it mostly depends on the extension maintainers whether they implement this or not.

As a side note, the script that @Kostov6 created for the `replace` directive for `client-go` could help https://github.com/gardener/gardenctl-v2 (at least until https://github.com/gardener/gardener/issues/6807 is resolved), as dependabot is already used there . From what I understand, they maintain the `client-go` `replace` directive manually after each automatic PR is opened by dependabot. /cc @petersutter

**Comment by plkokanov** [comment]
After a short internal discussion we decided to try out the dependabot configuration presented by @Kostov6 in the https://github.com/gardener/gardener-extension-os-gardenlinux extension as a start. After a couple release cycles we will weigh in the benefits vs cons. 

As mentioned above, one of the main caveats of the current approach is that the dependabot configuration has to be done in each repository and the [`dependabot.yaml`](https://github.com/Kostov6/gardener-extension-os-gardenlinux/blob/master/.github/workflows/vendor_gardener.yaml) and the [github actions config file](https://github.com/Kostov6/gardener-extension-os-gardenlinux/blob/master/.github/workflows/vendor_gardener.yaml) need to be copied over. It would be better if those files could be kept in one place. However, we can decide whether to tackle this problem once we have a bit more experience with the automatic revendoring in https://github.com/gardener/gardener-extension-os-gardenlinux.

**Comment by acumino** [comment]
After this https://github.com/gardener/gardener/pull/8248 PR special handling for `client.go` replace in dependabot configuration can be dropped.

**Comment by ialidzhikov** [comment]
In our last retro we discussed that dependabot helps an extension developer. I experienced it myself with the registy-cache extension. The most useful thing is that you can push adaptations (if needed) to the dependabot's PR and then you can approve && merge. You don't need another person for review which was the problem in most of the cases so far.

Maybe we can directly proceed with the enablement on all extensions instead of first investing in the `Research a better way for distributing hack scripts (git subtree)`. @plkokanov @rfranzke WDYT?

**Comment by rfranzke** [comment]
> The most useful thing is that you can push adaptations (if needed) to the dependabot's PR and then you can approve && merge. You don't need another person for review which was the problem in most of the cases so far.

Not sure if this is a good thing, but I guess there's not much we can do to reasonably prevent it. For small things, it's fine, but larger changes might want to get reviewed. Anyways, I'm not against continuing with the topic.
