### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.25”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#6567]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.25 has been released, find the changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md

Work can be started and pushed to the [`kubernetes-v1.25`](https://github.com/gardener/gardener/tree/kubernetes-v1.25) branch. There should be similar branches in the provider extension repositories in case the work has been started already.

#### Note:  Seeds do not support `v1.25` yet (Tracked separately in #6893 ) because of:
- ~https://github.com/gardener/etcd-druid/issues/429~
- https://github.com/gardener/hvpa-controller/issues/104

---

# Tasks

### Hyperkube
- [x] `hyperkube`: https://github.com/gardener/hyperkube/releases/tag/v1.25.0
  - Build new image for v1.25 

### Gardener

- [x] `gardener`: #6638 
  - Good to know/no action required
    - PodSecurityPolicy is Removed, Pod Security Admission graduates to Stable. Already tracked in #5250 
    - Ephemeral Containers Graduate to Stable [Ref](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#ephemeral-containers-graduate-to-stable)
    - Kube-proxy images are now based on distroless images. [Ref](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#kube-proxy-images-are-now-based-on-distroless-images)
  - Release-independent tasks
    - Allow instantiating v1.25 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/featuregates.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/shootsystem/shootsystem.go > `no changes`
    - Bump used Kubernetes version for local shoot and local e2e test
  - Release-specific tasks
    - [x] Moved container registry service from k8s.gcr.io to registry.k8s.io. [Ref](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#moved-container-registry-service-from-k8sgcrio-to-registryk8sio) > #6591 
    - [x] APIs deprecated or promoted: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
      - [x] Handle `PodDisruptionBudget` `policy/v1`
      - [x] Handle `HorizontalPodAutoscaler` `autoscaling/v2`
      - [x] Use v1 version for kube-scheduler config
      - [x] Handle pod-security.admission.config.k8s.io/v1 for clusters >= 1.25 > https://github.com/gardener/gardener/pull/6668
  - Release: [`v1.56.0`](https://github.com/gardener/gardener/releases/tag/v1.56.0)

### Cloud Controller Managers

- [x] `cloud-provider-aws`
  - Maintain `legacy-cloud-providers` and create `release-v1.25` branch from it (update container images and revendor latest Kubernetes patch): [`v1.25.2`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.25.2)
  - Maintain `release-v1.24` branch (update container images and revendor latest Kubernetes patch): [`v1.24.6`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.24.6)
  - Maintain `release-v1.23` branch (update container images and revendor latest Kubernetes patch): [`v1.23.12`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.23.12)
  - Maintain `release-v1.22` branch (update container images and revendor latest Kubernetes patch): [`v1.22.15`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.22.15)
- [x] `cloud-provider-azure`
  - Maintain `release-v1.22` branch (update container images and revendor latest Kubernetes patch): [`v1.22.15`](https://github.com/gardener/cloud-provider-azure/releases/tag/v1.22.15)
- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.25` branch from it (update container images and revendor latest Kubernetes patch): [`v1.25.2`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.25.2)
  - Maintain `release-v1.24` branch (update container images and revendor latest Kubernetes patch):  [`v1.24.6`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.24.6)
  - Maintain `release-v1.23` branch (update container images and revendor latest Kubernetes patch): [`v1.23.12`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.23.12)
  - Maintain `release-v1.22` branch (update container images and revendor latest Kubernetes patch): [`v1.22.15`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.22.15)

### Provider Extensions

- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/537
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-alicloud`
    - https://github.com/gardener/gardener-extension-provider-alicloud/pull/531
    - https://github.com/gardener/gardener-extension-provider-alicloud/pull/530
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-alicloud/pull/534
  - Update `README.md` with support for 1.25
  - Release: [`v1.41.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.41.0)
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/624
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-aws` 
    - https://github.com/gardener/gardener-extension-provider-aws/pull/600
    - https://github.com/gardener/gardener-extension-provider-aws/pull/626
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-aws/pull/609
  - Update `README.md` with support for 1.25
  - Update `cloud-controller-manager` images
  - Release: [`v1.39.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.39.0)
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/575
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-azure`
    - https://github.com/gardener/gardener-extension-provider-azure/pull/569
    - https://github.com/gardener/gardener-extension-provider-azure/pull/568
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-azure/pull/572
  - Update `README.md` with support for 1.25
  - Update `cloud-controller-manager` images
  - Release: [`v1.31.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.31.0)
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/498
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-gcp` 
    - https://github.com/gardener/gardener-extension-provider-gcp/pull/488
    - https://github.com/gardener/gardener-extension-provider-gcp/pull/502
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-gcp/pull/496
  - Update `README.md` with support for 1.25
  - Update `cloud-controller-manager` images
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/502
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-openstack`
    - https://github.com/gardener/gardener-extension-provider-openstack/pull/491
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-openstack/pull/495
  - Update `README.md` with support for 1.25
  - Update `cloud-controller-manager` images
  - Release: [`v1.29.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.29.0)
- [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/305
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-vsphere`
    - https://github.com/gardener/gardener-extension-provider-vsphere/pull/297
    - https://github.com/gardener/gardener-extension-provider-vsphere/pull/307
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-vsphere/pull/303
  - Update `README.md` with support for 1.25
  - Release: [`v0.20.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.20.0)
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/232
  - Upgrade `machine-controller-manager` and `machine-controller-manager-provider-equinix-metal`
    - https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/228 
  - Revendor `gardener/gardener` with support for 1.25 client creation
    - https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/230
  - Update `README.md` with support for 1.25
  - Release : [`v2.5.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.5.0)

### Networking Extensions

- [x] `networking-calico`: Handle `PodDisuptionBudget` `policy/v1` and Vendor `gardener@1.54` (For changes in the PSP helper function to support k8s v1.25) > https://github.com/gardener/gardener-extension-networking-calico/pull/210
  - Release: [`v1.27.0`](https://github.com/gardener/gardener-extension-networking-calico/releases/tag/v1.27.0) 
- [x] `networking-cilium`: Handle `PodDisuptionBudget` `policy/v1` and Vendor `gardener@1.54` (For changes in the PSP helper function to support k8s v1.25) > https://github.com/gardener/gardener-extension-networking-cilium/pull/126
  - Release: [`v1.17.0`](https://github.com/gardener/gardener-extension-networking-cilium/releases/tag/v1.17.0)

### Machine Controller Manager

- [x] Handle `PodDisruptionBudget` `policy/v1` > https://github.com/gardener/machine-controller-manager/pull/744
  - Release: [`v0.47.0`](https://github.com/gardener/machine-controller-manager/releases/tag/v0.47.0) 
 
### Shoot Extensions

- [x] `extensions-networking-problem-detector`: Handle `PodDisuptionBudget` `policy/v1` and Vendor `gardener@1.54` (For changes in the PSP helper function to support k8s v1.25) > https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/29 
  - Release: [`v0.7.0`](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/releases/tag/v0.7.0)
- [x] `extensions-networking-filter`: Handle `PodDisuptionBudget` `policy/v1` and Vendor `gardener@1.54` (For changes in the PSP helper function to support k8s v1.25) > https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/32 
  - Release: [`v0.7.0`](https://github.com/gardener/gardener-extension-shoot-networking-filter/releases/tag/v0.7.0)
- [x] `gardener-extension-shoot-oidc-service`: Handle `PodDisuptionBudget` `policy/v1` and Vendor `gardener@1.54` > https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/64
  - Release: [`v0.10.0`](https://github.com/gardener/gardener-extension-shoot-oidc-service/releases/tag/v0.10.0) 
- [x] `extensions-shoot-dns-service`: Handle `PodDisuptionBudget` `policy/v1` https://github.com/gardener/gardener-extension-shoot-dns-service/pull/161
  - Release: [`v1.25.0`](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.25.0)

**Comment by ialidzhikov** [comment]
> Maintain legacy-cloud-providers and create release-v1.25 branch from it (update container images and revendor latest Kubernetes patch):

With 1.25 the folks (@dkistner and @kon-angelo) wanted to try out the upstream CCM - ref https://github.com/gardener/gardener-extension-provider-aws/issues/577.

**Comment by rfranzke** [comment]
@dkistner @kon-angelo Can this switch to the OOT CCM also be done later (after 1.25 is already supported) so that we get rid this dependency on the tasks?

**Comment by kon-angelo** [comment]
The argument in the past was to not perform the upgrade in the middle of kubernetes releases so that we don't have any weird or unexpected behaviour due to the transition. 

In general OOT should be a superset of the behavior of the in-tree CCM. In practice if we go though with upgrade in-tree now, we would need to verify one extra transition (in-tree 1.25 -> oot 1.25) in addition to the others, but I do not think it would be that much extra effort.

**Comment by rfranzke** [comment]
OK, cc @shafeeqes. Let's see how it goes then and talk about this once we have finished the other items from above list.

**Comment by ialidzhikov** [comment]
> With 1.25 the folks (@dkistner and @kon-angelo) wanted to try out the upstream CCM - ref [gardener/gardener-extension-provider-aws#577](https://github.com/gardener/gardener-extension-provider-aws/issues/577).

I was actually thinking about this topic and I guess it will be best if you @dkistner and @kon-angelo can handle this with a feature gate so we can decouple it from the 1.25 topic. At the end, our final goal is a controlled rollout and a feature gate should do the trick. WDYT?

**Comment by kon-angelo** [comment]
@ialidzhikov I think that is a great idea. If my previous comment was not clear as to its intentions, I agree that we can and should decouple it from gardener's 1.25 support and doing it via feature gate could be a good way to introduce the change.

**Comment by shafeeqes** [comment]
/close
All tasks are completed.

**Comment by ialidzhikov** [comment]
Shouldn't we keep it open for 
> Please note that Gardener does not support 1.25 seeds yet.

?

Ref https://github.com/gardener/gardener/blob/v1.57.1/docs/usage/supported_k8s_versions.md#seed-cluster-versions

Or is it tracked somewhere else?

**Comment by shafeeqes** [comment]
> Shouldn't we keep it open for
> 
> > Please note that Gardener does not support 1.25 seeds yet.
> 
> ?
> 
> Ref https://github.com/gardener/gardener/blob/v1.57.1/docs/usage/supported_k8s_versions.md#seed-cluster-versions
> 
> Or is it tracked somewhere else?

Opened a new issue. We can keep this closed.

**Comment by shafeeqes** [comment]
We need to use cluster autoscaler v1.25 for 1.25 Shoots,
Current version has logs,
```
W1214 13:53:18.709613       1 reflector.go:324] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
E1214 13:53:18.709636       1 reflector.go:138] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309: Failed to watch *v1beta1.PodDisruptionBudget: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
```
/assign @himanshu-kun @rishabh-11

**Comment by shafeeqes** [comment]
/close
https://github.com/gardener/gardener/pull/7209 is merged.
