### ISSUE TITLE
☂️ Improve Gardener Operator

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7016]
**How to categorize this issue?**

/area dev-productivity delivery high-availability security open-source
/kind enhancement

As of today, Gardener has no notion of managing any components running in the garden cluster. As a consequence, human operators have to manually deploy the "garden system components" (`vertical-pod-autoscaler`, `hvpa-controller`, `etcd-druid`, `nginx-ingress`) and the "virtual garden control plane components" (`etcd`/`backup-restore`, `kube-apiserver`, `kube-controller-manager`) as well as the "Gardener control plane components".
However, logically these processes are quite similar to what we have already implemented in the `gardenlet` for seed or shoot clusters.
The idea of the `gardener-operator` component is re-using existing code and sharing it with `gardenlet` so that the needed components can be made available more easily in all environments.

As part of this, `gardener-resource-manager` is becoming a central "garden system component" as well since it has a lot of features like token invalidation, seccomp defaulting, token requesting, HA config injection, etc.

## Tasks

- Initial skaffolding and introduction of new component
  - [x] https://github.com/gardener/gardener/pull/7009
- Manage Garden System Components
  - [x] Fine-grained `PriorityClass`es: https://github.com/gardener/gardener/pull/7009
  - [x] `gardener-resource-manager`: https://github.com/gardener/gardener/pull/7009
  - [x] `vertical-pod-autoscaler`: https://github.com/gardener/gardener/pull/7009
  - [x] `hvpa-controller`: https://github.com/gardener/gardener/pull/7048
  - [x] `etcd-druid`: https://github.com/gardener/gardener/pull/7048
  - [x] `istio`: https://github.com/gardener/gardener/pull/7817
- Manage Virtual Garden Control Plane Components
  - [x] `etcd`/`backup-restore` (via `Etcd` custom resource): https://github.com/gardener/gardener/pull/7067
  - [x] `kube-apiserver` exposure
    - [x] via `LoadBalancer` service: https://github.com/gardener/gardener/pull/7238
    - [x] via `Istio`: https://github.com/gardener/gardener/pull/7953
    - [x] https://github.com/gardener/gardener/pull/8156
    - [x] https://github.com/gardener/gardener/pull/8302
  - [x] `kube-apiserver`: https://github.com/gardener/gardener/pull/7730
    - Prerequisites / related upfront work:
      - [x] https://github.com/gardener/gardener/pull/7242
      - [x] https://github.com/gardener/gardener/pull/7243
        - [x] https://github.com/gardener/gardener/pull/7710
      - [x] https://github.com/gardener/gardener/pull/7258
      - [x] https://github.com/gardener/gardener/pull/7498
      - [x] https://github.com/gardener/gardener/pull/7518
      - [x] https://github.com/gardener/gardener/pull/7558
      - [x] https://github.com/gardener/gardener/pull/7567
      - [x] https://github.com/gardener/gardener/pull/7573
        - [x] https://github.com/gardener/gardener/pull/7687
      - [x] https://github.com/gardener/gardener/pull/7682
      - [x] https://github.com/gardener/gardener/pull/7693
    - Follow-up work:
      - [x] https://github.com/gardener/gardener/pull/7734
      - [x] https://github.com/gardener/gardener/pull/7735
      - [x] https://github.com/gardener/gardener/pull/7877
  - [x] `virtual-garden-gardener-resource-manager`: https://github.com/gardener/gardener/pull/7881
  - [x] `kube-controller-manager`: https://github.com/gardener/gardener/pull/7931
    - Prerequisites / related upfront work:
      - [x] https://github.com/gardener/gardener/pull/7858
      - [x] https://github.com/gardener/gardener/pull/7887
- Manage Gardener Control Plane Components
  - [x] `gardener-{apiserver,controller-manager,...}`: https://github.com/gardener/gardener/pull/8309
    - Prerequisites / related upfront work:
      - [x] https://github.com/gardener/gardener/pull/7998
      - [x] https://github.com/gardener/gardener/pull/8234
      - [x] https://github.com/gardener/gardener/pull/8215
        - [x] https://github.com/gardener/gardener/pull/8235
      - [x] https://github.com/gardener/gardener/pull/8244
        - [x] https://github.com/gardener/gardener/pull/8251
      - [x] https://github.com/gardener/gardener/pull/8282
        - [x] https://github.com/gardener/gardener/pull/8283
      - [x] https://github.com/gardener/gardener/pull/8262
        - [x] https://github.com/gardener/gardener/pull/8265 
      - [x] https://github.com/gardener/gardener/pull/8276
  - [x] https://github.com/gardener/gardener/pull/8396
- Manage Garden Observability Components
  - [x] `nginx-ingress-controller` (~[or ideally `istio` only](https://github.com/gardener/gardener/issues/7232)~): https://github.com/gardener/gardener/pull/7945
  - [x] `kube-state-metrics`: https://github.com/gardener/gardener/pull/7836
  - [x] `fluent-operator`: https://github.com/gardener/gardener/pull/8240
  - [x] `vali`: https://github.com/gardener/gardener/pull/8240
  - [x] `plutono`: https://github.com/gardener/gardener/pull/8301
  - [x] `gardener-metrics-exporter`: https://github.com/gardener/gardener/pull/8419
- Miscellaneous
  - [x] https://github.com/gardener/gardener/pull/7859
  - [x] https://github.com/gardener/gardener/pull/8158
    - [x] https://github.com/gardener/gardener/pull/8346
  - [x] https://github.com/gardener/gardener/pull/8439
  - [x] Add support for credentials rotation (similar to how it works for [`Shoot`s](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_credentials_rotation.md)): https://github.com/gardener/gardener/pull/7144
    - [x] https://github.com/gardener/gardener/pull/8393
  - [x] Extended validation (deletion protection, etc.): https://github.com/gardener/gardener/pull/7144
  - [x] https://github.com/gardener/gardener/pull/7225
  - [x] https://github.com/gardener/gardener/issues/6896
  - [x] https://github.com/gardener/gardener/pull/8238
    - [x] https://github.com/gardener/gardener/pull/8279
  - [x] https://github.com/gardener/gardener/pull/8413
  - [x] https://github.com/gardener/gardener/pull/8433

❗️ Please note ❗️
- It is NOT planned (at least for the foreseeable future until this component graduates) to manage any additional addons deployed to the garden cluster (Gardener dashboard, audit log components, ...) or any extensions.
- Managing the `gardenlet` via `gardener-operator` is NOT planned as well, but could be done. However, in production scenarios, the garden cluster is typically not a seed cluster at a same time, and generally we cannot assume that `gardener-operator` has network connectivity to the clusters where a `gardenlet` should be deployed to. Hence, managing the `gardenlet` has a low priority (if any at all).

**Comment by shreyas-s-rao** [comment]
@rfranzke can you please also add the `HA`-related task(s) to the checklist in this issue? For instance, specifying `highAvailability` spec separately for `runtimeCluster` and `virtualCluster` in the `Garden` spec.

[Ref](https://github.com/gardener/gardener/pull/7067#discussion_r1033172513)

**Comment by rfranzke** [comment]
> @rfranzke can you please also add the `HA`-related task(s) to the checklist in this issue? For instance, specifying `highAvailability` spec separately for `runtimeCluster` and `virtualCluster` in the `Garden` spec.
> 
> [Ref](https://github.com/gardener/gardener/pull/7067#discussion_r1033172513)

Done, however there won't be `highAvailability` configuration for the `runtimeCluster` (we already have `zones` like in `Seed`s)

**Comment by rfranzke** [comment]
The work on this is currently paused in favor of https://github.com/gardener/gardener/issues/7352.

**Comment by rfranzke** [comment]
/assign @timuthy 
for the istio task above

**Comment by rfranzke** [comment]
All tasks have been completed.
/close
