### ISSUE TITLE
☂️ [GEP-21] IPv6 Single-Stack Support in Local Gardener

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#7051]
**How to categorize this issue?**

/area networking
/kind enhancement

This is an umbrella issue for implementing the changes proposed in [GEP-21 IPv6 Single-Stack Support in Local Gardener](https://github.com/gardener/gardener/blob/master/docs/proposals/21-ipv6-singlestack-local.md).

## Tasks

- [x] https://github.com/gardener/gardener/pull/7050
- [x] https://github.com/gardener/gardener/pull/7288
  - add the `IPv6SingleStack` feature gate
  - add `ipFamilies` field with defaulting (default to `["IPv4"]`) and validation (only single-stack can be specified, IPv6 single-stack can only be specified if feature gate is enabled)
  - validate that all CIDRs (`Shoot.spec.networking.{pods,services,nodes}`, `Seed.spec.networks.{nodes,pods,services,blockCIDRs}`, `Seed.spec.networks.shootDefaults.{pods,services}`, `Network.spec.{pod,service}CIDR`) match the selected IP family
- [x] https://github.com/gardener/gardener/pull/7353
- [x] https://github.com/gardener/gardener/pull/7246
  - allow specifying `AAAA` record type
  - allow specifying IPv6 values for `AAAA` records
  - provider-local: handle `DNSRecords` with type `AAAA`
- [x] https://github.com/gardener-community/dev-box-gcp/pull/1
  - add an easy way to bring up a Linux dev box with IPv4/IPv6 dual-stack connectivity
  - this allows everybody to develop and verify changes for IPv6 independent from their dev machine OS and internet connectivity
- [x] https://github.com/gardener/gardener/pull/7381
- [x] https://github.com/gardener/gardener/pull/7388
  - configure kind cluster and calico installation for IPv6 single-stack
  - `make kind-up` brings up IPv6 single-stack kind cluster
- [x] https://github.com/gardener/ci-infra/issues/619
- [x] https://github.com/gardener/gardener/pull/7686
- [x] https://github.com/gardener/gardener/pull/7698
- [x] https://github.com/gardener/gardener/pull/7561
  - provider-local: use IPv6 host address in service and ingress controller (important for bringing up istio ingress)
  - gardenlet: add `IPv6` equivalents of static CIDRs in `NetworkPolicies` (e.g., `allow-to-public-networks`)
  - `make gardener-up` brings up IPv6 single-stack seed
- [x] https://github.com/gardener/gardener-extension-networking-calico/pull/301:
  - handle `Shoot` `ipFamilies`
  - extend `NetworkConfig` API (types, defaulting, validation) as needed
  - configure calico-node and IPAM according to `Network.spec.ipFamilies` and `NetworkConfig`
- [x] https://github.com/gardener/vpn2/pull/45
  - allow configuring IPv6 networking
- [x] https://github.com/gardener/gardener/pull/8574
  - gardenlet: handle `Shoot` `ipFamilies`
  - enable kernel settings for IPv6 forwarding on shoot worker nodes (similar to https://github.com/gardener/gardener/pull/7046)
  - configure control plane components according to `ipFamilies`: `kube-apiserver`, `kube-controller-manager`, `vpn-seed-server`
  - configure shoot system components according to `ipFamilies`: `kube-proxy`, `apiserver-proxy`
  - configure `EnvoyFilters` to be applied to IPv6 listeners as well
  - configure `vpn-seed-server` and `vpn-shoot-client` pods accordingly
- [ ] activate vali on IPv6 single-stack seeds
- [ ] enhance `Shoot` API validation: service CIDR needs to have prefix of 108 or more
- [ ] document all required steps for getting started with the IPv6 single-stack local setup
- [x] add e2e tests for IPv6 with provider-local
  - [x] https://github.com/gardener/ci-infra/pull/1623: add periodics and optional presubmits to https://github.com/gardener/ci-infra/tree/master/config/jobs/gardener
  - [x] https://github.com/gardener/gardener/pull/9693
  - [x] https://github.com/gardener/ci-infra/pull/1623
- [x] https://github.com/gardener/gardener/pull/10678: add support for the node-local-dns feature on IPv6 single-stack shoots

**Comment by timebertt** [comment]
https://github.com/stackitcloud/gardener/tree/feature/shoot-ipv6 has a first working version of the remaining implementation steps of this GEP (adapting gardenlet's shoot components, adapting vpn2, adapting networking-calico).

On this branch, one should be able to successfully create a local IPv6 single-stack shoot:
```bash
make kind-up gardener-up IPFAMILY=ipv6
k apply -f example/provider-local/shoot-ipv6.yaml
```

**Comment by LucaBernstein** [comment]
@ScheererJ Could you please have a look, whether we can follow up on some of the remaining tasks on this issue?
