### ISSUE TITLE
☂️ Fluent Operator

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/gardener#7120]
**How to categorize this issue?**

/area logging
/kind enhancement

The Fluent-bit setup is currently scattered across various repositories. There is basic logic in g/g but there are also different filters and parsers on the different extensions, which Gardener is responsible for assembling into a single ConfigMap and giving it to Fluent-Bit. Therefore, we decided to rely on the [Fluent Operator](https://github.com/fluent/fluent-operator) to manage the entire lifecycle of the Fluent-bit and to be responsible for all activities related to it.
This change will make Fluent-Bit more easily extensible and also remove a lot of code from g/g related to its management.

**Tasks**:
- [x] https://github.com/gardener/gardener/pull/7093
- [x] Add `ClusterFilters` and `ClusterParsers` resources in all extensions which are deploying ConfigMap with label `extensions.gardener.cloud/configuration: logging`
   - [x] https://github.com/gardener/gardener-extension-provider-aws
   - [x] https://github.com/gardener/gardener-extension-provider-azure
   - [x] https://github.com/gardener/gardener-extension-provider-gcp
   - [x] https://github.com/gardener/gardener-extension-provider-alicloud
   - [x] https://github.com/gardener/gardener-extension-provider-openstack
   - [x] https://github.com/gardener/gardener-extension-provider-vsphere
   - [x] https://github.com/gardener/gardener-extension-provider-equinix-metal
   - [x] https://github.com/gardener/gardener-extension-shoot-dns-service
   - [x] https://github.com/gardener/gardener-extension-shoot-cert-service
   - [x] https://github.com/gardener/gardener-extension-networking-calico
- [x] https://github.com/gardener/gardener/pull/7568
- [x] Clean up the logging `ConfigMap`s in the extensions mentioned above
   - [x] gardener/gardener-extension-provider-aws#765
   - [x] gardener/gardener-extension-provider-gcp#616
   - [x] gardener/gardener-extension-provider-azure#700
   - [x] gardener/gardener-extension-provider-openstack#639
   - [x] gardener/gardener-extension-provider-alicloud#610
   - [x] gardener/gardener-extension-provider-equinix-metal#271
   - [x] gardener/gardener-extension-provider-vsphere#432 
   - [x] https://github.com/gardener/gardener-extension-shoot-dns-service/pull/215
   - [x] https://github.com/gardener/gardener-extension-shoot-cert-service/pull/168
   - [x] https://github.com/gardener/gardener-extension-networking-calico/pull/276

- [x] Open a new PR, similar to https://github.com/gardener/gardener/pull/7832, this time for the Operator , Log_Level config [ref](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file) -> https://github.com/gardener/gardener/pull/7942

**Comment by ScheererJ** [comment]
@Kristian-ZH Could you please also consider gardener-extension-networking-cilium?

**Comment by Kristian-ZH** [comment]
gardener-extension-networking-cilium currently does not have Parsers and Filters. 
With these updates, I just migrate the extensions which already have `logging` configmap
