### ISSUE TITLE
Implement `Infrastructure` extension resource

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#728]
Part of #308.

As we have proposed in [GEP-1](https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md) we want to have an `Infrastructure` extension resource that is reconciled by an external provider specific controller running in the seed. It should create the necessary networks, security groups, <iaas resources>, ... needed for a shoot cluster.

# Implementation Proposal

For now, in order to prevent incorporating undesired behaviour during the move out, let's stay with Terraform and simply externalize the Terraformer instantiation. Later, we can rewrite to "native" calls against the cloud's APIs via cloud SDKs.

# Definition of Done

- [x] Provider-specific extension controllers have been created for
  - [x] Alicloud [gardener/gardener-extensions#26, @adracus, ✅]
  - [x] AWS [gardener/gardener-extensions#14, @zanetworker, @rfranzke, ✅]
  - [x] Azure [gardener/gardener-extensions#23, @zanetworker, ✅]
  - [x] GCP [gardener/gardener-extensions#24, @adracus, ✅]
  - [x] OpenStack [gardener/gardener-extensions#25, @afritzler, ✅]
  - [x] Packet [gardener/gardener-extensions#78, @rfranzke, ✅]
  - [x] ~Local [discontinued]~
- [x] Required adaptions in Gardener [@rfranzke, ✅]
  - [x] All the infrastructure specific charts in https://github.com/gardener/gardener/tree/master/charts/seed-terraformer/charts are moved out of the `gardener` repository
  - [x] The two functions `DeployInfrastructure` and `DestroyInfrastructure` have been removed from the [`CloudBotanist` interface](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/types.go).
  - [x] The shoot reconciliation/deletion flow has been adapted that it will create/delete the `Infraststructure` extension resource into the seed instead of asking the cloud botanist to deploy/destroy the infrastructure.
  - [x] It is checked before the shoot flow that an adequate extension has been registered to Gardener.
  - [x] Every code path that used the Terraform state directly to get some outputs does now use the provided `InfrastructureStatus`.
  - [x] Documentation has been added to the `docs/extensions` folder that describes the contract between Gardener and the `Infrastructure` resource.
