### ISSUE TITLE
Implement `Worker` extension resource

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#729]
Part of #308.

As we have proposed in [GEP-1](https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md) we want to have an `Worker` extension resource that is reconciled by an external provider specific controller running in the seed. It should deploy the provider-specific `machine-controller-manager`, the required resources for it to reconcile, and the `MachineClass`es/`MachineDeployment`s needed for a shoot cluster.

# Definition of Done

- [x] Provider-specific extension controllers have been created for
  - [x] Alicloud  [gardener/gardener-extensions#75 @rfranzke, ✅]
  - [x] AWS  [gardener/gardener-extensions#71, @rfranzke, ✅]
  - [x] Azure  [gardener/gardener-extensions#72 @rfranzke, ✅]
  - [x] GCP  [gardener/gardener-extensions#73 @rfranzke, ✅]
  - [x] OpenStack  [gardener/gardener-extensions#74 @rfranzke, ✅]
  - [x] Packet  [gardener/gardener-extensions#82 @rfranzke, ✅]
  - [x] ~Local [discontinued]~
- [x] Required adaptions in Gardener [@rfranzke, ✅]
  - [x] The machine-controller-manager specific's resources at https://github.com/gardener/gardener/tree/master/charts/seed-bootstrap/templates are moved out the `gardener` repository
  - [x] All `Machine`-related functions have been removed from the [`CloudBotanist` interface](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/types.go).
  - [x] The shoot reconciliation/deletion flow has been adapted that it will create/delete the `Worker` extension resource into the seed instead of asking the cloud botanist to deploy/destroy the `MachineClass`es/`MachineDeployment`s/....
  - [x] It is checked before the shoot flow that an adequate extension has been registered to Gardener.
  - [x] Documentation has been added to the `docs/extensions` folder that describes the contract between Gardener and the `Worker` resource.
