### ISSUE TITLE
Refactor `NetworkPolicy`s in Gardener

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7352]
**How to categorize this issue?**

/area dev-productivity ops-productivity networking security
/kind enhancement

**What would you like to be added**:

Let's add a new `networkpolicy` controller as part of `gardener-resource-manager` which is only activated for the instance running in the `garden` namespace (not for shoot control plane namespaces) in seed/garden clusters. It shall watch `Service`s and create two `NetworkPolicy`s for each port in the `.spec.ports[]` list. For example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: gardener-resource-manager
  namespace: a
spec:
  # ...
  ports:
  - name: server
    port: 443
    protocol: TCP
    targetPort: 10250
```

leads to

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-gardener-resource-manager-tcp-10250
  namespace: a
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          networking.resources.gardener.cloud/gardener-resource-manager-tcp-10250: allowed
    ports:
    - port: 10250
      protocol: TCP
  podSelector:
    matchLabels:
      app: gardener-resource-manager
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-gardener-resource-manager-tcp-10250
  namespace: a
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: gardener-resource-manager
    ports:
    - port: 10250
      protocol: TCP
  podSelector:
    matchLabels:
      networking.resources.gardener.cloud/gardener-resource-manager-tcp-10250: allowed
  policyTypes:
  - Egress
```

A component that initiates the connection to `gardener-resource-manager`'s `tcp/10250` port can now be labeled with `networking.resources.gardener.cloud/gardener-resource-manager-tcp-10250=allowed`. That's all this component needs to do - it does not need to create any `NetworkPolicy`s itself anymore.

Apart from this "simple" case where both communicating components run in the same namespace, there is also the cross-namespace case. With above example, let's say there are components running in other namespaces `b` and `c`, but they would like to initiate the communication with `gardener-resource-manager` in `a`. To cover this scenario, the `Service` is annotated with `networking.resources.gardener.cloud/cross-namespace-selectors='[{"matchLabels":{"kubernetes.io/metadata.name":"b"}},{"matchLabels":{"kubernetes.io/metadata.name":"c"}}]'`. This will make the new controller create additional `NetworkPolicy`s as follows:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-gardener-resource-manager-tcp-10250-cross
  namespace: a
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          networking.resources.gardener.cloud/a-gardener-resource-manager-tcp-10250: allowed
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: b
    - podSelector:
        matchLabels:
          networking.resources.gardener.cloud/a-gardener-resource-manager-tcp-10250: allowed
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: c
    ports:
    - port: 10250
      protocol: TCP
  podSelector:
    matchLabels:
      app: gardener-resource-manager
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-a-gardener-resource-manager-tcp-10250
  namespace: b
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: gardener-resource-manager
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: a
    ports:
    - port: 10250
      protocol: TCP
  podSelector:
    matchLabels:
      networking.resources.gardener.cloud/a-gardener-resource-manager-tcp-10250: allowed
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-a-gardener-resource-manager-tcp-10250
  namespace: c
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: gardener-resource-manager
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: a
    ports:
    - port: 10250
      protocol: TCP
  podSelector:
    matchLabels:
      networking.resources.gardener.cloud/a-gardener-resource-manager-tcp-10250: allowed
  policyTypes:
  - Egress
```

The components in namespace `b` and `c` now need to be labeled with `networking.resources.gardener.cloud/a-gardener-resource-manager-tcp-10250=allowed`, but that's already it.

Obviously, this approach also works for namespace selectors different from `kubernetes.io/metadata.name` to cover scenarios where the namespace name is not known upfront or where multiple namespaces with a similar label are relevant.

> Note that the `NetworkPolicy`s deployed into the shoot clusters' `kube-system` namespaces remain to be handled "specially" since they only have the purpose to allow communication of the shoot system components in case the end-user deploys a "deny-all" `NetworkPolicy` into the namespace. Since the namespace can also run custom workload, we cannot deploy a "deny-all" `NetworkPolicy` by default.

> Note that there will remain a few "global"/"general" `NetworkPolicy`s that are created by `gardenlet`/`gardener-operator`: `deny-all`, `allow-to-dns`, `allow-to-public-networks`, `allow-to-private-networks`, `allow-to-blocked-cidrs`, `allow-to-runtime-apiserver` (called `allow-to-seed-apiserver` today).

**Why is this needed**:

Today, there is no consistent approach when it comes to managing `NetworkPolicy`s in the Gardener environment. While there are few "global"/"general" policies like `allow-to-dns`, `allow-to-public-networks`, `allow-to-private-networks`, there is no harmonized approach on tackling policies for "point-to-point" communication of two components. Sometimes, there are policies per component which include all the rules needed for it (e.g., `allow-kube-apiserver` in shoot namespaces). Sometimes, there are policies which only apply to pods with a certain label (e.g., `allow-to-aggregate-prometheus` in the `garden` namespace).

Moreover, there are components which do not have any `NetworkPolicy`s (for example, some seed system components in the `garden` namespace or extensions).
All of this makes it hard to reuse components (e.g., in the context of `gardener-operator` sharing some code with `gardenlet` and only deploying some of the shoot control plane components for the virtual garden cluster).

To summarize, this proposal shall tackle the following issues:

- Inconsistent approach of how `NetworkPolicy`s are used in the Gardener space (which makes it hard for devs and hard for ops as well)
- Reusing some components is not easy since they might deploy `NetworkPolicy`s for network paths that don't exist in certain scenarios (e.g., reusing `kube-apiserver` component would deploy a network policy allowing communication to `vpn-seed-server` which does not exist in virtual garden setup).
- Some `NetworkPolicy`s are wrongly replicated to the shoot namespace, although they only belong to the seed system components
- Every component needs custom coding to manage `NetworkPolicy`s
- Some components don't have `NetworkPolicy`s at all

**Tasks:**

- [x] https://github.com/gardener/gardener/pull/7392
  - [x] https://github.com/gardener/gardener/pull/7412
  - [x] https://github.com/gardener/gardener/pull/7437
  - [x] https://github.com/gardener/gardener/pull/7907
  - [x] https://github.com/gardener/gardener/pull/7929
  - [x] https://github.com/gardener/gardener/pull/8076
- [x] https://github.com/gardener/gardener/pull/7389
  - https://github.com/gardener/gardener/pull/7434
- [x] https://github.com/gardener/gardener/pull/7401
- [x] https://github.com/gardener/gardener/pull/7408
- Enable `gardener-resource-manager`'s `NetworkPolicy` controller:
  - [x] for shoot namespaces: https://github.com/gardener/gardener/pull/7484
  - [x] for `Istio`-related namespaces: https://github.com/gardener/gardener/pull/7570
  - [x] for extensions-related namespaces: https://github.com/gardener/gardener/pull/7589
  - [x] for `garden` namespace: https://github.com/gardener/gardener/pull/7636
- Adapt existing `NetworkPolicy`s and switch to new approach:
  - [x] https://github.com/gardener/gardener/pull/7484
  - [x] https://github.com/gardener/gardener/pull/7515
  - [x] https://github.com/gardener/gardener/pull/7570
  - [x] https://github.com/gardener/gardener/pull/7589
  - [x] https://github.com/gardener/gardener/pull/7636
- Adapt extensions
  - [x] [provider-aws](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/714, released with [`v1.43.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.43.0)
  - [x] [provider-azure](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/642, released with [`v1.35.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.35.0)
  - [x] [provider-gcp](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/566, released with [`v1.29.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.29.0)
  - [x] [provider-alicloud](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/581, released with [`v1.45.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.45.0)
  - [x] [provider-openstack](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/578, released with [`v1.33.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.33.0)
  - [x] [provider-equinix-metal](https://github.com/gardener/gardener-extension-provider-equinix-metal): https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/248, ~~released with [`v?`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v?)~~ (no need to wait for it)
  - [x] [provider-vsphere](https://github.com/gardener/gardener-extension-provider-vsphere): https://github.com/gardener/gardener-extension-provider-vsphere/pull/383, released with [`v0.26.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.26.0)
  - [x] [networking-cilium](https://github.com/gardener/gardener-extension-networking-cilium): https://github.com/gardener/gardener-extension-networking-cilium/pull/162, released with [`v1.22.0`](https://github.com/gardener/gardener-extension-networking-cilium/releases/tag/v1.22.0)
  - [x] [networking-calico](https://github.com/gardener/gardener-extension-networking-calico): https://github.com/gardener/gardener-extension-networking-calico/pull/247, released with [`v1.31.0`](https://github.com/gardener/gardener-extension-networking-calico/releases/tag/v1.31.0)
  - [x] [shoot-networking-filter](https://github.com/gardener/gardener-extension-shoot-networking-filter): https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/58, released with [`v0.12.0`](https://github.com/gardener/gardener-extension-shoot-networking-filter/releases/tag/v0.12.0)
  - [x] [shoot-networking-problem-detector](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector): https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/62, released with [`v0.14.0`](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/releases/tag/v0.14.0)
  - [x] [os-ubuntu](https://github.com/gardener/gardener-extension-os-ubuntu): https://github.com/gardener/gardener-extension-os-ubuntu/pull/78, released with [`v1.21.0`](https://github.com/gardener/gardener-extension-os-ubuntu/releases/tag/v1.21.0)
  - [x] [os-gardenlinux](https://github.com/gardener/gardener-extension-os-gardenlinux): https://github.com/gardener/gardener-extension-os-gardenlinux/pull/83, released with [`v0.18.0`](https://github.com/gardener/releases/tag/v?/gardener-extension-os-gardenlinux/releases/tag/v0.18.0)
  - [x] [os-suse-chost](https://github.com/gardener/gardener-extension-os-suse-chost): https://github.com/gardener/gardener-extension-os-suse-chost/pull/83, released with [`v1.21.0`](https://github.com/gardener/gardener-extension-os-suse-chost/releases/tag/v1.21.0)
  - [x] [os-coreos](https://github.com/gardener/gardener-extension-os-coreos): https://github.com/gardener/gardener-extension-os-coreos/pull/60, released with [`v1.16.0`](https://github.com/gardener/gardener-extension-os-coreos/releases/tag/v1.16.0)
  - [x] [shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service): https://github.com/gardener/gardener-extension-shoot-dns-service/pull/197, released with [`v1.31.0`](https://github.com/gardener/releases/tag/v?/gardener-extension-shoot-dns-service/releases/tag/v1.31.0)
  - [x] [shoot-cert-service](https://github.com/gardener/gardener-extension-shoot-cert-service): https://github.com/gardener/gardener-extension-shoot-cert-service/pull/152, released with [`v1.30.0`](https://github.com/gardener/gardener-extension-shoot-cert-service/releases/tag/v1.30.0)
  - [x] [shoot-oidc-service](https://github.com/gardener/gardener-extension-shoot-oidc-service): https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/95, released with [`v0.16.0`](https://github.com/gardener/gardener-extension-shoot-oidc-service/releases/tag/v0.16.0)
  - [x] [runtime-gvisor](https://github.com/gardener/gardener-extension-runtime-gvisor): https://github.com/gardener/gardener-extension-runtime-gvisor/pull/78, released with [`v0.9.0`](https://github.com/gardener/gardener-extension-runtime-gvisor/releases/tag/v0.9.0)
  - [x] [registry-cache](https://github.com/gardener/gardener-extension-registry-cache): https://github.com/gardener/gardener-extension-registry-cache/pull/14, ~~released with [`v?`](https://github.com/gardener/gardener-extension-registry-cache/releases/tag/v?)~~ (there is no non-alpha release of this extension yet)
  - [x] [kupid](https://github.com/gardener/kupid): https://github.com/gardener/kupid/pull/50, released with [`v0.5.0`](https://github.com/gardener/kupid/releases/tag/v0.5.0)
  - [x] shoot-lakom-service: kubernetes/gardener-extension-shoot-lakom-service#87, released with `v0.4.0`
  - [x] shoot-auditlog-service: kubernetes/gardener-extension-shoot-auditlog-service#44, released with `v0.3.0`
  - [x] auditlog-extension: kubernetes/auditlog-extension#392, released with `v0.53.0`
  - [x] [terminal pods via dashboard](https://github.com/gardener/dashboard/blob/master/backend/lib/services/terminals/index.js#L477-L496): https://github.com/gardener/dashboard/pull/1439, released with [`v1.68.0`](https://github.com/gardener/dashboard/releases/tag/v1.68.0)
- [x] https://github.com/gardener/gardener/pull/7866
- [x] Promote `FullNetworkPoliciesInRuntimeCluster` feature gate to GA: https://github.com/gardener/gardener/pull/8008
- [x] https://github.com/gardener/gardener/pull/8083
- [x] https://github.com/gardener/gardener/pull/7868

**Comment by ScheererJ** [comment]
To be explicit: For the cross-namespace case, the controller needs to react to namespace changes. Therefore, it needs to watch namespaces as well.

**Comment by timebertt** [comment]
Nice proposal, I like it! 👏 

Two naming suggestions:
- I would include `to` in the pod selectors to make it absolutely clear and self-explanatory, e.g.:
`networking.resources.gardener.cloud/to-gardener-resource-manager-tcp-10250=allowed`
- Instead of using `to-` and `from-` prefixes in `NetworkPolicy` names, I would include `egress` and `ingress` in the names.
Naming the `ingress` rule `from-gardener-resource-manager-tcp-10250` might be confusing, as no traffic originates from gardener-resource-manager on port `10250`.

One concern:
- The controller only generates `NetworkPolicies` for `Service` objects. However, prometheus can discover endpoints based on pod objects with no service attached. This is used in `seed-prometheus` for example.
We could
  - a) dictate that services for the metrics port need to be created (optionally, seed-prometheus could be configured to discover services with annotations instead of pods with annotations) or
  - b) dictate that `NetworkPolicies` allowing ingress on the metrics port need to be created "manually" and create a generic egress `NetworkPolicy` for prometheus or 
  - c) teach the controller to consider the prometheus annotations (least favorable).

And one question:
- Will the new controller also ensure a `deny-all` `NetworkPolicy` in all namespaces?
Without such a `NetwokPolicy` this effort's potential would not unfold entirely.

**Comment by ScheererJ** [comment]
@timebertt There are also a few other use cases where no services are used, e.g. network problem detector. Going forward some global policies might still be needed in addition to the ones created by the to-be-implemented controller. Creating unused services for metrics ports just to reuse this controller does not sound good to me.

From my perspective, this controller is the stepping stone to have `deny-all` policies in all namespaces in the seed. However, first it needs to be adopted also by the extensions, which can take some time. Hence, I do not see `deny-all` as the first step, but rather as a follow-up.

**Comment by rfranzke** [comment]
All related tasks have been completed.
/close
