### ISSUE TITLE
Update `golang` to 1.20

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#7449]
**How to categorize this issue?**

/area open-source
/kind enhancement

Golang v1.20 was released on February 1st,  Check what's new in Go v1.20 [release notes](https://go.dev/doc/go1.20) or [blog](https://go.dev/blog/go1.20).

## Tasks
- [x] Prepare PR to update images for [unit](https://github.com/gardener/ci-infra/blob/master/config/jobs/gardener/gardener-unit-tests.yaml) and [integration](https://github.com/gardener/ci-infra/blob/master/config/jobs/gardener/gardener-integration-tests.yaml) tests in prow to Go 1.20 https://github.com/gardener/ci-infra/pull/594
  - [x] merge PR which fixes wrong image labels first https://github.com/gardener/ci-infra/pull/573
- [x] Update `golangci-lint` to `v1.51.2` to support go 1.20 https://github.com/gardener/gardener/pull/7537
- [x] Bump images, dependencies, and versions to go 1.20 https://github.com/gardener/gardener/pull/7553

<hr>

### Optional

- Drop usage for `multierror.Append` of this library `github.com/hashicorp/go-multierror` and use `errors.Join` where ever possible.
- Build binary with -pgo flag to enable profile-guided optimizations, this can improve performance by around 2-4%.

**Comment by acumino** [comment]
Waiting for homebrew PR to get merged https://github.com/Homebrew/homebrew-core/pull/122082.

**Comment by rfranzke** [comment]
All above tasks are completed. Can we close this issue? As for the optional tasks, I understood that we cannot fully drop `github.com/hashicorp/go-multierror`, and that the `-pgo` is alpha. So, probably we shouldn't follow up with them for now?

**Comment by acumino** [comment]
> All above tasks are completed. Can we close this issue? As for the optional tasks, I understood that we cannot fully drop `github.com/hashicorp/go-multierror`, and that the `-pgo` is alpha. So, probably we shouldn't follow up with them for now?

Yes, PGO can be done separately as this required two-step process first to collect profile data and then optimize the binary.
/close
