### ISSUE TITLE
Adapt node ranges to reality

### ISSUE THREAD

**Issue by ScheererJ** [gardener/gardener#7582]
**How to categorize this issue?**

/area networking
/area robustness
/kind enhancement
/kind cleanup

**What would you like to be added**:
The shoot specification should include the (infrastructure-independent) set of used node networks.

**Why is this needed**:
The `node` network range is specified multiple times in the shoot specification (infrastructure configuration vs. networking configuration), which is redundant. `.spec.networking.nodes` is not well defined. Essentially, it is just a superset of what is actually used.
For example, if a networking extension wants to implement overlay-free pod networks it needs to implement source network address translation (SNAT) at some boundary. However, the `node` range does not necessarily need to be the correct range as it could contain other subnets not managed by Gardener, which need SNAT for pod IPs.

**Tasks**:

- [ ] Add `spec.networks.allNodes []string` to `Seed`
- [ ] Add `spec.networking.allNodes []string` to `Shoot`
- [ ] Add `spec.nodeCIDRs []string` to `extensions.Network`
- [ ] Adapt `status` in `extensions.Infrastructure`
- [ ] Use `spec.nodeCIDRs` in networking extensions (instead of `Cluster`)
- [ ] Create defaulting webhook in provider admission components for CREATE shoots, which specifies `.spec.networking.allNodes` based on infrastructure configuration
- [ ] Deprecate old (string nodes) fields
- [ ] Drop old fields after 3 months

**Comment by timebertt** [comment]
In general, the proposal sounds good to me.
I'm wondering about the proposed naming of the new list fields (e.g., `Shoot.spec.networking.allNodes`) though.
For supporting IPv6 dual-stack, we might need to add list fields of all network ranges (also for pods and services), correct?
I'm afraid that adding `all{Nodes,Pods,Services}` confuses users of the Shoot API. Should we consider moving the Shoot API to v1 and switching to `[]string` fields in the new API version?
