### ISSUE TITLE
Move `machine-controller-manager` reconciliation responsibility from extensions to `gardenlet`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7594]
**How to categorize this issue?**

/area dev-productivity
/kind enhancement

**What would you like to be added**:
`gardenlet` should be responsible to deploy `machine-controller-manager` as part of the shoot reconciliation. Extension controllers shall only inject their provider-specifics (e.g., the [sidecar containers](https://github.com/gardener/gardener/blob/master/charts/gardener/provider-local/internal/machine-controller-manager/seed/templates/deployment.yaml#L41-L69)).

In order to roll this out in a backwards-compatible way, a feature gate must be introduced which should only be enabled when the extensions support this deployment approach.

**Why is this needed**:
Today, the extension controllers are responsible for managing the lifecycle of the `machine-controller-manager` deployment. The [generic `Worker` actuator](https://github.com/gardener/gardener/tree/master/extensions/pkg/controller/worker/genericactuator) abstracts a good portion of the common, still the extensions each duplicate the resources again and again, see https://github.com/gardener/gardener/tree/master/charts/gardener/provider-local/internal/machine-controller-manager or https://github.com/gardener/gardener-extension-provider-aws/tree/master/charts/internal/machine-controller-manager. 

The ouf-of-tree story of `machine-controller-manager` has been completed a long while ago, so we can safely shift the responsibility to `gardenlet` now and reduce the maintenance effort on all extensions this way.

**Tasks:**

- [x] https://github.com/gardener/gardener/pull/7598
- [x] https://github.com/gardener/gardener/pull/8011
- [x] https://github.com/gardener/gardener/pull/8015
- [x] https://github.com/gardener/gardener/pull/8018
  -  Introduce new `MachineControllerManagerDeployment` feature gate
  - Adapt `gardenlet` to take over management of `machine-controller-manager`
  - Adapt generic `Worker` actuator (controller) in extensions library
  - Adapt generic `ControlPlane` mutator (webhook) in extensions library
- [x] https://github.com/gardener/gardener/pull/8056
- Adapt extensions (after revendoring `gardener/gardener@v1.73+`)
  - [x] provider-local: https://github.com/gardener/gardener/pull/8019
  - [x] [provider-aws](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/774, released with [`v1.46.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.46.0)
  - [x] [provider-azure](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/705, released with [`v1.38.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.38.0)
  - [x] [provider-gcp](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/624, released with [`v1.32.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.32.0)
  - [x] [provider-alicloud](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/617, released with [`v1.47.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.47.0)
  - [x] [provider-openstack](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/645, released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.36.0)
  - [x] [provider-equinix-metal](https://github.com/gardener/gardener-extension-provider-equinix-metal): https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/275, released with [`v2.7.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.7.0)
  - [x] [provider-vsphere](https://github.com/gardener/gardener-extension-provider-vsphere): https://github.com/gardener/gardener-extension-provider-vsphere/pull/437, released with [`v0.29.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.29.0)
  - [x] [provider-onmetal](https://github.com/onmetal/gardener-extension-provider-onmetal): https://github.com/onmetal/gardener-extension-provider-onmetal/pull/221, released with [`v0.1.7`](https://github.com/onmetal/gardener-extension-provider-onmetal/releases/tag/v0.1.7)
- [x] https://github.com/gardener/gardener/pull/8407 
- [x] Promote `MachineControllerManagerDeployment` feature gate to beta (planned for `gardener/gardener@v1.81`): https://github.com/gardener/gardener/pull/8526
- [x] Promote `MachineControllerManagerDeployment` feature gate to GA and cleanup migration code and old MCM management from `gardener/gardener` and provider extensions after graduation of the feature gate (planned for `gardener/gardener@v1.82`): https://github.com/gardener/gardener/pull/8596

**Comment by rfranzke** [comment]
/assign @rfranzke 
I have started to work on it on TGIFs and will continue sporadically when time allows.

FYI @himanshu-kun @kon-angelo @MartinWeindel @dkistner
