### ISSUE TITLE
☂️ Shoot Without Workers (a.k.a Control Plane as a Service)

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#7635]
**How to categorize this issue?**

/area control-plane open-source 
/kind enhancement epic

As of today, Gardener doesn't support shoots with zero worker pool. But there are use cases where the user doesn't want data plane and only wants to utilize `kube-apisever` features. To support this Gardener should allow creating shoots with zero worker pools.

For the first iteration of this topic:-
#### Goals:
 - Should be able to create a new shoot with zero worker pools.
 -  HA feature should be provided out of the box.
 - Migration should be provided out of the box.
#### Non-Goals:
 - Allow switching back and forth between shoot with zero worker pools and shoot with non-zero worker pools.

### Gardener:
- [x] Adapt shoot API to support new use case. Make following fields optional - 
      - `spec.secretBindingName` https://github.com/gardener/gardener/pull/7828
      - `spec.networking` https://github.com/gardener/gardener/pull/7828
      - `spec.networking.type` https://github.com/gardener/gardener/pull/7828
      - `spec.maintenance.autoUpdate.machineImageVersion` https://github.com/gardener/gardener/pull/7828
 - [x] Introduce `workerlessSupported` field under `spec.resources` in the ControllerRegistration API to specify whether this ControllerResource is supported in Workerless Shoot clusters. https://github.com/gardener/gardener/pull/7863
- [x] Adapt validation
      - Adapt validation for new API changes. https://github.com/gardener/gardener/pull/7828
      - Add validation that once a shoot without a worker pool is created one should not be able to add a worker pool and vice versa. https://github.com/gardener/gardener/pull/7828
- [x] Use only required KCM controllers for `workerless` shoot as per the below list - 
      - `namespace`,`serviceaccount`,`serviceaccount-token`,`clusterrole-aggregation`,`garbagecollector`,`csrapproving`,`csrcleaner`,`csrsigning`,`bootstrapsigner`,`tokencleaner`,`resourcequota`. https://github.com/gardener/gardener/pull/7858
- [x] Disable not required APIs in `kube-apiserver`. https://github.com/gardener/gardener/pull/7858
  - `autoscaling/v2`
  - `batch/v1`
  - `apps/v1`
  - `policy/v1/poddisruptionbudgets`
  - `storage.k8s.io/v1/csidrivers` 
  - `storage.k8s.io/v1/csinodes`
  - `policy/v1beta1/podsecuritypolicies`
- [x] Don't deploy not required controller and webhooks of GRM in shoot `control-plane`. 
  - [x] Not required controller https://github.com/gardener/gardener/pull/7882
       - `KubeletCSRApprover` controller
       - `Node` controller
  - [x] Not required Webhooks https://github.com/gardener/gardener/pull/7882
       - `PodSchedulerName`
       - `SystemComponentsConfig`
       - `ProjectedTokenMount`
       - `HighAvailabilityConfig`
       - `PodTopologySpreadConstraints`
- [x] Adapt shoot reconciliation flows(Create/Delete/Hibernate/Migrate) for shoots without worker pools. 
    - [x] Skip deploying shoot system components. https://github.com/gardener/gardener/pull/7882
    - [x] Skip deploying following component in `control-plane` - https://github.com/gardener/gardener/pull/7882
           - `Kube-Scheduler`
           - `Cluster-Autoscaler (CA)`
           - `Cloud-Controller-Manager (CCM)`
           - `Vertical Pod Autoscaler (VPA)`
           - `MCM`
           - `CSI components`
- [x] Adapt `shoot` health check in shoot `care` controller. https://github.com/gardener/gardener/pull/7882
      - Don't check `EveryNodeReady` healthy condition for workerless shoot.
- [x] Add e2e tests to check shoot flows for workerless shoots. https://github.com/gardener/gardener/pull/7882
- [x] Adapt logging and monitoring component for workerless shoots. https://github.com/gardener/gardener/pull/7889
  - [x] https://github.com/gardener/gardener/pull/7962 
- [x] Add gardener upgrade test for workerless shoot. https://github.com/gardener/gardener/pull/7948
- [x] https://github.com/gardener/gardener/pull/8141

### Extensions:
- Extensions having validating/mutating shoot based on `worker/controleplaneConfig/infrastructureConfig/networkingConfig`, need adaption for workerless shoots. 

  - [x] provider-alicloud https://github.com/gardener/gardener-extension-provider-alicloud/pull/600,  released with [`v1.46.0`](https://github.com/gardener/gardener-extension-provider-alicloud/releases/tag/v1.46.0)
  - [x] provider-aws https://github.com/gardener/gardener-extension-provider-aws/pull/749,  released with [`v1.44.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.44.0)
  - [x] provider-azure https://github.com/gardener/gardener-extension-provider-azure/pull/685, released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.36.0)
  - [x] provider-gcp https://github.com/gardener/gardener-extension-provider-gcp/pull/596, released with [`v1.30.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.30.0)
  - [x] provider-openstack https://github.com/gardener/gardener-extension-provider-openstack/pull/624, released with [`v1.34.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.34.0)
  - [x] provider-vsphere https://github.com/gardener/gardener-extension-provider-vsphere/pull/412, released with [`v0.29.0`](https://github.com/gardener/gardener-extension-provider-vsphere/releases/tag/v0.29.0)
  - [x] provider-equinix-metal https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/262, released with [`v2.7.0`](https://github.com/gardener/gardener-extension-provider-equinix-metal/releases/tag/v2.7.0)
  - [x] networking-calico , https://github.com/gardener/gardener-extension-networking-calico/pull/272 released with [`v1.34.0`](https://github.com/gardener/gardener-extension-networking-calico/releases/tag/v1.34.0)
  - [x] networking-cilium https://github.com/gardener/gardener-extension-networking-cilium/pull/189, released with [`v1.25.0`](https://github.com/gardener/gardener-extension-networking-cilium/releases/tag/v1.25.0)

- An optional field `workerlessSupported` is added under `spec.resources` in the  `ControllerRegistration` API. To support workerless Shoots, extensions reconciling `extensions.gardener.cloud/v1alpha1.Extension` resources need to make adaptions if needed and then set `spec.resources[].workerlessSupported` to `true` in the `ControllerRegistration` for their respective extension type.

  - [x] shoot-dns-service https://github.com/gardener/gardener-extension-shoot-dns-service/pull/212, released with [`v1.34.0`](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.34.0)
  - [x] shoot-cert-service https://github.com/gardener/gardener-extension-shoot-cert-service/pull/164, released with [`v1.33.0`](https://github.com/gardener/gardener-extension-shoot-cert-service/releases/tag/v1.33.0)

### Dashboard: 
- [x] https://github.com/gardener/dashboard/issues/1503

### DWD:
- [x] Do not create probes for shoot control NS without workers - https://github.com/gardener/dependency-watchdog/issues/80,  released with [`v1.1.0`](https://github.com/gardener/dependency-watchdog/releases/tag/v1.1.0)
  - [x] https://github.com/gardener/gardener/pull/7974 

<hr> 

Allowed/Denied fields for `Workerless` shoot

Shoot
-----
```yaml=
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: crazy-botany
  namespace: garden-dev
spec:
  secretBindingName:                   # Deny
  cloudProfileName:                    # Allowed
  region:                              # Allowed
  purpose:                             # Allowed
  provider: 
    type:                              # Allowed
    infrastructureConfig:              # Deny
    controlPlaneConfig:                # Deny
    workers:                           # Deny
    workersSettings:                   # Deny
  kubernetes: 
    version: 1.20.1                    # Allowed
    enableStaticTokenKubeconfig:       # Allowed
    allowPrivilegedContainers:         # Deny
    kubeAPIServer:                     # Allowed
    kubeControllerManager:             # Allowed
    kubeScheduler:                     # Deny
    kubeProxy:                         # Deny
    kubelet:                           # Deny
    clusterAutoscaler:                 # Deny
    verticalPodAutoscaler:             # Deny
  dns:                                 # Allowed
  extensions:                          # Allowed 
  - type: foobar (ex - networkPD, networking filter, shoot dns service)
  networking:
    type:                              # Deny
    providerConfig:                    # Deny
    pods:                              # Deny
    nodes:                             # Deny
    services:                          # Allowed
    ipFamilies:                        # Allowed
  maintenance:
    timeWindow:                        # Allowed
    autoUpdate:
      kubernetesVersion: true          # Allowd
      machineImageVersion: true        # Deny
    confineSpecUpdateRollout:          # Allowed
  monitoring:                          # Required
  hibernation:                         # Required
  addons:                              # Deny
  tolerations:                         # Allowed
  seedName:                            # Allowed
  seedSelector:                        # Allowed
  resources:                           # Allowed                               
  exposureClassName:                   # Allowed
  systemComponents:                    # Deny
  controlPlane:                        # Allowed
```

**Comment by unmarshall** [comment]
>But there are use cases where the user doesn't want data plane and only wants to utilize kube-apisever features.

It is a combination of a distributed DB (etcd) and KAPI + an ability for watch for changes that control plane as a service becomes attractive for customers (who are asking for it). However, this also opens door for a potential increase in a `noisy-neighbour` problem w.r.t etcd. The definition of this feature hints at using etcd as a storage for potentially large number of resources. Heavy usage of etcd in such control planes will eventually impact other etcds for shoots that have worker nodes (in their shoot cluster).

Since we do not know how in the end customers will be using such a feature, would it make sense to isolate these control-planes to a separate seed? If we go down this path then this epic becomes a bit more involved.

> NOTE: It is also true that no one is stopped even today from mis-using the current control-plane's etcd (even when they have workers > 0), however there is a semantic difference between these 2 variants of offerings. One is a serving as a control for workloads that are scheduled onto workers. Other `control-plane-as-a-service` is dedicated to be used for capabilities that etcd and KAPI provide.

**Comment by rfranzke** [comment]
> Since we do not know how in the end customers will be using such a feature, would it make sense to isolate these control-planes to a separate seed? If we go down this path then this epic becomes a bit more involved.

I would omit this additional complexity for now since the described problem can already occur today. I agree that calling it "CPaaS" might increase the risk that people put more load on ETCD, OTOH is this just an hypothesis and a problem that we can have with regular shoots as well. Hence, we should probably rather looking into fixing such "noisy neighbour" problems in a general way.

**Comment by unmarshall** [comment]
>OTOH is this just an hypothesis and a problem that we can have with regular shoots as well. Hence, we should probably rather looking into fixing such "noisy neighbour" problems in a general way.

We have already run into issues of noisy neighbour where a few customers have misused etcd and caused problems for others on the same node. So yes we are trying to think of ways to alleviate the noisy neighbour problem to some extent. However this feature is just going to add to the issue at hand. Today we might have a few customers misusing their control plane but as you also have stated the risk just increases. As long as we are aware of the risk it is fine.

**Comment by dguendisch** [comment]
I think it's very hard to predict load patterns here because the opposite can happen as well: no ccm, no mcm, no calico/csi/whatever-agents, so probably a lot less controllers, it _could_ result in less load on average as well 🔮

**Comment by vlerenc** [comment]
HANA Cloud is asking for a date (I am not quite sure why this would be critical to them and will return this feedback), but nevertheless, can we commit already on a milestone and set it at the ticket for better transparency (so that they can track)? Thank you in advance!

**Comment by acumino** [comment]
We are targeting the `alpha` release of this feature in v1.70. We aim to open the gardener PR by next week, after that there are adaptions required across extensions and DWD which can take some time.

**Comment by shafeeqes** [comment]
All tasks are completed!
/close

**Comment by vlerenc** [comment]
🎉
