### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.27”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7783]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.27 was released on April 11th, you'll find the changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md

Work can be started and pushed to the [`kubernetes-v1.27`](https://github.com/gardener/gardener/tree/kubernetes-v1.27) branch. There should be similar branches in the provider extension repositories in case the work has been started already.

---

# Tasks

## Hyperkube

- [x] `hyperkube`: https://github.com/gardener/hyperkube/releases/tag/v1.27.0
  - Build new image for v1.27
 
## Gardener

- [x] `gardener`: https://github.com/gardener/gardener/pull/7883
  - Good to know/no action required
    - Support for the alpha seccomp annotations `seccomp.security.alpha.kubernetes.io/pod` and `container.seccomp.security.alpha.kubernetes.io` were deprecated since `v1.19`, now have been completely removed. (https://github.com/kubernetes/kubernetes/pull/114947)
    - The `SecurityContextDeny` admission plugin is going to be deprecated and will be removed in future versions. As a part of deprecation process this admission plugin has been put behind the feature gate.(https://github.com/kubernetes/kubernetes/pull/115879)
    - Added validation to ensure that if `service.kubernetes.io/topology-aware-hints` and `service.kubernetes.io/topology-mode` annotations are both set, they are set to the same value.Also Added deprecation warning if service.kubernetes.io/topology-aware-hints annotation is used.(https://github.com/kubernetes/kubernetes/pull/116612)
    - Bump default API QPS limits for Kubelet. (https://github.com/kubernetes/kubernetes/pull/116121)
    - `Kubelet`: migrated `--container-runtime-endpoint` and `--image-service-endpoint` to `kubelet` config (https://github.com/kubernetes/kubernetes/pull/112136)
    - `MinDomainsInPodTopologySpread` feature gate is enabled by default as a Beta feature in 1.27. (https://github.com/kubernetes/kubernetes/pull/114445)
  - Release-independent tasks
    - Allow instantiating v1.27 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/features/featuregates.go
    - Update admission plugins in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/admissionplugins.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/component/shootsystem/shootsystem.go
    - Bump used Kubernetes version for local shoot and local e2e test
  - Release-specific tasks
    - Do no longer allow static kubeconfig for all `1.27+` shoot clusters
    - Remove deprecated `--pod-eviction-timeout` CLI.(https://github.com/kubernetes/kubernetes/pull/115840)
    - `Kubelet`: remove deprecated flag `--container-runtime` (https://github.com/kubernetes/kubernetes/pull/114017)
    - New `service.kubernetes.io/topology-mode` annotation has been introduced as a replacement for the `service.kubernetes.io/topology-aware-hints` annotation. `service.kubernetes.io/topology-aware-hints`annotation has been deprecated. https://github.com/gardener/gardener/pull/7933
    - https://github.com/gardener/gardener/issues/7688#issuecomment-1504967111
    - https://github.com/gardener/gardener/pull/7878

## Test Infra

- [x] [Ensure test-infra compatibility](https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/README.md#run-conformance-tests-against-new-k8s-versions) with conformance tests ([example](https://github.com/gardener/test-infra/commit/231f14fd430cbfc76be8ae4f893b7fa0ddd484c5)): 

## Cloud Controller Managers

- [x] `cloud-provider-aws`
  - Maintain `release-v1.24` branch (update container images and revendor latest Kubernetes patch): [`v1.24.13`](https://github.com/gardener/cloud-provider-aws/releases/tag/v1.24.13)
- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.27` branch from it (update container images and revendor latest Kubernetes patch): [`v1.27.1`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.27.1)
  - Maintain `release-v1.26` branch (update container images and revendor latest Kubernetes patch): [`v1.26.4`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.26.4)
  - Maintain `release-v1.25` branch (update container images and revendor latest Kubernetes patch): [`v1.25.9`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.25.9)
  - Maintain `release-v1.24` branch (update container images and revendor latest Kubernetes patch): [`v1.24.13`](https://github.com/gardener/cloud-provider-gcp/releases/tag/v1.24.13)

## Provider Extensions

- [x] `provider-alicloud`:  https://github.com/gardener/gardener-extension-provider-alicloud/pull/609
  - Revendor `gardener/gardener` with support for 1.27 client creation: https://github.com/gardener/gardener-extension-provider-alicloud/pull/604
  - Update `README.md` with support for 1.27
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/759
  - Revendor `gardener/gardener` with support for 1.27 client creation: https://github.com/gardener/gardener-extension-provider-aws/pull/749
  - Update `README.md` with support for 1.27
  - Update `cloud-controller-manager` images
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/699
  - Revendor `gardener/gardener` with support for 1.27 client creation: https://github.com/gardener/gardener-extension-provider-azure/pull/693
  - Update `README.md` with support for 1.27
  - Update `cloud-controller-manager` images
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/615
  - Revendor `gardener/gardener` with support for 1.27 client creation: https://github.com/gardener/gardener-extension-provider-gcp/pull/604
  - Update `README.md` with support for 1.27
  - Update `cloud-controller-manager` images
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/632
  - Revendor `gardener/gardener` with support for 1.27 client creation
  - Update `README.md` with support for 1.27
  - Update `cloud-controller-manager` images
- [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/450
  - Revendor `gardener/gardener` with support for 1.27 client creation
  - Update `README.md` with support for 1.27
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/270
  - Revendor `gardener/gardener` with support for 1.27 client creation
  - Update `README.md` with support for 1.27

## Cluster Autoscaler

- [x] Update cluster-autoscaler for K8s 1.27:
  - https://github.com/gardener/autoscaler/issues/191
  - https://github.com/gardener/gardener/pull/8187

## Follow-up items

- [x] Add K8s 1.27 support for Gardener to [kubernetes/test-infra](https://github.com/kubernetes/test-infra/): https://github.com/kubernetes/test-infra/pull/30473
- [x] Add K8s conformance badges to Gardener and extensions: https://github.com/gardener/gardener/pull/8426
- [x] Update the [the conformance spreadsheet](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0&range=113:114) and reflect this update in our README.md: 
- [x] Adapt TODOs to update the kubernetes versions in e2e tests. (https://github.com/gardener/gardener/pull/7970)

**Comment by dguendisch** [comment]
I [ensured](https://github.com/gardener/test-infra/pull/458) the task "Ensure test-infra compatibility with conformance tests (example)" yesterday and hence ticked this task in the issue description (the needed description files were already uploaded a while ago).

**Comment by briantopping** [comment]
The update for vSphere was merged elsewhere and can be considered complete.

**Comment by ary1992** [comment]
All the tasks are completed.
/close
