### ISSUE TITLE
[GEP-22] Improved Usage of the `ShootState` API

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#8073]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What would you like to be added**:
This issue tracks the implementation of [GEP-22](https://github.com/gardener/gardener/blob/master/docs/proposals/22-improved-usage-of-shootstate-api.md) which was submitted with https://github.com/gardener/gardener/pull/8012:

## Tasks

- [x] https://github.com/gardener/gardener/pull/8082
- [x] https://github.com/gardener/gardener/pull/8112
- [x] https://github.com/gardener/gardener/pull/8136
- [x] https://github.com/gardener/gardener/pull/8143
- [x] https://github.com/gardener/gardener/pull/8144
- Further optimizations
  - [x] https://github.com/gardener/gardener/pull/8093
  - [x] https://github.com/gardener/gardener/pull/8146

**Comment by rfranzke** [comment]
All related tasks have been completed.

/close
