### ISSUE TITLE
Shoot Cluster Quota/Limits

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#81]
# Story
- As operator I want my clusters to not exceed certain quotas/limits so that I can control the costs.
- As provider I want to offer free-of-charge trial clusters to interested parties, but with certain quotas/limits so that I can control the costs.

# Motivation
We want to offer trial clusters, but we need quota/limits for those.

Per IaaS account (which we model today, maybe not ideally, as a secret):
* CPUs
* GPUs
* Main Memory
* Disk Size (per type)
* Cluster LBs
* Cluster PVC Size (per type)
* Cluster Lifetime (terminate clusters after given period of time)

Per Gardener project (which we model today, maybe not ideally, as a namespace):
* CPUs
* GPUs
* Main Memory
* Disk Size (per type)
* Cluster LBs
* Cluster PVC Size (per type)
* Cluster Lifetime (terminate clusters after given period of time)

Note: We may have/want to add more resource types over time.

This way we could achieve the following:
* Limit the overall costs for our trial IaaS account, e.g. 200 CPUs, 20 GPUs, 400 GB Main Memory, 8 TB `gp2` and 2 TB `io1` Disk, 100 LB services overall, 4 LB services and 200 GB `gp2` and 50 GB `io1` PVCs per cluster, cluster auto-termination after 28 days
* Allot each Gardener project only a tiny share, so that no single project can consume all resources, e.g. 10 CPUs, 0 GPUs, 20 GB Main Memory, 400 GB `gp2` and 100 GB `io1` Disk, 5 LB services overall, 4 LB services and 200 GB `gp2` and 50 GB `io1` PVCs per cluster, cluster auto-termination after 7 days
* But allow for exceptions like permitting one project to use GPUs, another to use more expensive `io1` disks, or yet another to extend the lifetime of their clusters

See `https://<redacted>/kubernetes/garden-resources-redesign/tree/master/garden-trial`.

# Acceptance Criteria
- [x] All clusters within one project are bound by the project quota/limits if they are using the trial quota/limits.
- [x] All clusters that are using the trial quota/limits are bound by the same overall.
- [x] The cluster lifetime is respected and the cluster gets deleted when it reaches its planned end of lifetime, but the lifetime can be extended (within the limits of the maximum lifetime, i.e. if the maximum lifetime is e.g. 7 days, a cluster lifetime can be repeatedly extended by *up to* 7 days from the current date, but never more).

# Implementation Proposal
- Most of these quotas can be enforced by an [admission controller](https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks) in the garden cluster, but the LBs and PVC size quotas will require similar controllers in the respective shoot clusters themselves, which we can handle with lower priority/later. Actually, it would be nice if LBs and PVC size quotas could be specified on the IaaS account level for the entire IaaS account, but that would require the shoot cluster admission controller to call back to the garden cluster, which is currently not possible (not reachable), so let's go with the per-cluster simplification.
- We support worker count min/max, i.e. cluster auto-scaling. Check the max requirements against the quota, i.e. assume the worst case as long as we don't get the information from the machine controller manager.
- If quotas are set for the IaaS account and the Gardener project, both must comply (simplest strategy for now).
- Make sure a cluster member can't change these quotas. Later we may allow that, e.g. in a non-trial use case a customer purchases a certain quantity of resources and allots it to its projects.
- Consider having independent `ResourceQuota`s and admission controllers (per quota) or combine them into one in the first step, but this may make later extensions, especially when we open source, somewhat harder (still, if it speeds us up, let's go with a combined `ResourceQuota` and admission controller)

Implement tracking of shoot cluster resources (specified by quotas) gradually, e.g.:
1. The resources are only determined statically. This means, only metrics that can be determined from the shoot manifest can be used. Also, the maximum resource consumption is assumed, e.g. when specifying auto scaling from 1 to 4 workers with a 2 CPU workers each, assume 8 CPUs are added to the quota metric.
2. Most resources are still determined statically, but for the amount of used CPUs the machine controller manager (the machine resources) is used to deliver the exact amount of current machines and thus the used CPUs, GPUs, main memory and disk (per worker).
3. Dynamically determine all resources specified in the quota metrics. This requires the quota controller to call back to the garden cluster, which is currently not possible.

Let's have 2 quota controllers therefore:
- One in the garden cluster implementing (1) and then improving it with (2)
- Another one as part of the shoot cluster control plane in the seed cluster regulating the remainder (3):
  - Project quota disk minus shoot cluster worker disks is the maximum that may be used inside the shoot cluster
  - Project quota LBs minus shoot cluster LBs is the maximum that may be used inside the shoot cluster

That's not perfect, but good enough for our goal. We have some limits imposed, at least. Not perfect in regards to the overall trial quota either, but with enough shoot clusters it will average out and no single cluster can get too many resources/go beyond the project quota.

# Resources
- `ResourceQuota`, see [1](https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object) and [2](https://kubernetes.io/docs/tasks/administer-cluster/quota-memory-cpu-namespace)
- [Admission controllers](https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks)

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by mliepold** [comment]
## Tracking the quota status
Problem:
There is a problem with keeping the quota status in the status sub-resource of the quota.
With the current proposal there is only one quota resource for all projects that use the default quota.
### Proposals
1. Keep the quota states of all projects that use the default quota.
```
apiVersion: garden.sapcloud.io/v1beta1
kind: Quota
metadata:
  name: trial-aws-project-quota
  namespace: garden-trial
spec:
  scope: project
  clusterLifetimeDays: 14
  metrics:
    cpu: "20"
    memory: 400Gi
status:
  metrics:
  - project: "garden-project1"
    cpu: "6"
    memory: 20Gi
  - project: "garden-project2"
    cpu: "15"
    memory: 230Gi
```
2. Only keep the status at the quota object for the secret. For the project quotas determine the status on the fly at the admission controller. 
Like this the expensive calculation of the quota status for the secret is done independently in the quota controller. Only the status calculation for the project quota, which is much faster, is done in the admission controller during the shoot cluster creation.

### Solution
For now we will determine the status of any quota object on the fly at the admission controller (for secret and project quotas).
We will check the performance of the calculation. But as we don't expect hundreds of trial clusters, we expect the performance to be acceptable even for secret quotas.
In the future this can be improved.
--> see also this [comment](https://github.com/gardener/gardener/issues/81#issuecomment-364955428)

**Comment by mliepold** [comment]
## Event handling

### Quota Events:
- Create Quota:  
  1. Verify quota specification. Also check that a correct scope is set.
  2. For quota with scope "secret": Check the existence of referred secret and duplicate definitions (if owner references are used). 
  Note: No status is set at quota creation.
- Update Quota:  
  1. Verify quota specification. 
  2. Check: Only metrics and cluster lifetime are allowed to be changed.
  Note: No status is updated at quota update.
- Delete Quota:
  1.  Check for SecretBindings that use this quota.
     - If none exits, delete the quota resource.
     - If one or more exits, prevent the deletion.

### SecretBindings Events:
- Create/update SecretBinding:
   1. Verify that the referenced quota(s) exits in the specified namespace.
   2. Verify that the referenced secret exits in the specified namespace.
   3. Verify that the quota and secret namespaces are identical.

### Shoot Events:
- Create Shoot: 
  1. Check if the SecretBinding that is used for the shoot cluster has quotas referenced. 
  2. If no, nothing to do. Otherwise check for the scope of the quota(s):
      - Scope=secret: Calculate the status of the quota by getting all shoot resources that use the current secret binding. Take in account the currently created and deleted ones. 
**TODO** Clarify how to handle quota for shoots which are in deletion phase? 
      - Scope=project: Calculate the status of the quota by getting all shoot resource of the current project. Take in account the currently created and deleted ones. 
     
  3. Use this status to check if the creation of the cluster would violate any metric of the quota.
      - Quota violation: Prevent the creation of the shoot cluster and set an appropriate status at the shoot resource.
**TODO** How detailed should the quota violation be returned to the Dashboard?
      - No quota violation: Nothing to do. (see comment [Tracking the quota status](https://github.com/gardener/dashboard/issues/14#issuecomment-361025625)) 
   4. Start the creation of the shoot cluster.
- Shoot Reconciliation:
  1. Check if it is using a SecretBinding with quota references.
  2. If yes, check if the quota(s) have a cluster lifetime set.
  3. If yes, use the creation time of the cluster + the lifetime(s) to determine if the cluster has to be deleted. Take the stricter one!
  4. If yes, start the deletion event for the shoot.
- Update Shoot: 
  - Analog to "Create Shoot".
  - As no status is saved, no difference of the resources that the updated shoot cluster will use need to be considered.

**Comment by mliepold** [comment]
## Abstract
Currently every user or project owner has to bring its own secret(s) to create clusters.
In order to increase adoption of the Gardener, we want to introduce trial clusters.
But for these we need to introduce quotas to be able to limit the amount of created clusters and resources and thus the possible costs for a potential sponsor.

## Requirements
The quotas/limits need to be set for (account) secrets belonging to a Gardener project. 

In order to avoid the need to create specific trial projects and to copy trial secrets, secrets need to be referable from different namespaces (i.e. projects). 
Also individual projects that use a trial secret should only be allowed to use a certain share of the overall quota associated with it. Thus it is needed to set quotas on project level too.

By default every project using a trial quota should have a predefined quota.
But projects that have special needs can request an increase of their quota. 

Also the created trial cluster should automatically be cleaned up after a defined amount of days.

## Design

### Defining quotas
The Gardener UI will not support the creation of quotas (in the beginning). It has to be done via the K8S CLI for already existing secrets.
For this a new custom resource "Quota" of the gardener is used.
It has to be ensured by ClusterRoles that only gardener admins can set/update quotas in the trial namespace.

## Implementation
### Quota
```
apiVersion: garden.sapcloud.io/v1beta1
kind: Quota
metadata:
  name: trial-aws-secret-quota
  namespace: garden-trial
spec:
  scope: secret
  clusterLifetimeDays: 14
  metrics:
    cpu: "200"
    gpu: "20"
    memory: 4000Gi
    storage.standard: 8000Gi
    storage.premium: 2000Gi
    loadbalancer: "100"
```

Specification:
- **scope**: Defines if the quota is set for the (account) secret or for a project. Possible values: "secret" and "project"
- **clusterLifetimeDays**: Max. lifetime of a cluster in days.
- **metrics**: The individual metrics for the quota as described above.

**Note:**
The metric for _cpu_ uses the worst-case scenario with the maximum possible CPUs per cluster in the beginning, if auto scaling is set for clusters.
This means even if the actual amount of CPUs is not reached yet, the creation of new clusters could not be possible anymore! It ensures that the total costs can never be higher than defined by the quota.
But the operator of the week should monitor the actual amount of CPUs for a secret to possibly adjust the numbers.

### Quota Validator
Checks at quota creation and update if the provided fields and values are correct or if a field is immutable at update.

### Controllers
#### Quota Controller
The controller regularly checks all existing resources of kind "Shoot" for the annotation "shoot.garden.sapcloud.io/expirationTimestamp". If the expiration date is after the current date and the shoot still references a secret with a quota that has a clusterLifetime, the gardener triggers the deletion of this shoot cluster.
The user will get no notification before or when the cluster is deleted!

#### Quota Admission Controller
It checks the current status of the quotas that are used during the creation of a shoot cluster.
If the quota would be exceeded after the cluster creation, the creation will be prevented and the user gets an appropriate error message.

### Binding Secrets and Quotas
For every secret in a project namespace, a SecretBinding is created. It binds the secret with a possible quota for the secret. The referenced secret and quota will be in the same namespace.
Also for the Garden projects that can use a trial secret, a SecretBinding is created in the project namespace. It binds the trial secret with the secret quota and the (default) project quota.
These referenced objects reside in the trial namespace.

At the secret selection during the shoot creation, the Gardener UI will use all secret bindings in the current project.

### Open Issues
- Restrict the namespaces for trial secrets?

## Extended Scope
- It should also be possible to restrict the machine types of VMs that are created for a cluster, because the costs for the different VM types can differ a lot.
Setting for quota:
**shoots.machinetypes**: List of allowed machine types for the cluster
```
shoots.machinetypes: ["m4.large", "m4.xlarge"]
```
- Setting und modifying the (default) quota via the Gardener UI.

## Out of Scope
- Quota for max. amount of CPUs per user. 
This feature can't be implemented securely without a role concept in the gardener.
But without this feature, a misuse of certain users that create (too) many clusters has to be determined by the operator of the week.

**Comment by vlerenc** [comment]
@mliepold As discussed, let's keep it simple for now and dynamically calculate the used up resources whenever needed. We need this code anyhow (gathering the data) and could start with it at first (and improve it later when we see performance issues with it). That would simplify the first implementation as we wouldn't need to store and read the used up resources, don't have to find a solution for the shared default quota, and we would not need to implement a cleanup/reconcile step (e.g. once every 24h) in case the controller missed critical events like a cluster deletion and its status fails to represent the reality.

**Comment by dkistner** [comment]
Provided PR. As already discussed. Things are not covered so far...
- determination of resources, which are created within the Shoot cluster (PVs, LBs)
- admission for Shoot api-servers, to avoid the creation/increase of resources when Quota is exceeded

**Comment by vlerenc** [comment]
Thank you @dkistner.

**Comment by mliepold** [comment]
Questions / Open Issues:
- How are trial quotas identified? By a label or all quotas in the garden-trial namespace?
- When and by which component is the SecretBinding for a trial quota in a project created? At project creation or via cron job? Can all projects use the trial quota?
- Currently the quota field of a SecretBinding in immutable. So if a project requests a higher quota, it can't be changed.

**Comment by mliepold** [comment]
Questions / Open Issues:
- How are trial quotas identified? By a label or all quotas in the garden-trial namespace?
- When and by which component is the SecretBinding for a trial quota in a project created? At project creation or via cron job? Can all projects use the trial quota?
- Currently the quota field of a SecretBinding in immutable. So if a project requests a higher quota, it can't be changed.

**Comment by rfranzke** [comment]
> Currently the quota field of a SecretBinding in immutable. So if a project requests a higher quota, it can't be changed.

A new `SecretBinding` referencing a higher `Quota` would be needed to create and injected in the `Shoot` resources.

> How are trial quotas identified? By a label or all quotas in the garden-trial namespace?

All `Quota`s in the `garden-trial` namespace.

> When and by which component is the SecretBinding for a trial quota in a project created? At project creation or via cron job? Can all projects use the trial quota?

We will write a new controller creating `SecretBinding`s for the `Secret`s and `Quota`s in the `garden-trial` namespace in all our `Project` creation. This will not be part of Gardener itself as we want to leave it to the Gardener providers how to handle `Quota`s in case they want to support it.
