### ISSUE TITLE
☂️ [GEP-23] Autoscaling Shoot `kube-apiserver` via Independently Driven HPA and VPA

### ISSUE THREAD

**Issue by andrerun** [gardener/gardener#8259]
How to categorize this issue?
/area auto-scaling
/kind enhancement

This is an umbrella issue for implementing the changes proposed in [[GEP-23] Autoscaling Shoot `kube-apiserver` via Independently Driven HPA and VPA](https://github.com/gardener/gardener/blob/master/docs/proposals/23-autoscaling-kube-apiserver-via-independent-hpa-and-vpa.md).

## Tasks _(! this task list is work in progress)_
  - [gardener/gardener-custom-metrics](https://github.com/gardener/gardener-custom-metrics) repository
    - [x] Feature complete
    - [x] Test
      - [x] Unit tests
    - [x] Move to official repo&nbsp;&nbsp;&nbsp;
    - [x] CI, publishing/consumption setup
    - [ ] Documentation
    - [x] Add skaffold-based support for remote debugging
    - [x] Manually deploy `gardener-custom-metrics` for early field testing
    - [ ] Address code review comments:
        - https://github.com/gardener/gardener-custom-metrics/issues/5
        - https://github.com/gardener/gardener-custom-metrics/issues/6
    - [x] Cut `gardener-custom-metrics@v0.1.0` release: https://github.com/gardener/gardener-custom-metrics/releases/tag/v0.1.0
      - [x] Switch to AR: https://github.com/gardener/gardener-custom-metrics/pull/10
      - [x] Switch to REUSE license format: https://github.com/gardener/gardener-custom-metrics/pull/12
      - [x] Don't run with max concurrent reconciles 1: https://github.com/gardener/gardener-custom-metrics/pull/19
      - [x] Endless loop in the controller: https://github.com/gardener/gardener-custom-metrics/pull/17 
      - [x] Fix the example/ dir resources (leader election RBAC): https://github.com/gardener/gardener-custom-metrics/pull/20
      - [x] Go over the [component checklist](https://github.com/gardener/gardener/blob/master/docs/development/component-checklist.md) for the `gardener-custom-metrics` component:
        - [ ] Add readiness and liveness probes: https://github.com/gardener/gardener-custom-metrics/pull/18 reverted with https://github.com/gardener/gardener-custom-metrics/pull/24
        - [x] Restrict the secrets cache to watch only resources with the given names (`ca`, `gardener-access-gardener-custom-metrics`). It should also reduce the memory usage: https://github.com/gardener/gardener-custom-metrics/pull/23
        - [x] Restrict the endpoints operations to the garden namespace: https://github.com/gardener/gardener-custom-metrics/pull/22
    - [ ] Logging improvements: 
    - [ ] Run gardener-custom-metrics in active-active mode: 
  - `gardener/gardener` integration
    - [ ] Feature gate + GCMx deployment: https://github.com/gardener/gardener/pull/9570
    - [ ] CMHPA functionality: @andrerun 
    - [ ] Add docs
    - [ ] Make sure that CMHPA supports the annotation `alpha.control-plane.scaling.shoot.gardener.cloud/scale-down-disabled`: @ialidzhikov 
    - [ ] Fine tune the requests per seconds value in the HPA
    - [ ] Promote the feature gate
  - [ ] Observability for kube-apiserver utilization
    - [x] Federate resource utilization metrics: https://github.com/gardener/gardener/pull/9581
    - [ ] Add dashboards to garden/plutono for aggregated overview: https://github.com/gardener/gardener/pull/9643
  - (?) Support for gardener-operator (`virtual-kube-apiserver` and `gardener-apiserver`)
  - [ ] Prepare a machinery to gather observability data from the landscapes. Eventually prove that GEP-23 improves the autoscaling based on HPA and VPA: @andrerun

**Comment by vlerenc** [comment]
I guess we can close this one here, now that @ialidzhikov has implemented the VPAAndHPA feature gate @andrerun?

**Comment by andrerun** [comment]
Closing.
