### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.28”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#8291]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.28 is getting released on August 15th, you'll find the changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md

---

# Tasks
 
## Gardener

- [x] `gardener`: https://github.com/gardener/gardener/pull/8479
  - Release-independent tasks
    - Allow instantiating v1.28 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/features/featuregates.go
    - Update admission plugins in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/admissionplugins.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/component/shootsystem/shootsystem.go
    - Bump used Kubernetes version for local shoot and local e2e test
    - Bump `kubectl` version in https://github.com/gardener/gardener/blob/master/hack/tools.mk#L69
  - Good to know
    -  Swap support for `cgroup v1` is removed: (https://github.com/kubernetes/kubernetes/pull/118764).

## Test Infra

- [x] [Ensure test-infra compatibility](https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/README.md#run-conformance-tests-against-new-k8s-versions) with conformance tests ([example](https://github.com/gardener/test-infra/commit/231f14fd430cbfc76be8ae4f893b7fa0ddd484c5)): https://github.com/gardener/test-infra/pull/477

## Cloud Controller Managers

- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.28` branch from it (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/29
  - Maintain `release-v1.27` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/30
  - Maintain `release-v1.26` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/31
  - Maintain `release-v1.25` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/32

## Provider Extensions

- [x] `machine-controller-manager-provider-local`: https://github.com/gardener/machine-controller-manager-provider-local/pull/19
  - Bump `kindest/node` version in `node/Dockerfile` ([example](https://github.com/gardener/machine-controller-manager-provider-local/pull/19))
- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/650
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/813
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28
  - Update `cloud-controller-manager` images
- [x] `provider-azure`: https://github.com/gardener/gardener-extension-provider-azure/pull/734
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28
  - Update `cloud-controller-manager` images
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/652
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28
  - Update `cloud-controller-manager` images
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/679
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28
  - Update `cloud-controller-manager` images
- [x] `provider-vsphere`: https://github.com/gardener/gardener-extension-provider-vsphere/pull/476
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/292
  - Revendor `gardener/gardener` with support for 1.28 client creation
  - Update `README.md` with support for 1.28

## Cluster Autoscaler

- [x] Update cluster-autoscaler for K8s 1.28:
  - Adaptation of `gardener/autoscaler`: https://github.com/gardener/autoscaler/issues/246
  - Integration into `gardener/gardener`: https://github.com/gardener/gardener/pull/9095

## Follow-up items

- [x] Add K8s 1.28 support for Gardener to [kubernetes/test-infra](https://github.com/kubernetes/test-infra/): https://github.com/kubernetes/test-infra/pull/31443
- [x] Add K8s conformance badges to Gardener and extensions: https://github.com/gardener/gardener/pull/8977
- [x] Update the [the conformance spreadsheet](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0&range=126:127) and reflect this update in our README.md: https://github.com/kubernetes/test-infra/pull/31443, https://github.com/gardener/gardener/pull/8977
- [x] Adapt TODOs to update the kubernetes versions in e2e tests (#8533).

**Comment by rfranzke** [comment]
@oliver-goetz raised interest to take this over this time :)

**Comment by acumino** [comment]
/close
All relevant tasks completed.
