### ISSUE TITLE
Implement `ControlPlane` extension resource

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#881]
Part of #308.

It was not proposed in [GEP-1](https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md) but during discussion we came up with the idea to introduce a `ControlPlane` resource.
This resource is reconciled by an external provider specific controller running in the seed. It should create the provider specific control plane components (e.g., cloud-controller-manager + cloud-provider-config) needed for a shoot cluster.
Gardener will keep deploying the kube-apiserver, kube-controller-manager, kube-scheduler, and etcd. If the extension controller needs to modify these deployments it should use mutating webhooks to add its changes.

# Implementation Proposal

There is already https://github.com/gardener/gardener-extensions/pull/31 which can work as a baseline/reference implementation once merged.

# Definition of Done

- [x] Provider-specific extension controllers have been created for
  - [x] Alicloud [gardener/gardener-extensions#57, @stoyanr, ✅]
  - [x] AWS [gardener/gardener-extensions#52, @stoyanr, ✅]
  - [x] Azure [gardener/gardener-extensions#54, @mkoynov, ✅]
  - [x] GCP [gardener/gardener-extensions#55, @stoyanr, ✅]
  - [x] OpenStack [gardener/gardener-extensions#56, @svetlinas, ✅]
  - [x] Packet [gardener/gardener-extensions#109, @mkoynov, ✅]
  - [x] ~Local [discontinued]~
- [x] Required adaptions in Gardener [#1076, @stoyanr, ✅]
  - [x] The shoot reconciliation/deletion flow has been adapted that it will create/delete the `ControlPlane` extension resource into the seed instead of asking the cloud botanist to deploy the cloud-controller-manager + cloud-provider-config.
  - [x] The [control plane component Helm charts](https://github.com/gardener/gardener/tree/master/charts/seed-controlplane/charts) do only contain provider-specific configuration that is relevant for the control plane exposure (will be factored out separately).
  - [x] The [kubelet component Helm chart](https://github.com/gardener/gardener/tree/master/charts/seed-operatingsystemconfig/original/templates/kubelet) does no longer contain any provider-specific configuration.
  - [x] The functions `GenerateCloudProviderConfig`, `RefreshCloudProviderConfig`, `GenerateKubeAPIServerConfig`, `GenerateCloudControllerManagerConfig`, `GenerateKubeControllerManagerConfig`, `GenerateKubeSchedulerConfig` are removed from the [`CloudBotanist` interface](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/types.go).
  - [x] The `DeployCloudControllerManager` method has been removed from the hybrid botanist.
  - [x] It is checked before the shoot flow that an adequate extension has been registered to Gardener.
  - [x] It is ensured for shoots that already have been marked for deletion that the `ControlPlane` resource is created in order to allow a smooth migration.
  - [x] Documentation has been added to the `docs/extensions` folder that describes the contract between Gardener and the `ControlPlane` resource.
