### ISSUE TITLE
Deploy VPA for kube-scheduler

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener#886]
# Story
As an administrator, I would like to deploy VPA for kube-scheduler and make use of its recommendations to be able to manage larger clusters 

# Tasks
- [ ] Deploy VPA for kube-scheduler with the updater set to 'off' mode
- [ ] Create the necessary grafana dashboard showing actual vs recommended metrics
- [ ] Based on the observation, decide on the operation mode of the VPA 

# Acceptance Criteria
- [ ] Observe and compare the recommendations of VPA for kube-scheduler through Grafana dashboard
- [ ] Adapt VPA recommendations by switching the VPA Updater to 'initial' or as appropriate

**Comment by vlerenc** [comment]
See comment at #893. There are even more components like kube and cloud controller manager, maybe other control plane components as well, then everything that needs to be scaled based on load in the cluster itself like kube-proxy and calico. A gathering epic would be helpful, I guess. Either #16 or a new one (I don't mind if you close the old one).

**Comment by rfranzke** [comment]
Closing as it's done.
