### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.29”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#8871]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.29 is getting released on December 13th, you'll find the changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md
There is [this guide](https://github.com/gardener/gardener/blob/master/docs/development/new-kubernetes-version.md) for developers who want to work on adding support for a new Kubernetes version.

---

# Tasks
 
## Gardener

- [x] `gardener`:  https://github.com/gardener/gardener/pull/8976
  - Release-independent tasks
    - Allow instantiating v1.29 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/features/featuregates.go
    - Update admission plugins in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/admissionplugins.go
    - Update API groups in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/apigroups/apigroups.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/controllers.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/component/shootsystem/shootsystem.go
    - Bump used Kubernetes version for local shoot and local e2e test
    - Bump `kubectl` version in https://github.com/gardener/gardener/blob/master/hack/tools.mk#L69
  - "Good to know" changes / no action required
    - A new alpha feature is introduced for adding structured authentication configuration to the Kubernetes API server. https://github.com/kubernetes/kubernetes/pull/119142
    - A new alpha feature is introduced for adding structured authorization configuration to the Kubernetes API server. https://github.com/kubernetes/kubernetes/pull/120154
    - A new `ImageMaximumGCAge` field is added to Kubelet configuration, which allows a user to set the maximum age an image is unused before it's garbage collected. https://github.com/kubernetes/kubernetes/pull/121275

## Cloud Controller Managers

- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.29` branch from it (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/35
  - Maintain `release-v1.28` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/36
  - Maintain `release-v1.27` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/37
  - Maintain `release-v1.26` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/38
## Provider Extensions

- [x] `machine-controller-manager-provider-local`: https://github.com/gardener/machine-controller-manager-provider-local/pull/21
  - Bump `kindest/node` version in `node/Dockerfile` ([example](https://github.com/gardener/machine-controller-manager-provider-local/pull/19))
- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/688
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/873
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29
  - Update `cloud-controller-manager` images
- [x] `provider-azure`:  https://github.com/gardener/gardener-extension-provider-azure/pull/785
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29
  - Update `cloud-controller-manager` images
- [x] `provider-gcp`: https://github.com/gardener/gardener-extension-provider-gcp/pull/693
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29
  - Update `cloud-controller-manager` images
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/712
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29
  - Update `cloud-controller-manager` images
- ~~[ ] `provider-vsphere`: ~~
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/300
  - Revendor `gardener/gardener` with support for 1.29 client creation
  - Update `README.md` with support for 1.29

## Test Infra

- [x] [Ensure test-infra compatibility](https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/README.md#run-conformance-tests-against-new-k8s-versions) with conformance tests ([example](https://github.com/gardener/test-infra/commit/231f14fd430cbfc76be8ae4f893b7fa0ddd484c5)): https://github.com/gardener/test-infra/pull/484

## Cluster Autoscaler

- [x] Update cluster-autoscaler for K8s 1.29:
  - Adaptation of `gardener/autoscaler` https://github.com/gardener/autoscaler/issues/275
  - Integration into `gardener/gardener` https://github.com/gardener/gardener/pull/9822

## Follow-up items

- [x] Add K8s 1.29 support for Gardener to [kubernetes/test-infra](https://github.com/kubernetes/test-infra/): https://github.com/kubernetes/test-infra/pull/32063
- [x] Add K8s conformance badges to Gardener and extensions: 
- [x] Update the [the conformance spreadsheet](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0&range=114:115) and reflect this update in our README.md: 
- [x] Adapt TODOs to update the kubernetes versions in e2e tests https://github.com/gardener/gardener/pull/9069
- [x] Update `kindest/node` to `v1.29.0` 
    - https://github.com/gardener/gardener/pull/9108
    - https://github.com/gardener/gardener/pull/9155

**Comment by acumino** [comment]
/close
All task completed
