### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardener#8899]
# IPv6 support

## Table of Contents
- [Current State](#cs)
- [IPv6-only for provider local](#ipv6providerlocal)
- [IPv6-only for cloud infrastructure](#ipv6cloudinfra)
- [Dual-stack ingress traffic](#dsingress)
- [Single-stack Seed](#sss)
   1. [IPv4 Seed with IPv4 and IPv6 Shoot Cluster](#ipv4seed)
   2. [IPv6 Seed with IPv4 and IPv6 Shoot Cluster](#ipv6seed)
- [Dual-stack](#ds)
- [Migration from IPv4-only to Dual-stack](#migration)

## Current State <a name="cs"></a>

Previously, all shoot clusters provisioned by Gardener on the hyperscaler use IPv4 single-stack networking. A first endeavour was undertaken in [GEP-21](https://github.com/gardener/gardener/blob/master/docs/proposals/21-ipv6-singlestack-local.md) to add IPv6 single-stack networking support to Gardener for provider local.
When we want to add IPv6 single-stack networking support for the public cloud provider supported by gardener (alicloud, aws ,azure ,gcp, ...) we face a lot of restrictions. Infrastructure resources consumed by Gardener have only limited IPv6 support/capabilities. This makes it currently impossible to support a pure IPv6 single-stack networking in gardener provisioned shoot clusters for any of those cloud providers. Thus a dual-stack networking setup or a restricted setup in terms of functionality is required.

## IPv6-only support for provider local <a name="ipv6providerlocal"></a>

[GEP-21](https://github.com/gardener/gardener/blob/master/docs/proposals/21-ipv6-singlestack-local.md) proposed IPv6 support for provider local.
- [x] [IPv6 Single-Stack Support in Local Gardener](https://github.com/gardener/gardener/issues/7051)

## IPv6-only support for cloud infrastructure <a name="ipv6cloudinfra"></a>

...

### Changes in gardener/gardener-extension-provider-alicloud

...

### Changes in gardener/gardener-extension-provider-aws

- [x] Support `AWS Load Balancer Controller` to be able to deploy dualstack network loadbalancers: https://github.com/gardener/gardener-extension-provider-aws/pull/717
- [x] Configure infrastructure to allow creation of dualstack network loadbalancers: https://github.com/gardener/gardener-extension-provider-aws/pull/778
- [x] Support bring your own VPC case: https://github.com/gardener/gardener-extension-provider-aws/pull/834
- [x] Add documentation, how dual-stack network loadbalancer can be created: https://github.com/gardener/gardener-extension-provider-aws/pull/831

### Changes in gardener/gardener-extension-provider-azure

...

### Changes in gardener/gardener-extension-provider-gcp

- [ ] Support for regional proxy network loadbalancers (see https://cloud.google.com/load-balancing/docs/proxy-network-load-balancer#ext-proxy-netlb) to support automatic protocol translation (IPv6 => IPv4)
- [ ] Support for PROXY protocol with regional proxy network loadbalancers (see https://cloud.google.com/load-balancing/docs/proxy-network-load-balancer) to support preservation of client IP address
- [ ] Support GCP Ingress controller (https://github.com/kubernetes/ingress-gce) for IPv6 loadbalancer support: https://github.com/gardener/gardener-extension-provider-gcp/pull/848

...

### Changes in gardener/gardener-extension-provider-openstack

...

### Changes in gardener/external-dns-management

- [x] Support AAAA DNS records: https://github.com/gardener/external-dns-management/issues/340

## Single-stack Seed <a name="sss"></a>

Seed cluster should be capable to provision IPv4, IPv6 shoot clusters. The seed clusters itself uses a single stack network with a loadbalancer on the edge which translates the internet protocol version of the incoming traffic to the one supported in the seed cluster. The second place where the  internet protocol translation happens is in the vpn-seed-server in the controlplane of the shoot.

There are two possible scenarios:

### IPv4 Seed with IPv4 and IPv6 Shoot Cluster <a name="ipv4seed"></a>

The network in the seed cluster should run with IPv4. The seed should support provisioning of gardener shoot clusters with IPv4, IPv6 or dual-stack network. 

#### Changes in gardener/gardener

- [x] Add support for (simulated) scenario with IPv4 seed and IPv6 shoot cluster in local setup: https://github.com/gardener/gardener/pull/8983
- [x] All container images need to be pullable via an IPv4/IPv6 address from the container registry: https://github.com/gardener/gardener/pull/8748
- [ ] Support needs to be added for dual-stack entries for pods, nodes, services, like `10.244.0.0/16,2001:0DB8::/32`. When prefix delegation is used, IPv6 field for pods, nodes and services should be empty and filled in after infrastructure provisioning.
- [x] Validation needs to be adapted to support dual-stack entries: https://github.com/gardener/gardener/pull/10584
- [x] Apiserver proxy needs to support the case of IPv4 in the seed and IPv6 in the shoot: https://github.com/gardener/gardener/pull/8983
- [ ] VPN seed servers `NODE_NETWORK` needs to support an IPv4 CIDR and IPv6 CIDR in `NodeCIDR`.
- [x] VPN seed servers needs to listen on IPv4 and IPv6: https://github.com/gardener/gardener/pull/8830
- [x] Add dnsrecord of type AAAA for internal and external apiserver domain to hosted zones: https://github.com/gardener/gardener/pull/9289
- [ ] Configure cloud routes needs to be disabled in kube-controller manager and cloud-controller manager when provisioning a dual-stack shoot cluster or IPv6 shoot cluster.
- [x] Allow shoot node CIDR to be empty in IPv6-only shoots: https://github.com/gardener/gardener/pull/10533
- [x] Allow empty pod/service ranges in shoot spec: https://github.com/gardener/gardener/pull/10541
- [x] Set correct `IPFamilies` for HA VPN: https://github.com/gardener/gardener/pull/10622
- [x] Adapt `node-local-dns` to IPv6: https://github.com/gardener/gardener/pull/10678
- [x] Remove feature gate `IPv6SingleStack`: https://github.com/gardener/gardener/pull/10716

#### Changes in gardener/gardener-extension-provider-alicloud

...

#### Changes in gardener/gardener-extension-provider-aws

- [x] All container images need to be pullable via an IPv4/IPv6 address from the container registry: https://github.com/gardener/gardener-extension-provider-aws/pull/856
- [ ] NodeIPFamilies need to be set correctly in the cloud-provider-config.
- [ ] ~~Cloud-provider aws needs to be run with the correct nodeipam controller.~~
- [x] Cloud infrastructure needs to be provisioned with dualstack support in terraform and flow mode. VPC and subnets need an IPv4 and IPv6 CIDR range: https://github.com/gardener/gardener-extension-provider-aws/pull/1024
- [x] Assign IPv6 addresses and IPv6 prefixes to the instances: https://github.com/gardener/gardener-extension-provider-aws/pull/1024
- [x] [AWS-ipam-controller](https://github.com/gardener/aws-ipam-controller) needs to be deployed and `allocate-node-cidrs`needs to be disabled in kube-controller-manager and cloud-controller-manager when provisioning an IPv6 or dual-stack shoot cluster: https://github.com/gardener/gardener-extension-provider-aws/pull/984
- [x] Enable dns64 and nat64 for IPv6 shoot cluster: https://github.com/gardener/gardener-extension-provider-aws/pull/1082
- [x] Service range should be allocated from VPC range: https://github.com/gardener/gardener-extension-provider-aws/pull/1081
- [x] Add infrastructure-specific validation: https://github.com/gardener/gardener-extension-provider-aws/pull/1095
- [x] Always enable AWS load balancer controller for clusters with IPv6: https://github.com/gardener/gardener-extension-provider-aws/pull/1099

#### Create gardener/aws-ipam-controller

Cloud provider aws does not have a nodeipam controller right now. The node ipam controller should be capable of doing prefix delegation, taking the IPv6 prefix assigned by the cloud provider to the node and adding it to the kubernetes node object. As the `node.Spec.PodCIDRs` field can't be patched the operation needs to happen in one step (assigning IPv4 and IPv6 pod CIDR range).

- [ ] ~~A nodeipam controller needs to be added to cloud provider aws which supports IPv6 prefix delegation and dualstack mode: https://github.com/kubernetes/cloud-provider-aws/pull/679~~
- [x] Create a dedicated [aws-ipam-controller](https://github.com/gardener/aws-ipam-controller) 

#### Changes in gardener/machine-controller-manager-provider-aws

- [ ] Ipv6AddressCount and Ipv6PrefixCount needs to be set to assign an IPv6 address and an IPv6 prefix to the instance: https://github.com/gardener/machine-controller-manager-provider-aws/pull/128

#### Changes in gardener/gardener-extension-provider-azure

- [x] Add infrastructure-specific validation: https://github.com/gardener/gardener-extension-provider-azure/pull/993

...

#### Changes in gardener/gardener-extension-provider-gcp

- [x] Add infrastructure-specific validation: https://github.com/gardener/gardener-extension-provider-gcp/pull/878

...

#### Changes in gardener/gardener-extension-provider-openstack

- [x] Add infrastructure-specific validation: https://github.com/gardener/gardener-extension-provider-openstack/pull/886

...

#### Changes in gardener/gardener-extension-networking-calico

- [x] Fix network configuration for IPv6: https://github.com/gardener/gardener-extension-networking-calico/pull/486
- [x] Enable `host-local` ipam for IPv6: https://github.com/gardener/gardener-extension-networking-calico/pull/501
- [x] Disable SNAT for IPv6: https://github.com/gardener/gardener-extension-networking-calico/pull/547  

#### Changes in projectcalico/calico

Calico CNI supports only IPv6 with `calico-ipam` plugin, due to the fact that we rely on `host-local` ipam plugin we need to add IPv6 support for that to calico. An upstream [issue](https://github.com/projectcalico/calico/issues/8190) was opened.
- [x] Add IPv6 support for `host-local` ipam to calico. (seem to be fixed with newer calico release) => https://github.com/gardener/gardener-extension-networking-calico/pull/501

#### Changes in cilium/cilium
- [x] Add IPv6 support to cilium: https://github.com/gardener/gardener-extension-networking-cilium/pull/421
...

#### Changes in gardener/ci-infra
- [x] Copy images from ghcr and public.ecr.aws to artifact registry to support image pulls via AAAA records: https://github.com/gardener/ci-infra/pull/982

#### Changes in gardener/vpn2

- [x] Add IPv6 support to HA VPN: https://github.com/gardener/vpn2/pull/84, https://github.com/gardener/vpn2/pull/99 and https://github.com/gardener/gardener/pull/9774

### IPv6 Seed with IPv4 and IPv6 Shoot Cluster <a name="ipv6seed"></a>

...

## Dual-stack <a name="ds"></a>

Garden, seed and shoot cluster should run with dual-stack networking.

### Changes in gardener/gardener

- [x] Allow multiple ranges for node, pod & service networks: https://github.com/gardener/gardener/pull/9998
- [x] Dual-stack support for coredns: https://github.com/gardener/gardener/pull/10733
- [x] Dual-stack support for vpn: https://github.com/gardener/gardener/pull/10767#issuecomment-2449770159
- [x] Allow creation of dual-stack clusters: https://github.com/gardener/gardener/pull/10803
- [x] Fix kubelet CSRs to allow IPv6 addresses to be used: https://github.com/gardener/gardener/pull/10876
- [x] Extend local setup to support dual-stack: https://github.com/gardener/gardener/pull/11226
- [x] Allow dual-stack in `Garden`: https://github.com/gardener/gardener/pull/11251
- [ ] Adapt garden runtime/seed network policies to dual-stack
- [ ] Allow dual-stack in `Seed`
- [x] Add migration of kube-dns service to dual-stack: https://github.com/gardener/gardener/pull/12816

### Changes in gardener/gardener-extension-provider-aws

- [x] Allow dual-stack networking: https://github.com/gardener/gardener-extension-provider-aws/pull/1139
- [x] Create dual-stack loadbalancer: 
   - https://github.com/gardener/gardener-extension-provider-aws/pull/1160
   - https://github.com/gardener/gardener-extension-provider-aws/pull/1167

### Changes in gardener/aws-ipam-controller

- [x] Reflect primary IPFamily: https://github.com/gardener/aws-ipam-controller/pull/83

### Changes in gardener/gardener-extension-provider-gcp

- [x] [Support IPv6](https://github.com/gardener/gardener-extension-provider-gcp/issues/829)
- [x] Support for Dual-Stack: https://github.com/gardener/gardener-extension-provider-gcp/pull/848
- [x] Add documentation for dual-stack shoot clusters https://github.com/gardener/gardener-extension-provider-gcp/pull/923
- [x] Support GCP Ingress controller (https://github.com/kubernetes/ingress-gce) for IPv6 loadbalancer support: https://github.com/gardener/gardener-extension-provider-gcp/pull/848
- [ ] Automatically enable new load balancers for dual-stack: https://github.com/gardener/gardener-extension-provider-gcp/pull/1001

### Changes in gardener/vpn2
- [x] Add dual-stack support: https://github.com/gardener/vpn2/pull/112

### Changes in gardener/network-problem-detector

- [x] Execute checks for both IP address families: https://github.com/gardener/network-problem-detector/pull/83

...

## Migration from IPv4-only to Dual-stack <a name="migration"></a>

Cluster owners might want to migrate their existing IPv4-only shoot clusters to IPv6. The obvious first step in this journey is to be able to migrate a shoot cluster from IPv4-only to dual-stack.

Migration from dual-stack to IPv6-only is currently not supported by the cloud infrastructures, but may be supported at a later point in time.

### Changes in gardener/gardener
- [ ] Add constraint to track migration state: https://github.com/gardener/gardener/pull/11692

### Changes in gardener/gardener-extension-provider-aws
~~- [ ] Enable migration from single-stack IPv4 to dual-stack IPv4, IPv6: https://github.com/gardener/gardener-extension-provider-aws/pull/1252~~

### Changes in gardener/gardener-extension-provider-gcp
- [ ] Enable migration from single-stack IPv4 to dual-stack IPv4, IPv6: https://github.com/gardener/gardener-extension-provider-gcp/pull/1010

### Changes in gardener/gardener-extension-networking-calico
- [x] read migration state from constraint and configure calico components accordingly: https://github.com/gardener/gardener-extension-networking-calico/pull/615

### Changes in gardener/gardener-extension-networking-cilium
- [ ]Add support for single-stack to dual-stack networking migration and add provider status to network resource:
https://github.com/gardener/gardener-extension-networking-cilium/pull/539
...

**Comment by aghassemlouei** [comment]
While it seems as though a majority of the items that were outlined have been checked off; would it be safe to assume that Gardener now supports IPV6?
