### ISSUE TITLE
Deploy VPA for kube-apiserver

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener#893]
# Story
As an administrator, I would like to deploy VPA for kube-apiserver and make use of its recommendations to be able to manage larger clusters 

# Tasks
- [ ] Deploy VPA for kube-apiserver with the updater set to 'off' mode
- [ ] Create the necessary grafana dashboard showing actual vs recommended metrics
- [ ] Based on the observation, decide on the operation mode of the VPA 

# Acceptance Criteria
- [ ] Observe and compare the recommendations of VPA for kube-apiserver through Grafana dashboard
- [ ] Adapt VPA recommendations by switching the VPA Updater as appropriate

**Comment by vlerenc** [comment]
You have opened a couple of new tickets @padma. Shouldn't we rather first plan the steps, e.g. in an epic? Either #16 or a new one (I don't mind if you close the old one).

Specifically about this one, yesterday you showed plans for HVPA which would certainly be interesting to this ticket here, right?

**Comment by rfranzke** [comment]
Done with https://github.com/gardener/gardener/pull/1421
