### ISSUE TITLE
[GEP-19] Migrate monitoring stack to `prometheus-operator`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#9065]
**How to categorize this issue?**

/area dev-productivity monitoring
/kind enhancement

**What would you like to be added**:
The monitoring stack should be migrated from the current custom-built Helm charts to the [`prometheus-operator`](https://github.com/prometheus-operator/prometheus-operator/) as proposed in [GEP-19](https://github.com/gardener/gardener/blob/master/docs/proposals/19-migrating-observability-stack-to-operators.md).

**Why is this needed**:
GEP-19 has been accepted and merged a long while ago, hence we should strive for completing its implementation. Also, the garden cluster (managed via `gardener-operator`, ref #7016) does not have a monitoring stack yet. Also, this increases the development productivity by cleaning up technical debt and improving the code.

**Tasks**:

- Deployment of `prometheus-operator`
  - [x] Golang component package: https://github.com/gardener/gardener/pull/9067
  - [x] Deployment to garden cluster via `gardener-operator`: https://github.com/gardener/gardener/pull/9067
  - [x] Deployment to seed clusters via `gardenlet`: https://github.com/gardener/gardener/pull/9067
- Prometheis/Alertmanager responsible for seed cluster
  - [x] https://github.com/gardener/gardener/pull/9128
    - [x] https://github.com/gardener/gardener/pull/9179
    - [x] https://github.com/gardener/gardener/pull/9188
    - [x] https://github.com/gardener/gardener/pull/9189
  - [x] https://github.com/gardener/gardener/pull/9180
    - [x] https://github.com/gardener/gardener/pull/9193
    - [x] https://github.com/gardener/gardener/pull/9195
  - [x] https://github.com/gardener/gardener/pull/9200
    - [x] https://github.com/gardener/gardener/pull/9299
  - [x] https://github.com/gardener/gardener/pull/9159
    - [x] https://github.com/gardener/gardener/pull/9189
    - [x] https://github.com/gardener/gardener/pull/9190
    - [x] https://github.com/gardener/gardener/pull/9298
    - [x] https://github.com/gardener/gardener/pull/9387
- Prometheis/Alertmanager responsible for garden cluster
  - [x] https://github.com/gardener/gardener/pull/9301
  - [x] https://github.com/gardener/gardener/pull/9543
    - [x] https://github.com/gardener/gardener/pull/9587
  - [x] https://github.com/gardener/gardener/pull/9606
- Prometheus/Alertmanager responsible for shoot clusters
  - [x] https://github.com/gardener/gardener/pull/9257
    - [x] https://github.com/gardener/gardener/pull/9335
    - [x] https://github.com/gardener/gardener/pull/9338
    - [x] https://github.com/gardener/gardener/pull/9344
    - [x] https://github.com/gardener/gardener/pull/9416
  - [x] https://github.com/gardener/gardener/pull/9695
  - Adapt shoot Prometheus configuration (scrape configs, rules, ...) for components deployed by `gardenlet`
    - [x] https://github.com/gardener/gardener/pull/9737
    - [x] https://github.com/gardener/gardener/pull/9848
- Adapt how extensions provide their observability configuration
  - [x] [`provider-alicloud`](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/720
  - [x] [`provider-aws`](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/946
  - [x] [`provider-azure`](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/853
  - [x] [`provider-gcp`](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/754
  - [x] [`provider-openstack`](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/766
  - [x] [`provider-equinix-metal`](https://github.com/gardener/gardener-extension-provider-equinix-metal): https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/307
  - [x] [`networking-calico`](https://github.com/gardener/gardener-extension-networking-calico): https://github.com/gardener/gardener-extension-networking-calico/pull/394
  - [x] [`networking-cilium`](https://github.com/gardener/gardener-extension-networking-cilium): https://github.com/gardener/gardener-extension-networking-cilium/pull/307
  - [x] [`shoot-cert-service`](https://github.com/gardener/gardener-extension-shoot-cert-service): https://github.com/gardener/gardener-extension-shoot-cert-service/pull/257
  - [x] [`shoot-oidc-service`](https://github.com/gardener/gardener-extension-shoot-oidc-service): https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/193
  - [x] [`shoot-lakom-service`](https://github.com/gardener/gardener-extension-shoot-lakom-service): https://github.com/gardener/gardener-extension-shoot-lakom-service/pull/87
  - [x] [`shoot-networking-problemdetector`](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector): https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/142
  - [x] [`shoot-rsyslog-relp`](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp): https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/99
  - [x] [`registry-cache`](https://github.com/gardener/gardener-extension-registry-cache): https://github.com/gardener/gardener-extension-registry-cache/pull/187
- Miscellaneous
  - [x] https://github.com/gardener/gardener/pull/9163
  - [x] ~~Consider deployment of [admission webhook server](https://github.com/prometheus-operator/prometheus-operator/tree/main/example/admission-webhook)~~ (abandoned for now due to other, more important topics)
  - [x] https://github.com/gardener/gardener/pull/9624

---

**General notes** for the migration (taken from https://github.com/gardener/gardener/issues/6319):

- Add temporary migration code for the Persistent volume. This ensures that no data is lost.
   1. Find the "old" `pvc` and its `pv` and set `persistentVolumeReclaimPolicy=Retain`.
   2. Delete the "old" `pvc`.
   3. Create a Prometheus Object with a `volumeClaimTemplate` that references the `pv` with `volumeName=<existing-pv>`
   4. Migrate the data using an init container
   5. Remove the migration code after 1-2 releases
- Add all existing prometheus configuration to an `additionalScrapeConfig`. This will allow us to switch to the `prometheus-operator` without creating `PodMonitors` and `ServiceMonitors` for each component and instead do that migration step by step.
- Add all extension prometheus configuration to the same `additionalScrapeConfig`. This will allow extensions time to migrate as well.
- Existing rules should be replaced with `PrometheusRules`.
- Once all of these steps are completed, most of the configuration in the `additionalScrapeConfig` can be migrated to `PodMonitors` and `ServiceMonitors`.
