### ISSUE TITLE
☂️  [GEP-24] Shoot OIDC issuer 

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#9157]
**How to categorize this issue?**

/area security usability
/kind enhancement

This issue is to track the implementation of [GEP-24](https://github.com/gardener/gardener/blob/master/docs/proposals/24-shoot-oidc-issuer.md)

### Tasks:

- Gardener
  - [x] Expose feature through shoot annotation & `gardenlet` should adjust `kube-apiserver` flags https://github.com/gardener/gardener/pull/9196
  - [x] Create the `gardener-system-shoot-issuer` namespace https://github.com/gardener/gardener/pull/9196
  - [x] Sync metadata of shoot into the Garden cluster & extend seed authorizer https://github.com/gardener/gardener/pull/9354
  - [x] Introduce `ShootManagedIssuer` feature gate https://github.com/gardener/gardener/pull/9489
  - [x] Add documentation 
    - https://github.com/gardener/gardener/pull/9746
    - https://github.com/gardener/gardener/pull/9923
  - [x] ~Promote~ Remove `ShootManagedIssuer` feature gate https://github.com/gardener/gardener/pull/11078
- Discovery Server
  - [x] Implement `gardener-discovery-server` in a new repository
    - https://github.com/gardener/gardener-discovery-server/pull/1
    - https://github.com/gardener/gardener-discovery-server/pull/3
    - https://github.com/gardener/gardener-discovery-server/pull/4
    - https://github.com/gardener/gardener-discovery-server/pull/5
    - https://github.com/gardener/gardener-discovery-server/pull/6
    - https://github.com/gardener/ci-infra/pull/1561
    - https://github.com/gardener/ci-infra/pull/1564
    - https://github.com/gardener/gardener-discovery-server/pull/19
    - https://github.com/gardener/gardener-discovery-server/pull/21
    - https://github.com/gardener/gardener-discovery-server/pull/22
    - https://github.com/gardener/ci-infra/pull/1711
- Gardener Operator
  - [x] Install `gardener-discovery-server` via `gardener-operator` https://github.com/gardener/gardener/pull/9746

**Comment by dimityrmirchev** [comment]
The `ShootManagedIssuer` was removed with https://github.com/gardener/gardener/pull/11078. No more pending tasks.

/close
