### ISSUE TITLE
☂️ [GEP-25] Introduce `NamespacedCloudProfile`s

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#9504]
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:
In order to introduce `NamespacedCloudProfile`s (see [GEP-25](https://github.com/gardener/gardener/blob/master/docs/proposals/25-namespaced-cloud-profiles.md)) the following tasks need to be done:

- [x] Gardener Enhancement Proposal #9142
- [x] API Changes #9440
- [x] Adjust admission controller of known providers (after vendored to API adjustments)
  - [x] Alicloud: part of https://github.com/gardener/gardener-extension-provider-alicloud/pull/755
  - [x] AWS: https://github.com/gardener/gardener-extension-provider-aws/pull/1000
  - [x] Azure: https://github.com/gardener/gardener-extension-provider-azure/pull/922
  - [x] GCP: https://github.com/gardener/gardener-extension-provider-gcp/pull/853
  - [x] OpenStack: https://github.com/gardener/gardener-extension-provider-openstack/pull/834
  - [x] [Ironcore](https://github.com/ironcore-dev/gardener-extension-provider-ironcore): https://github.com/ironcore-dev/gardener-extension-provider-ironcore/pull/636
- [x] Gardener adjustments
  - [x] Default `shoot.spec.cloudProfile.kind` to `CloudProfile`: https://github.com/gardener/gardener/pull/10093
  - [x] Adjust admission plugins
  - [x] Adjust `SeedAuthorizer`: https://github.com/gardener/gardener/pull/10485
  - [x] Adjust `Cluster` resource handling
  - [x] Add `NamespacedCloudProfile` controller: #10266
- [x] Migrate `shoot.spec.cloudProfileName` to `cloudProfile` field ~~if feature is enabled~~
	- [x] Transfer field information
	- [x] Automatically set `shoot.spec.cloudProfile` when  `shoot.spec.cloudProfileName` is configured
	- [x] With https://github.com/gardener/gardener/pull/10093 `shoot.spec.cloudProfileName` and `shoot.spec.cloudProfile` are synced in both directions
- [x] Further dependencies and usages to keep an eye on
  - [x] Make [gardenctl](https://github.com/gardener/gardenctl-v2) aware of `NamespacedCloudProfile`s: https://github.com/gardener/gardenctl-v2/pull/462
  - [x] Inventory project
- [x] Graduate feature gate to `beta`: https://github.com/gardener/gardener/pull/11289
- [x] Graduate feature gate to `GA`: https://github.com/gardener/gardener/pull/12620
- [x] Remove feature gate with Gardener `v1.128`: https://github.com/gardener/gardener/pull/13020
- [x] Deprecate `shoot.spec.cloudProfileName` field: https://github.com/gardener/gardener/pull/11816
- [x] Revisit future enhancements, e.g. support "custom" os images for projects (cc @marwinski @dguendisch).
  - [x] Fix manual status updates: https://github.com/gardener/gardener/pull/10937
    - [x] g/g: https://github.com/gardener/gardener/pull/11036
    - [x] AWS: https://github.com/gardener/gardener-extension-provider-aws/pull/1169
    - [x] Azure: https://github.com/gardener/gardener-extension-provider-azure/pull/1039
    - [x] GCP: https://github.com/gardener/gardener-extension-provider-gcp/pull/942
    - [x] Openstack: https://github.com/gardener/gardener-extension-provider-openstack/pull/930
    - [x] Alicloud: part of https://github.com/gardener/gardener-extension-provider-alicloud/pull/755
  - [x] Make use of `SingleObjectCache`: https://github.com/gardener/gardener/pull/11014 (cleanup prior implementation).
  - [x] Support custom machine images and versions: https://github.com/gardener/gardener/pull/10629
    - [x] adjust known provider-extensions (after vendoring to g/g version `v1.108.0`)
      - [x] Alicloud: part of https://github.com/gardener/gardener-extension-provider-alicloud/pull/755
      - [x] AWS: https://github.com/gardener/gardener-extension-provider-aws/pull/1136
      - [x] Azure: https://github.com/gardener/gardener-extension-provider-azure/pull/1016
        - [x] Fix validation regarding architectures: https://github.com/gardener/gardener-extension-provider-azure/pull/1021
      - [x] GCP: https://github.com/gardener/gardener-extension-provider-gcp/pull/918
      - [x] OpenStack: https://github.com/gardener/gardener-extension-provider-openstack/pull/911
  - [x] [Allow switching](https://github.com/gardener/gardener/pull/10629#discussion_r1802903487) (back) from a `NamespacedCloudProfile` to its parent `CloudProfile`: https://github.com/gardener/gardener/pull/10811
  - [x] Fix status calculation for custom images (versions) being added to the `CloudProfile` after initial definition in the `NamespacedCloudProfile`: https://github.com/gardener/gardener/pull/11093

Future work / tracked separately:

- Implement necessary changes in dashboard: https://github.com/gardener/dashboard/issues/1971

**Comment by timuthy** [comment]
Update: I added another point to revisit a requested enhancement, to allow custom OS images in projects. We defined this out-of-scope for the initial shipment but list it in this issue as a reminder. (cc @dguendisch @marwinski)

**Comment by timuthy** [comment]
Awesome work @LucaBernstein 👏 🥳
