### ISSUE TITLE
☂️-Issue for "Support for Kubernetes v1.30”

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#9508]
/area open-source
/kind enhancement
/priority 3
/topology garden seed shoot

Kubernetes v1.30 is getting released on April 17th, you'll find the changelog here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md
There is [this guide](https://github.com/gardener/gardener/blob/master/docs/development/new-kubernetes-version.md) for developers who want to work on adding support for a new Kubernetes version.

---

# Tasks
 
## Gardener

- [x] `gardener`: https://github.com/gardener/gardener/pull/9689
  - Release-independent tasks
    - Allow instantiating v1.30 Kubernetes clients and update `README.md` and `docs/usage/supported_k8s_versions.md`
    - Update feature gates in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/features/featuregates.go
    - Update admission plugins in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/admissionplugins.go
    - Update API groups in https://github.com/gardener/gardener/blob/master/pkg/utils/validation/apigroups/apigroups.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/controllers.go
    - Update KCM controllers in https://github.com/gardener/gardener/blob/master/pkg/component/shootsystem/shootsystem.go
    - Bump used Kubernetes version for local shoot and local e2e test
    - Bump `kubectl` version in https://github.com/gardener/gardener/blob/master/hack/tools.mk#L69
  - Release-dependent tasks
    - In kubelet configuration, the `.memorySwap.swapBehavior` field now accepts a new value `NoSwap`, which becomes the default if unspecified. The previously accepted `UnlimitedSwap` value has been dropped.
   ([#122745](https://github.com/kubernetes/kubernetes/pull/122745)). See https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory.
  - "Good to know" changes / no action required
    - The deprecated `SecurityContextDeny` admission plugin, which has been deprecated since `v1.27`, has been removed. It is recommended to use the Pod Security Admission plugin instead, which has been available since v1.25. Refer to the [Kubernetes documentation](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny) for more information.
    - Kubelet would fail if NodeSwap was used with LimitedSwap and cgroupv1 node.([#123738](https://github.com/kubernetes/kubernetes/pull/123738))
    - The StorageVersionMigration API, previously available as a Custom Resource Definition (CRD), is now a built-in API in Kubernetes.
    - Added the `disable-force-detach` CLI option for `kube-controller-manager`. By default, it's set to `false`. When enabled, it prevents force detaching volumes based on maximum unmount time and node status. If activated, the non-graceful node shutdown feature must be used to recover from node failure. Additionally, if a pod needs to be forcibly terminated at the risk of corruption, the appropriate VolumeAttachment object must be deleted. ([#120344](https://github.com/kubernetes/kubernetes/pull/120344))
    - Alpha support for field selectors on custom resources has been added. With the `CustomResourceFieldSelectors` feature gate enabled, the CustomResourceDefinition API now allows specifying `selectableFields`. Listing a field there enables filtering custom resources for that CustomResourceDefinition in list or watch requests. ([#122717](https://github.com/kubernetes/kubernetes/pull/122717))
    - Contextual logging is now in beta and enabled by default. Check out the [KEP](https://github.com/kubernetes/enhancements/issues/3077) and [official documentation](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#contextual-logging) for more details.

## Cloud Controller Managers

- [x] `cloud-provider-gcp`
  - Maintain `legacy-cloud-providers` and create `release-v1.30` branch from it (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/49
  - Maintain `release-v1.29` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/48
  - Maintain `release-v1.28` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/50
  - Maintain `release-v1.27` branch (update container images and revendor latest Kubernetes patch): https://github.com/gardener/cloud-provider-gcp/pull/51

## Provider Extensions

- [x] `machine-controller-manager-provider-local`: https://github.com/gardener/machine-controller-manager-provider-local/pull/40
  - Bump `kindest/node` version in `node/Dockerfile` ([example](https://github.com/gardener/machine-controller-manager-provider-local/pull/19))
- [x] `provider-alicloud`: https://github.com/gardener/gardener-extension-provider-alicloud/pull/722
  - Revendor `gardener/gardener` with support for 1.30 client creation
  - Update `README.md` with support for 1.30
- [x] `provider-aws`: https://github.com/gardener/gardener-extension-provider-aws/pull/942
  - Revendor `gardener/gardener` with support for 1.30 client creation
  - Update `README.md` with support for 1.30
  - Update `cloud-controller-manager` images
  - Released with [`v1.55.0`](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.55.0)
- [x] `provider-azure`:  https://github.com/gardener/gardener-extension-provider-azure/pull/855
  - Revendor `gardener/gardener` with support for 1.30 client creation
  - Update `README.md` with support for 1.30
  - Update `cloud-controller-manager` and `cloud-node-manager` images
  - Released with [`v1.44.0`](https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.44.0)
- [x] `provider-gcp`:  https://github.com/gardener/gardener-extension-provider-gcp/pull/755
  - Revendor `gardener/gardener` with support for 1.30 client creation
  - Update `README.md` with support for 1.30
  - Update `cloud-controller-manager` images
  - Released with [`v1.36.0`](https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.36.0)
- [x] `provider-openstack`: https://github.com/gardener/gardener-extension-provider-openstack/pull/770
  - Revendor `gardener/gardener` with support for 1.30 client creation.
  - Update `README.md` with support for 1.30
  - Update `cloud-controller-manager` images
  - Released with [`v1.40.0`](https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.40.0)
- [x] `provider-equinix-metal`: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/309
  - Revendor `gardener/gardener` with support for 1.30 client creation
  - Update `README.md` with support for 1.30

## Test Infra

- [x] [Ensure test-infra compatibility](https://github.com/gardener/test-infra/blob/master/integration-tests/e2e/README.md#run-conformance-tests-against-new-k8s-versions) with conformance tests ([example](https://github.com/gardener/test-infra/commit/231f14fd430cbfc76be8ae4f893b7fa0ddd484c5)): https://github.com/gardener/test-infra/commit/0ce0b36d58fc996c6d5711bbbc3d698e3ff56e58

## Cluster Autoscaler

- [x] Update cluster-autoscaler for K8s 1.30: https://github.com/gardener/autoscaler/issues/304
  - Adaptation of `gardener/autoscaler`: https://github.com/gardener/autoscaler/pull/317
  - Integration into `gardener/gardener`: https://github.com/gardener/gardener/pull/10309

## Follow-up items

- [x] Add K8s 1.30 support for Gardener to [kubernetes/test-infra](https://github.com/kubernetes/test-infra/): https://github.com/kubernetes/test-infra/pull/32931
- [x] Add K8s conformance badges to Gardener and extensions: https://github.com/gardener/gardener/pull/10102
- [x] Update the [the conformance spreadsheet](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0&range=117:118) and reflect this update in our README.md: 
- [x] Adapt TODOs to update the kubernetes versions in e2e tests: https://github.com/gardener/gardener/pull/9745
- [x] Update `kindest/node` to `v1.30.0`: https://github.com/gardener/gardener/pull/9745

**Comment by shafeeqes** [comment]
All tasks are completed.
/close
