### ISSUE TITLE
Gardener fails to create shoots with > ~80 worker pools

### ISSUE THREAD

**Issue by hown3d** [gardener/gardener#9545]
**How to categorize this issue?**

/area scalability
/kind bug

**What happened**:
When attempting to create a shoot with over approximately 80 nodepools, the shoot becomes stuck in the `Create Processing` state. The shoot generates an error message stating: `Flow "Shoot cluster reconciliation" encountered task errors: [task "Configuring shoot worker pools" failed: retry failed with context deadline exceeded, last error: etcdserver: request is too large] Operation will be retried.`

Upon investigation, it was discovered that the `Worker` resource, which is created for the shoot, becomes excessively large due to each `WorkerPool` containing userData necessary for machine bootstrap. This exceeds the etcd's max-request-bytes limit of 1.5MiB for the worker resource.

**What you expected to happen**:
The shoot should be successfully created.

**How to reproduce it (as minimally and precisely as possible)**:
Create shoots with a large number (80-90+) of nodepools.

**Proposed Solution:**
Suggest replacing the [userData field in the WorkerPool type](https://github.com/gardener/gardener/blob/f6e3efa6fbaafb42025e14b6af8ee4b03d6a5cb4/pkg/apis/extensions/v1alpha1/types_worker.go#L145) with a secretReference. This approach aligns with the OperatingSystemConfig resource, which already stores its cloud_config in a secret. Refer to the [OperatingSystemConfig documentation](https://github.com/gardener/gardener/blob/master/docs/extensions/operatingsystemconfig.md?plain=1#L268-L308) for more details.

**Tasks**:

- [x] https://github.com/gardener/gardener/pull/9722
- Adapt `Worker` extensions (after `v1.95` has been released)
  - [x] [`provider-alicloud`](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/727
  - [x] [`provider-aws`](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/961
  - [x] [`provider-azure`](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/868
  - [x] [`provider-gcp`](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/767
  - [x] [`provider-openstack`](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/776
  - [x] [`provider-equinix-metal`](https://github.com/gardener/gardener-extension-provider-equinix-metal): https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/314
- [x] ~~After `gardener/gardener@v1.100` has been released~~: Drop deprecated `UserData` field from `extensions.gardener.cloud/v1alpha1.Worker` resource (originally done after `v1.100` release with https://github.com/gardener/gardener/pull/10220, but reverted with https://github.com/gardener/gardener/pull/10285), now planned after `gardener/gardener@v1.104`): https://github.com/gardener/gardener/pull/10542

**Environment**:

- Gardener version: v1.82.3
- Kubernetes version (use `kubectl version`): v1.26.14
- Cloud provider or hardware configuration: 
  - openstack-provider v1.39.2
  - coreos extension v1.21
- Others:
  - etcd-druid v0.20.0

**Comment by rfranzke** [comment]
We checked a `Worker` with > 80 pools and saw that we could reduce the size by ~90% when we referenced the `userData` instead of putting it inline.

**Comment by rfranzke** [comment]
For now, all related PRs have been opened. Still, we have to wait until `gardener/gardener@v1.100` has been released (end of July 2024) before we can finally cleanup the inlined, now deprecated `.spec.userData` field from the `extensions.gardener.cloud/v1alpha1.Worker` API. This is to give extensions enough time to adapt to the API change.
Before this is done, the issue cannot be closed.

**Comment by rfranzke** [comment]
All tasks have been completed.
/close

**Comment by rfranzke** [comment]
/reopen
The PR linked above (#10220) was confusing - it was supposed to close this issue, but due we have reverted the needed API cleanup with https://github.com/gardener/gardener/pull/10285, so we have to wait a bit longer. I'll update above issue description accordingly.
