### ISSUE TITLE
☂️ [GEP-26] Workload Identity - Trust Based Authentication

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#9586]
**How to categorize this issue?**
/area security
/kind enhancement

This is an umbrella issue for implementing the changes proposed in [GEP-26](https://github.com/gardener/gardener/blob/master/docs/proposals/26-workload-identity.md)

# Tasks

- Documentation
  - [x] #10347
  - [x] https://github.com/gardener/gardener/pull/12099
  - [x] https://github.com/gardener/gardener/pull/12296
  - [x] https://github.com/gardener/gardener/pull/12879
  - [x] https://github.com/gardener/gardener/pull/13383

## API Server

- [x] API spec for `WorkloadIdentity` #9780
- [x] API spec for `CredentialsBinding` #9626
- [x] API spec for `TokenRequest` #9813
- [x] Implement quotas and all other features of `SecretBinding` for `CredentialsBinding`
  - partially done with Allow shoots to use `CredentialsBinding` instead of `SecretBinding`
  - Quotas to support scope of type `WorkloadIdentity` #10346
- [x] Allow shoots to use `CredentialsBinding` instead of `SecretBinding`
  - #9853
  - #10020
  - #10172
  - #10327
  - #10365
- [x] Implement provider agnostic static validation of `WorkloadIdentity` #9780
- [x] Implement token issuer with verification of the provided context, if any #10042
- [x] Implement issuer url, minimal and maximal token duration configurations #9813
- [x] Write `sub` claim value into `WorkloadIdentity` status #9780
- [x] Deprecate `SecretBinding` in favour of `CredentialsBinding` https://github.com/gardener/gardener/issues/12324
  - https://github.com/gardener/gardener/pull/12804
- Extend Shoot API to allow extensions to use workload identity
  - [x] https://github.com/gardener/gardener/pull/13469
  - [x] https://github.com/gardener/gardener/pull/13552
  - `shoot-dns-service` https://github.com/gardener/gardener-extension-shoot-dns-service/issues/620
- [x] Extend Seed API to use workload identity for credentials instead of secrets
  - [x] https://github.com/gardener/gardener/pull/13680
  - ETCD Backup
    - [x] https://github.com/gardener/gardener/pull/11583
    - https://github.com/gardener/gardener/pull/11950
    - [x] https://github.com/gardener/gardener/pull/11959
    - [x] https://github.com/gardener/gardener/pull/12032
    - [x] https://github.com/gardener/gardener/pull/12087
    - [x] https://github.com/gardener/gardener/pull/11983
    - [x] https://github.com/gardener/gardener/pull/12168
    - [x] https://github.com/gardener/gardener/pull/12321
    - [x] https://github.com/gardener/gardener/pull/12347
    - [x] https://github.com/gardener/gardener/pull/12414
    - [x] https://github.com/gardener/gardener/pull/12516
    - [x] https://github.com/gardener/gardener/pull/12517
    - [x] https://github.com/gardener/gardener/pull/12924
  - DNS records
    - [x] https://github.com/gardener/gardener/pull/13680
- [x] https://github.com/gardener/gardener/pull/10786
  - https://github.com/gardener/gardener/pull/10784
- [x] #11238
  -  https://github.com/gardener/gardener/pull/11168
- [x] https://github.com/gardener/gardener/pull/12353
- [x] https://github.com/gardener/gardener/pull/12357

## Admission Controller

- [x] Extend Seed Authorizer to allow gardenlets to request only `CredentialsBindings` that they are responsible for:
  - #9853
  - #10020
- [x] Extend Seed Authorizer to allow gardenlets to request workload identity tokens only for `WorkloadIdentity` that they are responsible for:
  - #10239
  - #10298

## Controller Manager

- [x] https://github.com/gardener/gardener/pull/11962

## Gardenlet

- [x] Update shoot reconciliation loop to create/update `cloudprovider` secret with the workload identity annotations and metadata in the seed cluster #10239
- [x] Implement gardenlet controller that reconciles the workload identity secrets and maintain the token valid #10298
- [x] https://github.com/gardener/gardener/pull/10383
  - https://github.com/gardener/gardener/pull/10371
- [ ] Support manual rotation of the workload identity token when the referring resource is annotated with `gardener.cloud/operation=renew-workload-identity-token`
- [x] Fix bug where shoot care controller uses outdated credentials config https://github.com/gardener/gardener/pull/10672
- [x] https://github.com/gardener/gardener/pull/11832
- [x] https://github.com/gardener/gardener/pull/12372
- [x] https://github.com/gardener/gardener/pull/13060
- [x] https://github.com/gardener/gardener/pull/13282
- Expose Gardenlet Configuration Used to Control the Duration of Requested Workload Identity Tokens https://github.com/gardener/gardener/issues/13669
- [x] https://github.com/gardener/gardener/pull/13720

## Operator

- [x] Generate and rotate workload identity signing key #10313
- [x] Adapt gardener-apiserver deployment:
  - #9813
  - #10042
- [x] Configure gardener discovery server to serve the workload identity documents https://github.com/gardener/gardener/pull/10538

## Discovery Server

- [x] Publish the public OIDC discovery documents via the GEP-24 discovery server https://github.com/gardener/gardener-discovery-server/pull/60

## Extensions

- [x] Add Accessor and ProviderType for security.garden.cloud API group #10499
- [x] Validation disallowing usage of `WorkloadIdentity` when the extension provider has not implemented support yet.
  - https://github.com/gardener/gardener-extension-provider-aws/pull/1047
  - https://github.com/gardener/gardener-extension-provider-azure/pull/957
  - https://github.com/gardener/gardener-extension-provider-gcp/pull/832
  - https://github.com/gardener/gardener-extension-provider-openstack/pull/845
  - https://github.com/gardener/gardener-extension-provider-alicloud/pull/738
  - https://github.com/gardener/gardener-extension-provider-openstack/pull/1150

### AWS

- [x] Enhance MCM to use credentials mounted as volume: https://github.com/gardener/machine-controller-manager-provider-aws/pull/177
- [x] Validation of the `WorkloadIdentity` resource: https://github.com/gardener/gardener-extension-provider-aws/pull/1141
- [x] Infrastructure controller to retrieve individual tokens per cluster and use them for authentication: https://github.com/gardener/gardener-extension-provider-aws/pull/1141
- [x] Extension admission controller adjusts the secret with the token and metadata: https://github.com/gardener/gardener-extension-provider-aws/pull/1141
- [x] Add Workload identity support to IPAM controller: https://github.com/gardener/aws-ipam-controller/pull/59
- [x] Add Workload identity support to Custom Route controller: https://github.com/gardener/aws-custom-route-controller/pull/47
- [x] Improve workload identity documentation https://github.com/gardener/gardener-extension-provider-aws/pull/1361
- [x] Set AWS_REGION for cloud controller manager https://github.com/gardener/gardener-extension-provider-aws/pull/1363
- [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1373
- [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1389
- [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1461
- [x] https://github.com/gardener/gardener-extension-provider-aws/pull/1629

### Azure

- [x] Enhance MCM to use credentials mounted as volume: https://github.com/gardener/machine-controller-manager-provider-azure/pull/167
- [x] Validation of the `WorkloadIdentity` resource https://github.com/gardener/gardener-extension-provider-azure/pull/999
- [x] Infrastructure controller to retrieve individual tokens per cluster and use them for authentication:  https://github.com/gardener/gardener-extension-provider-azure/pull/999
- [x] Extension admission controller adjusts the secret with the token and metadata: https://github.com/gardener/gardener-extension-provider-azure/pull/999
- [x] Update `azurerm` terraform provider to 3.47.0 https://github.com/gardener/terraformer/pull/156
- [x] Add Workload identity support to remedy controller https://github.com/gardener/remedy-controller/pull/64
- [x] Correctly mount workload identity token to csi driver controller https://github.com/gardener/gardener-extension-provider-azure/pull/1143
- [x] Improve workload identity documentation https://github.com/gardener/gardener-extension-provider-azure/pull/1155
- [x] https://github.com/gardener/gardener-extension-provider-azure/pull/1204
- [x] https://github.com/gardener/gardener-extension-provider-azure/pull/1265
- [x] https://github.com/gardener/gardener-extension-provider-azure/pull/1277

### GCP

- Enhance MCM to use credentials mounted as volume
  - [x] https://github.com/gardener/machine-controller-manager-provider-gcp/pull/130
  - [x] Reenable support for workload identity credentials https://github.com/gardener/machine-controller-manager-provider-gcp/pull/155
- [x] Validation of the `WorkloadIdentity` resource https://github.com/gardener/gardener-extension-provider-gcp/pull/855
- [x] Infrastructure controller to serve the token on unique URL (localhost) per cluster https://github.com/gardener/gardener-extension-provider-gcp/pull/855
- [x] Extension admission controller adjusts the secret with the token and metadata https://github.com/gardener/gardener-extension-provider-gcp/pull/855
- [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/973
- [x] Improve validation of credential configs https://github.com/gardener/gardener-extension-provider-gcp/pull/1061
- [x] Clarify validation of workload identity config https://github.com/gardener/gardener-extension-provider-gcp/pull/1065
- [x] Improve workload identity documentation https://github.com/gardener/gardener-extension-provider-gcp/pull/1091
- [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/1102
- [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/1151
- [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/1163
- [x] https://github.com/gardener/gardener-extension-provider-gcp/pull/1209

### Alicloud

- [ ] Enhance MCM to use credentials mounted as volume
- [ ] Validation of the `WorkloadIdentity` resource
- [ ] Infrastructure controller to write the token on unique filepath per cluster
- [ ] Extension admission controller adjusts the secret with the token and metadata
- [x] https://github.com/gardener/gardener-extension-provider-alicloud/pull/803
- [x] https://github.com/gardener/gardener-extension-provider-alicloud/pull/837

## Enablement

- [x] Grant operators, users and viewers with permissions to manage `CredentialsBinding` and `WorkloadIdentity` https://github.com/gardener/gardener/pull/10587
- [x] Promote `ShootCredentialsBinding` to beta https://github.com/gardener/gardener/pull/10662
- [x] Promote `ShootCredentialsBinding` feature gate to GA https://github.com/gardener/gardener/pull/13530
- [x] Clean up the `ShootCredentialsBinding` feature gate https://github.com/gardener/gardener/pull/13576
- [x] Promote `DoNotCopyBackupCredentials` feature gate to GA https://github.com/gardener/gardener/pull/13564

## Development Setup

- [x] Enhance dev setup with extensions to allow usage of workload identity https://github.com/gardener/gardener/pull/10520
- [x] https://github.com/gardener/gardener/pull/12519

## Gardenctl

- [x] Add support for credentials binding https://github.com/gardener/gardenctl-v2/pull/464
- [x] https://github.com/gardener/gardenctl-v2/issues/406
- [x] https://github.com/gardener/gardenctl-v2/issues/521

## Dashboard

- [x] https://github.com/gardener/dashboard/issues/2147

## ETCD Backup Restore

- [x] https://github.com/gardener/etcd-backup-restore/pull/874
- [x] https://github.com/gardener/etcd-backup-restore/pull/892
- [x] https://github.com/gardener/etcd-backup-restore/pull/908

**Comment by dimityrmirchev** [comment]
## Current state

The current proposal allows changing `credentialsBinding.CredentialsRef` which is convenient but can also cause unwanted behavior. Let's imagine the following scenario. A user has created a `CredentialsBinding` that references a `Secret` that is controlled by another organisation and is in another namespace. The user can reference this `Secret` for the purpose of creating a trial cluster. Now once the user has finished experimenting they can create their own `Secret` and point the existing `CredentialsBinding` to it. This will lead to a change in the provider accounts and the resources created in the trial account will be considered orphaned. We want to avoid that.

## Proposal

I propose that we make `credentialsBinding.CredentialsRef` immutable and `shoot.CredentialsBindingName` mutable (but on condition). Migration from `shoot.SecretBindingName` to `shoot.CredentialsBindingName` will only be possible if the `SecretBinding` and the `CredentialsBinding` both reference exactly the same `Secret` and `Quota`s. We will allow changing the `shoot.CredentialsBindingName` when the user making the request has read permissions for both "old" and "new" credential. This will ensure that users that have access to a `CredentialsBinding` referencing a credential in another namespace cannot suddenly reference their own credential and leak the already created resources in another account. This check will only be made when a `Shoot` is updated, but not during creation.

**Comment by vpnachev** [comment]
Of the initially planned tasks, only support for Alicloud has left. Its implementation will be tracked in https://github.com/gardener/gardener-extension-provider-alicloud/issues/931. 

I am closing the issue as the feature is implemented and functional for AWS, Azure and GCP already, other tasks will be tracked in their own issues.

/close
