### ISSUE TITLE
Extension registration and automation for `gardener-operator`

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#9635]
**How to categorize this issue?**

/area usability
/area ops-productivity
/area open-source
/area ipcei
/kind enhancement

**What would you like to be added**:
The following concept aims at improving the overall experience and productivity for **operators**. A Gardener installation usually needs additional and tedious preparation tasks to be done, e.g. creating storage buckets for backups or managing DNS entries. All of those can be automated via `gardener-operator`.
They even overlap with requirements that were already implemented for shoot clusters, but never made it to the Garden due to conceptional reasons.

Therefore, we plan to add a new custom resource `Extension`:

🎯 _Goals_
- Registration of a provider extension for the Garden-Runtime and Shoot clusters at the same time.
  - Serves common tasks in Runtime cluster, e.g. reconciling `DNSRecord` or `BackupBucket` resources (`gardener-operator` will need to create those).
  - Will be translated into and deployed as `ControllerRegistration`/`ControllerDeployment` ([ref](https://github.com/gardener/gardener/blob/master/docs/extensions/controllerregistration.md)) in Garden cluster.
- Registration of an optional admission controller ([example](https://github.com/gardener/gardener-extension-provider-aws/tree/master/charts/gardener-extension-admission-aws)).
- Stick to Helm deployment logic ([ref](https://github.com/gardener/gardener-extension-provider-aws/blob/ddf6c5673da50787d96a4de9245ddf67a624c764/example/controller-registration.yaml#L8)) but only rely on OCI repositories to fetch charts/assets (similar to [Flux's support for OCI Repositories](https://fluxcd.io/flux/components/source/ocirepositories)).
- Add great defaulting for known extensions, hosted in `github.com/gardener`. This allows smaller and trial landscapes to be setup with a minimal `Extension` resources (see _Example 2_ below).

🙅‍♂️ _Non Goals_
- It's not planned to eliminate `ControllerRegistration`s. For complex or advanced configurations, operators should still consider their additional usage.

**`Extension` API**:

Fields of the `Extension` API are very similar to `ControllerRegistration`/`ControllerDeployment` as requirements and goals overlap for the main part.

_Example 1_:

```
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: aws
spec:
    resources: # optional - defaulted by Operator for well-known extensions
  # - kind: BackupBucket
  #   type: aws
  #   primary: true|false
  #   globallyEnabled: true|false # only valid if kind=Extension
  #   reconcileTimeout: 30s # only valid if kind=Extension
  #   lifecycle: {}
  #   workerlessSupported: true|false # only valid if kind=Extension
  version: # optional - defaulted by Operator for well-known extensions
  deployment: # optional - defaulted by Operator for well-known extensions
    admission:
      ociRepositoryURL: # optional - defaulted by Operator for well-known extensions
      type: helm
      providerConfig:
        values: {}
    extension:
      ociRepositoryURL: # optional - defaulted by Operator for well-known extensions
      type: helm
      providerConfig:
        values: {}
    # policy: OnDemand|Always
```

The `resources` configuration merges the extension handling for Garden and Shoot clusters, whereas the most part is irrelevant for the Garden and only needed to craft the `ControllerRegistration`.

With decent defaulting, we want the extension registration for operators to be as simple as the following:

_Example 2_:

```
apiVersion: operator.gardener.cloud
kind: Extension
metadata:
  name: aws
```

**Tasks:**

- Prerequisites
  - [x] https://github.com/gardener/gardener/pull/9924
  - [x] Introduce `class` in `extensions.gardener.cloud/v1alpha1.DefaultSpec`
- Registration and Deployment
  - [x] Extension registration in Virtual Garden Cluster for Seeds: https://github.com/gardener/gardener/pull/10006
  - [x] Extension Deployment in Runtime Garden Cluster
    - [x] #10255
    - [x] #10254
    - [x] #10518
  - [x] Admission controller deployment ([example](https://github.com/gardener/gardener-extension-provider-aws/tree/master/charts/gardener-extension-admission-aws)): #10277
  - [x] Care controller for periodic health checks: https://github.com/gardener/gardener/pull/11769
  - [x] OwnerRef change for [webhook configuration](https://github.com/gardener/gardener/blob/554451cd97e08099728fe9687e62e60ab6f9c88a/extensions/pkg/webhook/registration.go#L164): #10585
  - [x] Uninstall features
    - [x] https://github.com/gardener/gardener/pull/10650
    - [x] https://github.com/gardener/gardener/pull/11001
    - [x] https://github.com/gardener/gardener/pull/11058
    - [x] https://github.com/gardener/gardener/pull/11606
- `Garden` controller adaptations 
  - [x] https://github.com/gardener/gardener/pull/10645
- [x] https://github.com/gardener/gardener/pull/11192
- [x] https://github.com/gardener/gardener/pull/11801
- [x] https://github.com/gardener/gardener/pull/11329
- Adapt `Backup{Bucket,Entry}` and `DNSRecord` extensions (for now, others maybe later) to be able to run in a cluster twice (one resp. for garden, one resp. for seed) - also see `provider-local` adaptions in https://github.com/gardener/gardener/pull/10518
  - [x] [`gardener/gardener-extension-provider-alicloud`](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/746
  - [x] [`gardener/gardener-extension-provider-aws`](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/1100
  - [x] [`gardener/gardener-extension-provider-azure`](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/1030
  - [x] [`gardener/gardener-extension-provider-gcp`](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/905
  - [x] [`gardener/gardener-extension-provider-openstack`](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/901
- Push Helm charts to OCI registries (for both extension and admission components)
  - [x] [`gardener/gardener`](https://github.com/gardener/gardener): https://github.com/gardener/gardener/commit/cb947e812522dd42595012382db0465eeb6b3986, https://github.com/gardener/gardener/commit/75d338ab764e64fa36db607d166367437a90c606
  - [x] [`gardener/gardener-extension-provider-alicloud`](https://github.com/gardener/gardener-extension-provider-alicloud): https://github.com/gardener/gardener-extension-provider-alicloud/pull/734 https://github.com/gardener/gardener-extension-provider-alicloud/pull/737
  - [x] [`gardener/gardener-extension-provider-aws`](https://github.com/gardener/gardener-extension-provider-aws): https://github.com/gardener/gardener-extension-provider-aws/pull/1012 https://github.com/gardener/gardener-extension-provider-aws/pull/1020
  - [x] [`gardener/gardener-extension-provider-azure`](https://github.com/gardener/gardener-extension-provider-azure): https://github.com/gardener/gardener-extension-provider-azure/pull/920 https://github.com/gardener/gardener-extension-provider-azure/pull/933
  - [x] [`gardener/gardener-extension-provider-gcp`](https://github.com/gardener/gardener-extension-provider-gcp): https://github.com/gardener/gardener-extension-provider-gcp/pull/805 https://github.com/gardener/gardener-extension-provider-gcp/pull/815
  - [x] [`gardener/gardener-extension-provider-openstack`](https://github.com/gardener/gardener-extension-provider-openstack): https://github.com/gardener/gardener-extension-provider-openstack/pull/811 https://github.com/gardener/gardener-extension-provider-openstack/pull/828
  - [x] [`gardener/gardener-extension-provider-equinix-metal`](https://github.com/gardener/gardener-extension-provider-equinix-metal): https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/317
  - [x] [`gardener/gardener-extension-networking-calico`](https://github.com/gardener/gardener-extension-networking-calico): https://github.com/gardener/gardener-extension-networking-calico/pull/445 https://github.com/gardener/gardener-extension-networking-calico/pull/453
  - [x] [`gardener/gardener-extension-networking-cilium`](https://github.com/gardener/gardener-extension-networking-cilium): https://github.com/gardener/gardener-extension-networking-cilium/pull/369 https://github.com/gardener/gardener-extension-networking-cilium/pull/376 https://github.com/gardener/gardener-extension-networking-cilium/pull/377
  - [x] [`gardener/gardener-extension-os-gardenlinux`](https://github.com/gardener/gardener-extension-os-gardenlinux): https://github.com/gardener/gardener-extension-os-gardenlinux/pull/188
  - [x] [`gardener/gardener-extension-os-suse-chost`](https://github.com/gardener/gardener-extension-os-suse-chost): https://github.com/gardener/gardener-extension-os-suse-chost/pull/162
  - [x] [`gardener/gardener-extension-os-coreos`](https://github.com/gardener/gardener-extension-os-coreos): https://github.com/gardener/gardener-extension-os-coreos/pull/121
  - [x] [`gardener/gardener-extension-os-ubuntu`](https://github.com/gardener/gardener-extension-os-ubuntu): https://github.com/gardener/gardener-extension-os-ubuntu/pull/143
  - [x] [`gardener/gardener-extension-runtime-gvisor`](https://github.com/gardener/gardener-extension-runtime-gvisor): https://github.com/gardener/gardener-extension-runtime-gvisor/pull/138
  - [x] [`gardener/gardener-extension-registry-cache`](https://github.com/gardener/gardener-extension-registry-cache): https://github.com/gardener/gardener-extension-registry-cache/pull/229
  - [x] [`gardener/gardener-extension-shoot-dns-service`](https://github.com/gardener/gardener-extension-shoot-dns-service): https://github.com/gardener/gardener-extension-shoot-dns-service/pull/359 https://github.com/gardener/gardener-extension-shoot-dns-service/pull/362
  - [x] [`gardener/gardener-extension-shoot-cert-service`](https://github.com/gardener/gardener-extension-shoot-cert-service): https://github.com/gardener/gardener-extension-shoot-cert-service/pull/282
  - [x] [`gardener/gardener-extension-shoot-oidc-service`](https://github.com/gardener/gardener-extension-shoot-oidc-service): https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/222
  - [x] [`gardener/gardener-extension-shoot-lakom-service`](https://github.com/gardener/gardener-extension-shoot-lakom-service): https://github.com/gardener/gardener-extension-shoot-lakom-service/pull/98
  - [x] [`gardener/gardener-extension-shoot-falco-service`](https://github.com/gardener/gardener-extension-shoot-falco-service): https://github.com/gardener/gardener-extension-shoot-falco-service/pull/48
  - [x] [`gardener/gardener-extension-shoot-networking-problemdetector`](https://github.com/gardener/gardener-extension-shoot-networking-problemdetector): https://github.com/gardener/gardener-extension-shoot-networking-problemdetector/pull/166
  - [x] [`gardener/gardener-extension-shoot-networking-filter`](https://github.com/gardener/gardener-extension-shoot-networking-filter): https://github.com/gardener/gardener-extension-shoot-networking-filter/pull/163
  - [x] [`gardener/gardener-extension-shoot-rsyslog-relp`](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp): https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/147
  - [x] [`stackitcloud/gardener-extension-acl`](https://github.com/stackitcloud/gardener-extension-acl): https://github.com/stackitcloud/gardener-extension-acl/pull/114
- Adapt extension Helm charts to satisfy Garden deployment
  - [x] [`stackitcloud/gardener-extension-acl`](https://github.com/stackitcloud/gardener-extension-acl): https://github.com/stackitcloud/gardener-extension-acl/pull/121

**Comment by timuthy** [comment]
All initial tasks are finally completed, and the issue can be closed. 🥳
A big shoutout to everyone who contributed to this feature!
/close

**Comment by rfranzke** [comment]
That's great, well done folks :)
