### ISSUE TITLE
Extension webhooks don't have an `objectSelector`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#9864]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What would you like to be added**:
The extensions webhooks don't have and `objectSelector`s in the webhook's definitions. For example, see https://github.com/gardener/gardener-extension-provider-aws/blob/b985c85ea7bebe5812fee7769441e65b84767e2b/pkg/webhook/controlplane/add.go#L27-L41

This means that the corresponding controlplane webhook mutates every CREATE/UPDATE request for Deployments, VerticalPodAutoscalers and OperatingSystemConfigs.

Internally it is switching over the object kind and object names and decides whether it has to mutate something or not: https://github.com/gardener/gardener/blob/de03c8ee1103c1122c749f937de9b5cc79a386d9/extensions/pkg/webhook/controlplane/genericmutator/mutator.go#L131-L235

For example, for VPA the extension webhook only needs to mutate the `machine-controller-manager-vpa`. The way webhook is set up, it is called for every VPA requests and internally, client-side the webhook does the filtering by the above switch cases. The MCM VPA objects are < 5% of the all VPA objects on a Seed cluster. For the rest of the VPA objects 95% the webhook is called unnecessary.

This is problematic wrt to scalability reasons. The introduction of the VPA mutation caused the following issue to the vpa-recommender of ManagedSeeds. vpa-recommender consider itself unhealthy (failing liveness probe) if its control loop fails to update all VPA objects in the cluster in given amount of time. The introduction of the VPA webhook (https://github.com/gardener/gardener-extension-provider-aws/pull/774/files#diff-83a16519f79a8712837f7575101e67e321d6bac43f11b6486b48af12bca5d5acR47) made many vpa-recommender unhealthy on many Seeds.

> The long total time is caused by the relatively slow patch operations which are executed sequentially. A patch on a vpa object takes 110ms. This seems also "acceptable", but the vpa can not cope with high latency so well. It executes the updates sequentially and hence it adds up to 500s and that leads to the restarts.

> [...], the webhook call times are 100ms, which dominates the patch duration of 110ms.

The issue is also outlined in https://github.com/gardener/gardener/issues/9020#issuecomment-1900349709.

**Why is this needed**:
See above.

**Tasks**:
- [x] controlplane webhooks:
  - [x] gardener/gardener: https://github.com/gardener/gardener/pull/9981
  - [x] gardener/gardener-extension-provider-alicloud: https://github.com/gardener/gardener-extension-provider-alicloud/pull/731
  - [x] gardener/gardener-extension-provider-aws: https://github.com/gardener/gardener-extension-provider-aws/pull/989
  - [x] gardener/gardener-extension-provider-azure: https://github.com/gardener/gardener-extension-provider-azure/pull/905
  - [x] gardener/gardener-extension-provider-gcp: https://github.com/gardener/gardener-extension-provider-gcp/pull/789
  - [x] gardener/gardener-extension-provider-openstack: https://github.com/gardener/gardener-extension-provider-openstack/pull/797
- [x] cloudprovider-webhook
  - [x] gardener/gardener: https://github.com/gardener/gardener/pull/10027
  - [x] gardener/gardener-extension-provider-openstack: adopted in the extension with https://github.com/gardener/gardener-extension-provider-openstack/pull/816, cleaned up more with https://github.com/gardener/gardener-extension-provider-openstack/pull/823
  - [x] gardener/gardener-extension-provider-azure: adopted in the extension with https://github.com/gardener/gardener-extension-provider-azure/pull/909
- [x] shoot-webhook
  - [x] gardener/gardener: https://github.com/gardener/gardener/pull/10026
  - [x] gardener/gardener-extension-provider-aws: https://github.com/gardener/gardener-extension-provider-aws/pull/988
  - [x] gardener/gardener-extension-provider-azure: https://github.com/gardener/gardener-extension-provider-azure/pull/903
  - [x] gardener/gardener-extension-provider-alicloud: https://github.com/gardener/gardener-extension-provider-alicloud/pull/730
  - [x] gardener/gardener-extension-provider-equinix-metal: https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/316

**Comment by ialidzhikov** [comment]
I am closing this issue as completed as the only open PR is for provider-equinix-metal (ref https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/316) and it does not seem to be actively maintained anymore

/close
